build/compliance-build.yml
build/delaysign.targets
build/prbuild.yml
build/settings.targets
build/signedbuild.yml

**Description:**
Move the build folder to be able to create the ADO pipelines

Move the build folder to the repo to be able to create the ADO pipelines

---

src/AccessibilityInsights.CI/AccessibilityInsights.CI.nuspec
src/AccessibilityInsights.CI/App.config
src/AccessibilityInsights.CI/CI.csproj
src/AccessibilityInsights.CI/Program.cs
src/AxeWindows.sln

- Move the CI project to the repo.
- No update for the .nupspec yet.

Move the CI project to the repo

---

build/compliance-build.yml
build/prbuild.yml
build/signedbuild.yml

- Update nuget tool installer version to 5.0.0 in the pipelines definition to match the latest nuspec xml schema

update NuGet tool installer version to 5.0.0

---

src/props/version.props

Bump AxeWindows to version 0.1.1

---

docs/Overview.md
docs/RulesOverview.md

These are a couple of files adapted from Accessibility Insights for Windows. 

Seed the docs folder with a couple of files

---

src/AutomationTests/AutomationIntegrationTests.cs
src/AutomationTests/AutomationTests.csproj
tools/scripts/check-automation.ps1

- Add an E2E test to AutomationTests
- [Crossing the bridge](https://github.com/microsoft/axe-windows/pull/48#issuecomment-499989796) to update the check-automation script to use the new scan interface

Introducing automation e2e tests

---

src/Automation/Automation.csproj
src/Automation/Factory.cs
src/Automation/Interfaces/IFactory.cs
src/Automation/Interfaces/IInternalScanner.cs
src/Automation/Interfaces/IScanTools.cs
src/Automation/InternalScanner.cs
src/Automation/ScanTools.cs
src/Automation/ScanToolsBuilder.cs
src/Automation/SnapshotCommand.cs

This class extracts out the logic from SnapshotCommand which talks  to parts of AxeWindows that are outside the Automation package. This now means the logic of SnapshotCommand is now testable without Fakes.

Add InternalScanner class

---

src/ActionsTests/ActionsTests.csproj
src/ActionsTests/packages.config
src/AutomationTests/AutomationTests.csproj
src/AutomationTests/packages.config
src/CoreTests/CoreTests.csproj
src/CoreTests/packages.config
src/RulesTest/RulesTests.csproj
src/RulesTest/packages.config
src/TelemetryTests/TelemetryTests.csproj
src/TelemetryTests/packages.config

Please review by commit. Each commit has a description of the minimal change made.

Remove Fakes from AutomationUnitTests and Add Mocks

---

src/Automation/Interfaces/IInternalScanner.cs
src/Automation/InternalScanner.cs
src/Automation/SnapshotCommand.cs
src/AutomationTests/AutomationTests.csproj
src/AutomationTests/SnapshotCommandUnitTests.cs

The new tests use Moq, as opposed to the old tests which used Fakes.

Add unit tests for SnapshotCommand

---

src/Automation/SnapshotCommand.cs
src/CI/Axe.Windows.nuspec

Remove a couple of references to PowerShell

---

src/props/version.props

Preparing for release of Axe.Windows with updated Automation API.

Bump AxeWindows version to 0.2.0

---

src/CI/Axe.Windows.nuspec

Update package copyright to include contributors

---

src/props/version.props

Any future changes will not be part of the 0.2.0 release.

Bump AxeWindows version to 0.2.1

---

src/CI/Axe.Windows.nuspec

Also, replace "contributors" with Deque Systems

Update package authors in expected nuspec format

---

src/Automation/OutputFileHelper.cs
src/Automation/ScanResultsAssembler.cs
src/Rules/PropertyConditions/StringProperty.cs

TSA flagged 3 cases where it wants IFormatProvider. Some of these might be arguable, but I took the approach that it's harmless to fix them.

Add IFormatProvider in a few places flagged by TSA

---

src/props/version.props

Update package version after 0.2.0 release

---

src/Automation/Abstractions/ISystem.cs
src/Automation/Abstractions/ISystemFactory.cs
src/Automation/Abstractions/ISystemIO.cs
src/Automation/Automation.csproj
src/Automation/Concretions/System.cs
src/Automation/Concretions/SystemFactory.cs
src/Automation/Concretions/SystemIO.cs
src/Automation/Factory.cs
src/Automation/OutputFileHelper.cs
src/AutomationTests/AutomationTests.csproj
src/AutomationTests/OutputFileHelperUnitTests.cs
src/AutomationTests/SystemUnitTests.cs

Making the System abstractions take the same form as System. I'm interested to know if this makes the system abstractions easier to understand or to work with.

Refactor the System abstractions to take the same form as System

---

Contributing.md
README.md
docs/AccessingInternals.md
docs/AddUnitTests.md
docs/FAQ.md
docs/GitBranchSetup.md
docs/NewProject.md
docs/Overview.md
docs/RulesOverview.md
docs/SetUpDevEnv.md
docs/Telemetry.md
docs/UnitTestBarAndStandards.md

This is the initial add of most Axe.Windows documentation. Some existing files have been modified to be specific to Axe.Windows as well.

Add Axe.Windows documentation

---

docs/Automation.md

This updates the documentation for how to consume and use AxeWindows for automation purposes.

Updated documentation for automation

---

CODE_OF_CONDUCT.md
Contributing.md
README.md
docs/AccessingInternals.md
docs/AddUnitTests.md
docs/Overview.md
docs/RulesOverview.md

Microsoft documentation says to have headings use sentence case

Fix heading title case

---

src/CI/Axe.Windows.nuspec

Adding a link to the release notes in the nuspec file.

Add a URL link to release notes in nuspec

---

README.md

Providing a brief description of how Axe.Windows is used. Hoping this will provide more clarity about the package in the first place users are likely to look.

Add detail to the overview section in readme.md

---

src/CI/Axe.Windows.nuspec

While our logo discussions are ongoing, remove the logo from our package.

Remove logo from NuGet package

---

src/props/version.props

This will be the next version of Axe.Windows.

Increment version to v0.3.1

---

src/Win32/Win32.csproj

This is the expected name. It is how the file is picked up by the NuGet package.

Rename output file for Win32 project to Axe.Windows.Win32

---

src/UIAAssemblies/readme.md

Remove reference to SharedUx.csproj (it's not in Axe.Windows)

---

src/props/version.props

This is the next possible release version.

Bump version to 0.3.4

---

src/props/version.props

Bump version to next possible, 0.3.5

---

src/Actions/Actions.csproj
src/Actions/packages.config
src/Automation/Automation.csproj
src/Automation/packages.config
src/Core/Core.csproj
src/Core/packages.config
src/Desktop/Desktop.csproj
src/Desktop/packages.config
src/RuleSelection/RuleSelection.csproj
src/RuleSelection/packages.config
src/Rules/Rules.csproj
src/Rules/packages.config
src/SystemAbstractions/SystemAbstractions.csproj
src/Telemetry/Telemetry.csproj
src/Telemetry/packages.config
src/UnitTestSharedLibrary/UnitTestSharedLibrary.csproj
src/UnitTestSharedLibrary/packages.config
src/Win32/Win32.csproj

Update to Roslyn 2.9.6. No code changes were required

Update to Roslyn 2.9.6

---

src/ActionsTests/ActionsTests.csproj
src/ActionsTests/packages.config
src/AutomationTests/AutomationTests.csproj
src/AutomationTests/packages.config
src/CoreTests/CoreTests.csproj
src/CoreTests/packages.config
src/RulesTest/RulesTests.csproj
src/RulesTest/packages.config
src/SystemAbstractionsTests/SystemAbstractionsTests.csproj
src/TelemetryTests/TelemetryTests.csproj
src/TelemetryTests/packages.config
src/Win32Tests/Win32Tests.csproj
src/Win32Tests/packages.config

Use VS to update to Moq 4.13.1

Update to Moq 4.13.1

---

src/Actions/packages.config
src/Automation/packages.config
src/Core/packages.config
src/Desktop/packages.config
src/RuleSelection/packages.config
src/Rules/packages.config
src/SystemAbstractions/SystemAbstractions.csproj
src/Telemetry/packages.config
src/Win32/Win32.csproj

Update BinSkim to 1.5.1, add it where it was missing. Manual version of #180 

Update BinSkim to 1.5.1, add it where it was missing

---

src/Actions/packages.config

Remove System.Runtime.Extensions from Actions (it's not needed)

Remove System.Runtime.Extensions from Actions (it's not needed)

---

src/CI/Axe.Windows.nuspec
src/SystemAbstractions/SystemAbstractions.csproj
src/Win32/Win32.csproj

Update Microsoft.Win32.Registry to version 4.6.0 (including updating the nuspec file)

Update Microsoft.Win32.Registry to version 4.6.0

---

src/Actions/Actions.csproj
src/Actions/packages.config
src/ActionsTests/ActionsTests.csproj
src/ActionsTests/packages.config
src/Automation/Automation.csproj
src/Automation/packages.config
src/CI/Axe.Windows.nuspec
src/Core/Core.csproj
src/Core/packages.config
src/CoreTests/CoreTests.csproj
src/CoreTests/packages.config
src/CurrentFileVersionCompatibilityTests/App.config
src/CurrentFileVersionCompatibilityTests/CurrentFileVersionCompatibilityTests.csproj
src/CurrentFileVersionCompatibilityTests/packages.config
src/Desktop/Desktop.csproj
src/Desktop/packages.config
src/DesktopTests/DesktopTests.csproj
src/DesktopTests/packages.config
src/Fakes.Prebuild/Fakes.Prebuild.csproj
src/Fakes.Prebuild/packages.config
src/UnitTestSharedLibrary/UnitTestSharedLibrary.csproj
src/UnitTestSharedLibrary/packages.config

Bump Newtonsoft.Json from 9.0.1 to 12.0.2

---

src/Actions/Actions.csproj
src/Actions/packages.config
src/ActionsTests/ActionsTests.csproj
src/ActionsTests/packages.config
src/Automation/Automation.csproj
src/Automation/packages.config
src/CI/Axe.Windows.nuspec
src/Core/Core.csproj
src/Core/packages.config
src/CoreTests/CoreTests.csproj
src/CoreTests/packages.config
src/CurrentFileVersionCompatibilityTests/CurrentFileVersionCompatibilityTests.csproj
src/CurrentFileVersionCompatibilityTests/packages.config
src/Desktop/Desktop.csproj
src/Desktop/packages.config
src/DesktopTests/DesktopTests.csproj
src/DesktopTests/packages.config
src/Fakes.Prebuild/Fakes.Prebuild.csproj
src/Fakes.Prebuild/packages.config
src/UnitTestSharedLibrary/UnitTestSharedLibrary.csproj
src/UnitTestSharedLibrary/packages.config

Except for the nuspec change, all changes were made by Visual Studio.

Bump Newtonsoft.Json from 12.0.2 to 12.0.3

---

docs/AutomationReference.md

Adding text to let users know which APIs are considered supported or not supported by Accessibility Insights.

Add text to explicitly specify which APIs are supported by axe-windows

---

src/ActionsTests/ActionsTests.csproj
src/ActionsTests/app.config
src/ActionsTests/packages.config
src/AutomationTests/AutomationTests.csproj
src/AutomationTests/app.config
src/AutomationTests/packages.config
src/CoreTests/CoreTests.csproj
src/CoreTests/app.config
src/CoreTests/packages.config
src/CurrentFileVersionCompatibilityTests/App.config
src/CurrentFileVersionCompatibilityTests/CurrentFileVersionCompatibilityTests.csproj
src/CurrentFileVersionCompatibilityTests/packages.config
src/RulesTest/RulesTests.csproj
src/RulesTest/app.config
src/RulesTest/packages.config
src/TelemetryTests/TelemetryTests.csproj
src/TelemetryTests/app.config
src/TelemetryTests/packages.config
src/Win32Tests/Win32Tests.csproj
src/Win32Tests/app.config
src/Win32Tests/packages.config

- System.Runtime.CompilerServices.Unsafe
- System.Collections.Immutable

Update two NuGet dependencies

---

src/props/version.props

Updating the axe-windows version after release 0.3.5.

Bump axe-windows package to version 0.3.6 for next release

---

src/AutomationTests/AutomationIntegrationTests.cs

We recently added some "control sampler" apps to help pin our behavior with controls from different frameworks. These are __not__ intended to be exhaustive tests of framework controls. Instead, they are intended to pin the behavior of our rules and to prevent unintended consequences of rule additions or modifications. These apps currently rely on manual testing--this change wraps them in integration tests so that they run automatically.
The existing code includes a 10 second delay when starting the test app, since experience has shown that the pipeline machines are sometimes slow to respond to the newly started app. Rather than add 30 more seconds to the local unit tests, I've optimized the delay to be only 2 seconds when running on a machine outside of the build pipeline (we use the VSTS …

Automate scans of control sampler apps

---

src/SystemAbstractions/SystemAbstractions.csproj

This reverts commit 6666187752ee5cf7614ef393150614aa99654e44.

Revert "Add a temporary reference to System.Collections.Immutable (#298)"

---

src/props/version.props

Bump axe-windows to version 1.0.0

---

src/props/version.props

Bumping down because screen shots are not working in all cases.

Bump down the version of axe-windows to 0.9.0-prerelease

---

src/CLI/OptionsEvaluator.cs

Rename a method (PR feedback that I missed in the last PR)

---

README.md
docs/AutomationReference.md

- Add information about the new scanId parameter available in the IScanner.Scan method
- Add a reference on the project readme to the newly minted CLI

Update docs with scanId and CLI info

---

src/Automation/AxeWindowsActions.cs

This just removes one level of indent from a block of code.

Remove extra indent from a block of code

---

src/props/version.props

Bump axe-windows to version 0.9.1

---

src/props/version.props

Update the version to 0.9.2-prerelease

Update version to 0.9.2

---

src/props/version.props

Bump to version 0.9.5

---

src/ActionsTests/ActionsTests.csproj
src/AutomationTests/AutomationTests.csproj
src/CLITests/CLITests.csproj
src/CoreTests/CoreTests.csproj
src/DesktopTests/DesktopTests.csproj
src/OldFileVersionCompatibilityTests/OldFileVersionCompatibilityTests.csproj
src/RuleSelectionTests/RuleSelectionTests.csproj
src/RulesTest/RulesTests.csproj
src/SystemAbstractionsTests/SystemAbstractionsTests.csproj
src/TelemetryTests/TelemetryTests.csproj
src/Win32Tests/Win32Tests.csproj

VS suggested the update, so I clicked the update button. No impact on shipping code

Bump Microsoft.NET.Test.SDK from 16.5.0 to 16.6.0

---

src/CLI/CLI.csproj
src/CLI_Full/CLI_Full.csproj
src/RulesMD/RulesMD.csproj
src/RulesMD/packages.config

Manually making the change from PR #366.

Bump CommandLineParser to version 2.8.0

---

build/settings.targets
src/CLI/CLI.csproj
src/CLI_Full/CLI_Full.csproj
src/CLI_Installer/CLI_Installer.wixproj
src/CLI_Installer/Product.wxs
tools/scripts/BuildZippedCLI.ps1

Currently, we have two non-Microsoft-signed dependencies. This PR ensures they are signed with the 3rd party certificate (but not strong name signed by us) in both the CLI installer and zip. Signed build [here](https://dev.azure.com/mseng/1ES/_build/results?buildId=12609892&view=results).

Sign external dependencies

---

src/CI/Axe.Windows.nuspec

This PR updates our nuget package metadata based on internal guidance.

Update nuspec metadata per guidance

---

src/props/version.props

We are ready for the 1.0.0 release!

Update version to 1.0.0 & remove prerelease

---

src/props/version.props

All future changes belong to a version > 1.0.0.

Bump package to version 1.0.1

---

src/props/version.props

All future changes belong to a version > 1.0.1. Will not merge until 1.0.1 is actually released.

Bump package to version 1.0.2

---

src/props/version.props

Bump release version to 1.0.4 (merge after version 1.0.3 is released)

chore: Bump version to 1.0.4

---

src/props/version.props

chore: Bump version to 1.0.5

---

src/props/version.props

Bump to version 1.0.6 after releasing version 1.0.5

chore: Bump to version 1.0.6

---

src/props/version.props

Bump to version 1.0.7 (will be merged after 1.0.6 is released)

chore: Bump to version 1.0.7

---

Contributing.md
docs/GitBranchSetup.md

We've changed the default branch from `master` to `main`. Update the docs accordingly.

chore: Update docs to reflect the new default branch

---

src/CI/Axe.Windows.nuspec

We missed updating the .nuspec file with #514 and #555. This corrects those oversights.
The NuSpec file needs to match the internal versions or downstream assembly versioning is disrupted

chore: Update versions in nuspec file

---

src/props/version.props

This will be merged only after Axe.Windows 1.0.7 is released to NuGet
Each release needs to have a unique version

chore: Update version to 1.0.8

---

src/props/version.props

Bump the version (standard step when we release).
Maintain distinct released versions

chore: Bump version to 1.0.9

---

docs/CustomUIA.md

This PR contains an initial configuration file format for specifying custom UIA properties for which Axe Windows should register.
Part of feature 1845247 (internal access required to view).
This PR includes no functionality, just documentation on a possible config format. Code changes to follow in subsequent PRs.

feat(custom-uia): Configuration file spec

---

docs/CustomUIA.md

This PR updates the custom UIA properties documentation to reflect the current state of implementation.
Preparation for release, to be reverted once enums are implemented.

feat(custom-uia): Update docs to reflect current state

---

docs/AutomationReference.md
src/CLI/README.MD

This PR updates the CLI readme for custom UIA.

feat(custom-uia): Update the CLI readme

---

docs/RulesDescription.md

Janitorial: copies rules from pipeline.

chore: Update rules for upcoming release

---

src/props/version.props

This PR increments the version in preparation for the next release.
Release process.

chore: Bump version to 1.0.10

---

src/props/version.props

Janitorial: bump version after 1.0.10 release.

chore: Bump version to 1.0.11

---

docs/CustomUIA.md
src/Core/CustomObjects/Converters/EnumTypeConverter.cs
src/Core/CustomObjects/CustomProperty.cs
src/Core/Enums/CustomUIAPropertyType.cs
src/CoreTests/CustomObjects/ConfigTests.cs
src/CoreTests/CustomObjects/Converters/EnumConverterTests.cs
src/CoreTests/CustomObjects/CustomPropertyTests.cs
src/Desktop/UIAutomation/CustomObjects/Registrar.cs
src/DesktopTests/UIAutomation/CustomObjects/RegistrarTests.cs

This PR adds support for enums (such as used in PowerPoint).

feat(custom-uia): Add support for enumeration types

---

src/props/version.props

Janitorial: bump version number in preparation for release as custom UIA properties is now complete.

Bump version to 1.1.0

---

src/props/version.props

Janitorial: post-release version bump.

Bump version to 1.1.1

---

src/props/version.props

Bump version to 1.1.3 (routine action after releasing version 1.1.2)
Maintain unique versions

chore: Bump version to 1.1.3

---

src/props/version.props

Bump the version to 1.1.4
Bumping version to 1.1.4 after release of version 1.1.3

chore: Bump version to 1.1.4

---

src/Actions/Contexts/ElementContext.cs
src/Core/Bases/A11yElement.cs
src/Core/Results/ScanStatus.cs

When opening the project in a recent version of Visual Studio, the analyzer suggests some changes. These changes were made by accepting the suggested changes.
Reduce noise when opening project in Visual Studio

chore: Make some analyzer-suggested changes

---

src/Rules/Library/EdgeBrowserHasBeenDeprecated.cs
src/RulesTest/Library/EdgeBrowserHasBeenDeprecated.cs

#687 had a small typo in the class name. It has no impact on any user-facing aspect (including the docs), but it's still wrong

feat(framework-issues-logic): Fix typo

---

docs/CodeSampleLinks.md

Fix broken link. This was a PR comment from #709 but I didn't catch it until after the merge.

fix: Correct broken link

---

src/props/version.props

Bump the version number after we release version 1.1.4
We always do this after a release
We won't merge this PR until after the release of 1.1.4 has been completed.

chore: Bump version to 1.1.5

---

docs/FAQ.md
docs/VirusScannerExclusions.md

This adds docs about excluding the repo from virus scanners to improve app startup time
Document best practices

chore: Add docs for virus scanner exclusions

---

src/props/version.props

Bump the release version to 1.1.7. PR will only be merged after 1.1.6 is released
Standard procedure after each update

chore: Bump version to 1.1.7

---

src/Desktop/ColorContrastAnalyzer/Color.cs
src/Desktop/ColorContrastAnalyzer/ColorContrastRunner.cs
src/Desktop/ColorContrastAnalyzer/CountMap.cs
src/Desktop/ColorContrastAnalyzer/RowResultV2Accumulator.cs
src/Desktop/UIAutomation/A11yAutomation.cs
src/Desktop/UIAutomation/DesktopElement.cs
src/Desktop/UIAutomation/DesktopElementExtensionMethods.cs
src/Desktop/UIAutomation/EventHandlers/EventListenerBase.cs
src/Desktop/UIAutomation/EventHandlers/EventListenerFactory.cs
src/Desktop/UIAutomation/Patterns/AnnotationPattern.cs
src/Desktop/UIAutomation/Patterns/ScrollPattern.cs
src/Desktop/UIAutomation/Patterns/WindowPattern.cs
src/Desktop/UIAutomation/Support/TextRangeFinder.cs
src/Desktop/UIAutomation/TreeWalkers/TreeWalkerForLive.cs
src/Desktop/UIAutomation/TreeWalkers/TreeWalkerForTest.cs

This PR fixes various spelling and typographical errors found in strings and comments in the `Desktop` namespace.

chore: Fix various spelling and typographical errors in source code comments and strings (Desktop namespace)

---

src/Actions/Actions/DataManager.cs
src/Actions/Contexts/ElementDataContext.cs
src/Actions/Trackers/BaseTracker.cs
src/Actions/Trackers/MouseTracker.cs
src/ActionsTests/Misc/ExtensionMethodsTests.cs

This PR fixes various spelling and typographical errors found in strings and comments in the `Actions` namespace.

chore: Fix various spelling and typographical errors in source code comments and strings (Actions namespace).

---

src/props/version.props

Bump version to 1.1.8. We'll merge this after releasing version 1.1.7
Standard version maintenance

chore: bump version to 1.1.8

---

src/AutomationTests/ScanToolsBuilderTests.cs
src/AutomationTests/SnapshotCommandTests.cs

A PR comment in #757 suggested some unit test refactoring, which we put into a separate PR for clarity. These refactorings include:
- 2 classes use the `MockRepository` pattern, while no others do. For consistency, don't use it here, either
- Use fixtures and the `[TestInitialize]` pattern in the same 2 classes
- Move all mock verification into a separate `VerifyAllMocks` method
- Try to move most of the repeated mock setup into helper methods to help focus what each unit test does uniquely. It's possible to put so much into the helper classes that it's hard to discern what the unit test is actually doing. Hopefully these changes stop short of that point.
Make the unit tests more readable and more consistent

chore: Refactor unit tests

---

docs/AutomationReference.md

This PR updates documentation for the Axe.Windows 2.0 API and adds a migration guide for 1.x users.
Part of feature [1986365](https://mseng.visualstudio.com/1ES/_workitems/edit/1986365) to add an asynchronous API (internal access required to view).
- [n/a] Addresses an existing issue: #000

feat(async-api): Update documentation for the Axe.Windows 2.0 API

---

src/Automation/Resources/ErrorMessages.Designer.cs
src/Automation/Resources/ErrorMessages.resx
src/AutomationTests/AutomationIntegrationTests.cs

Follow up on PR comment: https://github.com/microsoft/axe-windows/pull/759#issuecomment-1275385362, removing error codes that are no longer relevant
Clean up code

chore: Remove unnecessary error codes

---

src/CLI/README.MD
src/props/version.props

Bump version from 2.0.0 to 2.0.1. This will be merged after version 2.0.0 releases
Routine version maintenance

chore: Bump version after release

---

src/Automation/ScanResultsAssembler.cs
src/Core/Bases/A11yElement.cs
src/Rules/Extensions/ExtensionMethods.cs
src/Rules/RuleInfo.cs
src/Rules/RuleRunner.cs

Splitting PR feedback into a separate PR, since these changes touch so many files: https://github.com/microsoft/axe-windows/pull/768#issuecomment-1284207447

feat(localization): Remove instances of FormattableString

---

build/signedbuild.yml

Follow up on PR feedback comment: https://github.com/microsoft/axe-windows/pull/784#issuecomment-1290867685
Test run with these changes: https://dev.azure.com/mseng/1ES/_build/results?buildId=18610715&view=results
Follow up on PR feedback
This PR also moves away from using relative paths, as we seem to be running into this issue: https://github.com/microsoft/azure-pipelines-tasks/issues/10264

feat(localization): Include resource.dll files in binskim

---

src/Rules/Resources/HowToFix.Designer.cs
src/Rules/Resources/HowToFix.resx

Sister PR to https://github.com/microsoft/axe-windows/pull/790-- this PR covers the how to fix strings that are still outstanding after those changes. 
I don't have much context on most of these, so please feel free to correct or expand on any of these strings!

feat(localization): Convert remaining how to fix strings

---

src/SystemAbstractions/Concretions/MicrosoftFactory.cs
src/SystemAbstractions/Concretions/SystemFactory.cs

The analyzer flagged a couple of places where our keyword order is inconsistent with other usage
Align code to single standard

chore: Adjust keyword ordering for consistency

---

src/Actions/Actions/DataManager.cs
src/Actions/Actions/ListenAction.cs
src/Actions/Actions/SelectAction.cs
src/Actions/Contexts/ElementContext.cs
src/Actions/Contexts/ElementDataContext.cs
src/Actions/Contexts/ScopedActionContext.cs
src/Actions/Trackers/BaseTracker.cs
src/Actions/Trackers/FocusTracker.cs
src/Actions/Trackers/MouseTracker.cs
src/Actions/Trackers/TreeTracker.cs

Code standards are very inconsistent throughout the code base. This PR contains the changes needed to make the `Actions` project consistent after locally applying #810. The renames were all done through the IDE, and in most cases the IDE-suggested name was used. In cases where the IDE-supplied name seemed odd, I chose a name that seemed appropriate.

chore: Update private field names in Actions project

---

src/Core/Types/ControlType.cs
src/Core/Types/HeadingLevelType.cs
src/Core/Types/LandmarkType.cs
src/Core/Types/PatternType.cs
src/Core/Types/PlatformPropertyType.cs
src/Core/Types/PropertyType.cs

PR #814 missed some misnamed private fields. This fixes them. It also updates some poorly worded comments (technically the same comment in the 6 classes that are being touched)

chore: Housekeeping in src\Core\Types folder

---

src/loc/lcl/CHS/Axe.Windows.Core.lcl
src/loc/lcl/CHS/Axe.Windows.RuleSelection.lcl
src/loc/lcl/CHS/Axe.Windows.Rules.lcl
src/loc/lcl/DEU/Axe.Windows.Core.lcl
src/loc/lcl/DEU/Axe.Windows.RuleSelection.lcl
src/loc/lcl/DEU/Axe.Windows.Rules.lcl
src/loc/lcl/FRA/Axe.Windows.Core.lcl
src/loc/lcl/FRA/Axe.Windows.RuleSelection.lcl
src/loc/lcl/FRA/Axe.Windows.Rules.lcl
src/loc/lcl/KOR/Axe.Windows.Core.lcl
src/loc/lcl/KOR/Axe.Windows.RuleSelection.lcl
src/loc/lcl/KOR/Axe.Windows.Rules.lcl
src/loc/lcl/RUS/Axe.Windows.Core.lcl
src/loc/lcl/RUS/Axe.Windows.RuleSelection.lcl
src/loc/lcl/RUS/Axe.Windows.Rules.lcl

Adding translations to LCL files

feat(localization): Add translations to LCL files

---

src/loc/lcl/CHT/Axe.Windows.Core.lcl
src/loc/lcl/CHT/Axe.Windows.RuleSelection.lcl
src/loc/lcl/CHT/Axe.Windows.Rules.lcl
src/loc/lcl/CSY/Axe.Windows.Core.lcl
src/loc/lcl/CSY/Axe.Windows.RuleSelection.lcl
src/loc/lcl/CSY/Axe.Windows.Rules.lcl
src/loc/lcl/ESN/Axe.Windows.Core.lcl
src/loc/lcl/ESN/Axe.Windows.RuleSelection.lcl
src/loc/lcl/ESN/Axe.Windows.Rules.lcl
src/loc/lcl/ITA/Axe.Windows.Core.lcl
src/loc/lcl/ITA/Axe.Windows.RuleSelection.lcl
src/loc/lcl/ITA/Axe.Windows.Rules.lcl
src/loc/lcl/JPN/Axe.Windows.Core.lcl
src/loc/lcl/JPN/Axe.Windows.RuleSelection.lcl
src/loc/lcl/JPN/Axe.Windows.Rules.lcl
src/loc/lcl/PLK/Axe.Windows.Core.lcl
src/loc/lcl/PLK/Axe.Windows.RuleSelection.lcl
src/loc/lcl/PLK/Axe.Windows.Rules.lcl
src/loc/lcl/PTB/Axe.Windows.Core.lcl
src/loc/lcl/PTB/Axe.Windows.RuleSelection.lcl
src/loc/lcl/PTB/Axe.Windows.Rules.lcl
src/loc/lcl/TRK/Axe.Windows.Core.lcl
src/loc/lcl/TRK/Axe.Windows.RuleSelection.lcl
src/loc/lcl/TRK/Axe.Windows.Rules.lcl

LEGO: Pull request from users/loc/juno/hb_bcf03584-5f49-46b3-b9d9-20b47d2b6ca7_20221115000953479 to LocalizationOnboarding with localized lcls

LEGO: Pull request from users/loc/juno/hb_bcf03584-5f49-46b3-b9d9-20b47d2b6ca7_20221115000953479 to LocalizationOnboarding

---

src/CLI/README.MD
src/props/version.props

Localization is a new feature, so we're bumping the release version to 2.1.0. The existing release is 2.0.0, and the previously anticipated release was 2.0.1
Prepare to release version 2.1.0

chore: Bump version from 2.0.1 to 2.1.0

---

src/CLI/README.MD
src/props/version.props

Bump the release version from 2.1.0 to 2.1.1. This will be merged after 2.1.0 releases
Standard version maintenance

chore: Bump version to 2.1.1

---

docs/RulesDescription.md

Update RulesDescription.md to reflect the current set of rules
We do this after each release to keep RulesDescription.md in sync with the most recent release.

chore: Update RulesDescription.md

---

README.md

In #762, the `AutomationReference` document was updated to match the v2 API. However, the shorter code sample in the main readme does not reflect current usage.

Chore: update the project readme for v2-style usage

---

src/loc/lcl/ESN/Axe.Windows.Rules.lcl

LEGO: Pull request from users/loc/juno/hb_bcf03584-5f49-46b3-b9d9-20b47d2b6ca7_20230308203340974 to main with localized lcls

chore: Update localization files

---

docs/RulesDescription.md

We had some rule changes that didn't update RulesDescription.md. This PR just runs the RulesMD project to refresh the file in the repo.
Docs should be in sync with rules.

chore: Update Rules with latest changes

---

src/props/version.props

Bump the patch version
Standard procedure after releasing

chore: Bump version number from 2.1.1 to 2.1.2

---

src/props/version.props

Bump the package version to 2.1.3
Routine post-release step

chore: bump version to 2.1.3

---

docs/BuildingTheCode.md
docs/DebuggingTips.md
docs/solution.md

Fill a few documentation gaps that were identified.
Good docs are cheaper than bad docs

chore: Fill some documentation gaps

---

src/Rules/Resources/Descriptions.resx
src/Rules/Resources/HowToFix.resx

This PR makes "UI Automation" translatable.
Localization team request (email)

fix: Unlock "UI Automation" as requested

---

docs/RulesDescription.md

Rule strings changed but the descriptions were not. Fix this.
Be in sync with what we release

Refresh rule descriptions with latest strings

---

src/props/version.props

Janitorial: bump version after release.

Chore: Bump version to 2.1.4

---

src/CLI/README.MD
src/props/version.props

This PR increments the minor version, bringing us to v2.2.0.
Upcoming release

chore: Bump version to 2.2.0

---

src/CLI/README.MD
src/props/version.props

Janitorial: bump patch version after release.

chore: Bump version to 2.2.1

---

tools/scripts/pipeline/build/clearly-defined/ValidateScript.bat
tools/scripts/pipeline/build/clearly-defined/check-clearly-defined.ps1

This keeps the ClearlyDefined script up to date with changes made in the web repository, where the script needed to exclude dependabot PRs updating the playwright docker image.
keep the ClearlyDefined script in sync with web, per https://github.com/microsoft/accessibility-insights-web/pull/6917 

chore: Update ClearlyDefined script to exclude dependabot updates to docker images

---

src/CLI/README.MD
src/props/version.props

#967 added new functionality, so our next release ought to reflect this. This moves from 2.2.1 to 2.3.0
Follow semver guidelines

chore: Bump version to 2.3.0

---

src/CLI/README.MD
src/props/version.props

Bump version number post-release
Routine maintenance

chore: Bump version (post-release)

---

tools/scripts/pipeline/build/clearly-defined/ValidateScript.bat
tools/scripts/pipeline/build/clearly-defined/check-clearly-defined.ps1

Bring ClearlyDefined tooling in sync with https://github.com/microsoft/accessibility-insights-web/pull/7046 and https://github.com/microsoft/accessibility-insights-web/pull/7055. 
Keep duplicated files in sync since we don't yet have a single place to store these

chore: Sync latest ClearlyDefined changes

---

src/ActionsTests/ActionsTests.csproj
src/AutomationTests/AutomationTests.csproj
src/CLITests/CLITests.csproj
src/CoreTests/CoreTests.csproj
src/DesktopTests/DesktopTests.csproj
src/MsiFileTests/MsiFileTests.csproj
src/OldFileVersionCompatibilityTests/OldFileVersionCompatibilityTests.csproj
src/RuleSelectionTests/RuleSelectionTests.csproj
src/RulesTest/RulesTests.csproj
src/SystemAbstractionsTests/SystemAbstractionsTests.csproj
src/TelemetryTests/TelemetryTests.csproj
src/Win32Tests/Win32Tests.csproj

Bumps [Microsoft.NET.Test.Sdk](https://github.com/microsoft/vstest)
Updates Microsoft.NET.Test.Sdk from 17.8.0 to 17.9.0

chore(deps): Bump Microsoft.NET.Test.Sdk in /src

---

src/props/version.props

Bump version to 2.3.2 (releasing 2.3.1 today)
Routine maintenance associated with release

chore: Bump version to 2.3.2

---

src/props/version.props

Janitorial: bump version after release

chore: Bump version after 2.4.1 release

---

src/Actions/Actions.csproj
src/OldFileVersionCompatibilityTests/OldFileVersionCompatibilityTests.csproj

Bumps [System.IO.Packaging](https://github.com/dotnet/runtime) from 8.0.0 to 8.0.1.
This will resolve CG issue https://dev.azure.com/mseng/1ES/_componentGovernance/320/alert/239153?typeId=268109
- [na] Addresses an existing issue: #0000

chore(deps): Bump System.IO.Packaging from 8.0.0 to 8.0.1 in /src

---

src/CI/Axe.Windows.nuspec

Updated Axe.Windows.nuspec to System.IO.Packaging 8.0.1
https://dev.azure.com/mseng/1ES/_componentGovernance/320/alert/239153?typeId=268109

chore: Updated System.IO.Packaging 8.0.1 in Axe.Windows.nuspec

---

src/ActionsTests/Actions/CaptureActionTests.cs
src/AutomationTests/AutomationIntegrationTests.cs

This PR replaces all references to [DataTestMethod] with [TestMethod]
Adresses #1074. Supersedes #1075 due to CI issues.

chore: Switch all [DataTestMethod] to [TestMethod]

---

build/signedbuild.yml

Updated Micro build template to use code signing with Prod service connection.
This is to address IcM Incident: 674210625 

chore: updated signed job to use Prod service connection
