microsoft/axe-windows

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/general-question.md
- .github/pull_request_template.md
- Move code owner and code request template.
- Check lists was removed from the template till we create a new one for the repo.
- in general-question folder, the recommendatio to ask on stackoverflow was removed till we have a new account for the repo.
> Move ".github" folder

- src/props/version.props
In the long term, the "-prerelease" suffix should not be stored in the version.props file. But in order to create our first package suitable to be pushed to nuget.org, I have included it here to simplify building and signing the package.
> Add prerelease suffix for first NuGet push

- src/Axe.Windows.Core/Core.csproj
- src/Axe.Windows.Core/Misc/PackageInfo.cs
- src/Axe.Windows.Core/Misc/Utility.cs
- src/Axe.Windows.CoreTests/CoreTests.csproj
- src/Axe.Windows.CoreTests/Misc/PackageInfoTests.cs
- src/Axe.Windows.Desktop/Settings/SnapshotMetaInfo.cs
- used the informational version because it represents the semver version, whereas the file version cannot.
- Moved the code that exposes the version out of Utility and into PackageInfo to make it more obvious how to get the version
> Add code to expose Axe.Windows package version

- src/CI/CI.csproj
- src/CI/Microsoft.Axe.Windows.nuspec
This PR updates the .nuspec file so that the NuGet package id includes 'Microsoft'. This allows us to be consistent with guidelines for publishing to NuGet.org via Microsoft.
> Rename the nuget package to Microsoft.Axe.Windows

- build/signedbuild.yml
Remove "Axe.Windows" from targets path in the signed build yml sine we removed it from folder names, now signed build should not fail in BinSim or FXCop tasks.
> Fix targets path in the signed build yml file

- src/CI/CI.csproj
The name of the NuGet package should be Microsoft.Axe.Windows, but the csproj signing looked for Axe.Windows.
> Fixing missing name for NuGet file

- build/common.targets
- build/delaysign.targets
- build/settings.targets
The new Roslyn changes are generating errors because flow-analysis isn't enabled. It's enabled by default in the official build environment, but not when building locally. This explicitly enables it locally, as well. It will be doubly-enabled in the official build, but that shouldn't be a problem.
> Enable flow analysis in all projects

- src/DesktopTests/DesktopTests.csproj
- src/DesktopTests/Settings/SnapshotMetaInfoTests.cs
Remove Fakes dependency from DesktopTests project. There was only 1 Shim being used, and by initializing a Stream with the test input, I could completely remove the need for the Shim. DesktopTests is now independent of Fakes
> Remove Fakes dependency from DesktopTests project

- build/prbuild.yml
Enable code coverage to see how much we cover and act based on that.
> Enable code coverage in build result

- src/Automation/Automation.csproj
- src/Automation/AxeWindowsAutomationException.cs
- src/Automation/Data/Config.cs
- src/Automation/Data/ElementInfo.cs
- src/Automation/Data/ScanResult.cs
- src/Automation/Data/ScanResults.cs
- src/Automation/Enums/OutputFileFormat.cs
- src/Automation/Interfaces/IScanner.cs
- src/Automation/ReadMe.md
- src/Automation/Scanner.cs
- src/Automation/ScannerFactory.cs
- src/AutomationTests/SnapshotCommandUnitTests.cs
- src/AutomationTests/StartCommandUnitTests.cs
The model has not been implemented yet, except for the Config class and the ScannerFactory class.
Changes since the last design review:
- Change ScanResult.OutputFiles from an IEnumerable to a Tuple: (string A11yTest, string Sarif) so that output files are grouped together, but still distinguishable by type
- Removed Scanner.Builder and created ScannerFactory since creating new objects which implement a specific interface is the job of a factory. It also hides the implementation of Scanner entirely.
- For the returned data classes, changed private access to internal access because we don't need to manage construction of these classes with a builder.
> Add new interface model for Axe.Windows.Automation

- docs/Automation.md
- src/CI/Axe.Windows.nuspec
- src/CI/CI.csproj
This decision was based on Microsoft's collaboration with the open source community. 
> Remove "Microsoft." from Axe.Windows package name

- src/Automation/ExecutionWrapper.cs
- src/Automation/SnapshotCommand.cs
- src/Automation/StartCommand.cs
- src/Automation/StopCommand.cs
- src/AutomationTests/ExecutionWrapperUnitTests.cs
- src/AutomationTests/SnapshotCommandUnitTests.cs
- src/AutomationTests/StartCommandUnitTests.cs
- src/AutomationTests/StopCommandUnitTests.cs
We originally returned error messages in the results objects because it was thought that PowerShell couldn't handle exceptions. But it turns out PowerShell is fine with exceptions; so we can simply throw them and not return invalid data.
> Replace error return values with AxeWindowsAutomationException

- src/Automation/Automation.csproj
- src/Automation/Interfaces/IScanResultsAssembler.cs
- src/Automation/ScanResultsAssembler.cs
- src/AutomationTests/ScanResultsAssemblerTests.cs
To improve future unit testing scenarios, this PR makes ScanResultsAssembler non-static and introduces the IScanResultsAssembler interface. ScanResultsAssembler is still not in use, so there is no impact on other classes.
> Make ScanResultsAssembler non-static and add interface

- src/Automation/ExecutionWrapper.cs
- src/AutomationTests/ExecutionWrapperUnitTests.cs
The code to rethrow a caught AxeWindowsAutomationException was using the wrong syntax, causing the Exception to reach the caller without its stack trace. Reference: https://blogs.msdn.microsoft.com/perfworld/2009/06/15/how-can-i-throw-an-exception-without-losing-the-original-stack-trace-information-in-net/
Fixed the code, added a unit test to demonstrate the bad behavior and to pin the correct behavior.
> Correct the code to rethrow an AxeWindowsAutomationException

- src/Automation/Automation.csproj
- src/Automation/Factory.cs
- src/Automation/Interfaces/IFactory.cs
- src/Automation/Interfaces/IScanToolsBuilder.cs
- src/Automation/ScanToolsBuilder.cs
- src/Automation/ScannerFactory.cs
- src/AutomationTests/AutomationTests.csproj
- src/AutomationTests/ScanToolsBuilderUnitTests.cs
Changes
- Create IScanToolsBuilder interface and implementation
- Make ScanToolsBuilder take IFactory as a constructor parameter
- Create IFactory interface, used with ScanToolsBuilder
- Update Factory to implement IFactory
- Create the outline for ScanToolsBuilder unit tests to be implemented when Moq is introduced to the project
> Add ScanToolsBuilder for creating IScanTools implementation

- src/Automation/ScanResultsAssembler.cs
- src/AutomationTests/ScanResultsAssemblerTests.cs
- ScanResultsAssembler currently happens to fail if a RuleResult's ID is not in the current set of rules. This PR updates it to explicitly reject this scenario with a specific exception. Unit tests updated accordingly.
- ScanResultsAssembler unit tests also updated to test the ? null check previously added to properties and patterns.
> Update ScanResultsAssembler to explicitly reject bad RuleIds

- src/Automation/ScanToolsBuilder.cs
- src/AutomationTests/ScanToolsBuilderUnitTests.cs
These tests now ensure that all the properties of the resultant ScanTools object were _probably_ generated by the IFactory. 
> Rework ScanToolsBuilder unit tests using Moq

- src/AutomationTests/AutomationIntegrationTests.cs
- src/UnitTestSharedLibrary/TestCategory.cs
- src/UnitTestSharedLibrary/UnitTestSharedLibrary.csproj
Running our integration test is slower than unit tests and can be jarring. This PR adds a TestCategory static class and uses it to set the TestCategory attribute of our integration test. 
Now, devs can enter `-Trait:"Integration"` to their Test Explorer search box and continue to use "Run All" without running our integration test.
> Add integration TestCategory 

- src/Automation/Automation.csproj
- src/Automation/AxeWindowsActions.cs
- src/Automation/Factory.cs
- src/Automation/Interfaces/IAxeWindowsActions.cs
- src/Automation/Interfaces/IFactory.cs
- src/Automation/Interfaces/IScanTools.cs
- src/Automation/ScanTools.cs
- src/Automation/ScanToolsBuilder.cs
- src/Automation/SnapshotCommand.cs
- src/AutomationTests/ScanToolsBuilderUnitTests.cs
- src/AutomationTests/SnapshotCommandUnitTests.cs
The new name more accurately reflects the purpose of the interface.
Note: Only rename actions were done in this PR.
> Rename InternalScanner to AxeWindowsActions

- src/Automation/OutputFileHelper.cs
- src/AutomationTests/OutputFileHelperUnitTests.cs
There was some concern that using seconds for test file output names would result duplicate name generation. This PR adds ticks to the filename to alleviate that risk.
>  Add ticks to OutputFileHelper filename for uniqueness

- src/Core/Enums/RuleId.cs
- src/Rules/Library/HyperlinkNameShouldBeUnique.cs
- src/Rules/Library/SiblingUniqueAndFocusable.cs
- src/Rules/Library/SiblingUniqueAndNotFocusable.cs
- src/Rules/Resources/Descriptions.Designer.cs
- src/Rules/Resources/Descriptions.resx
- src/Rules/Resources/HowToFix.Designer.cs
- src/Rules/Resources/HowToFix.resx
- src/Rules/Rules.csproj
- src/RulesTest/Library/HyperlinkNameShouldBeUniqueTest.cs
- src/RulesTest/RulesTests.csproj
We had a false positive described in issue #42 . This PR removes the hyperlink from the unique name check for siblings. Instead a new rule is created for sibling hyperlinks and a warning is returned if the names are identical.
> Exclude hyperlinks from unique name rule for siblings

- build/signedbuild.yml
- src/AutomationTests/AutomationIntegrationTests.cs
Our signed build can't handle ui-inclusive tests. Also, our normal build needs more time to properly run the integration tests. This PR stops running the integration tests on signed builds and gives them more time in other scenarios.
> Don't run integration tests on signed build

- src/Rules/Library/BoundingRectangleContainedInParent.cs
- src/RulesTest/Library/BoundingRectangleContainedInParentTest.cs
This change is based on a discussion with the Accessibility Tooling Advisory Board.
BoundingRectangleContainedInParent was created based on a similar rule which is part of another automated accessibility scanning tool. And while the rule seems to make sense logically, there is no known documentation to support it. In addition, there are numerous violations in existence in the wild, and there is no evidence it presents an accessibility barrier to users. Therefore, we are demoting this rule to a warning.
> Change EvaluationCode of BoundingRectangleContainedInParent to Warning

- src/props/version.props
We need to do this in order to make another build which has an updated nupkg file.
> Revert AxeWindows version to 2.0

- src/CI/Axe.Windows.nuspec
- The author should match the name of our NuGet org
- And the copyright is what we agreed to with legal
> Update nuspec with correct authors and suggested copyright

- build/signedbuild.yml
We are no longer signing the package with the Microsoft certificate since this is meant to be a community package.
> Remove NuGet package signing by the build

- src/Automation/OutputFileHelper.cs
- src/Rules/PropertyConditions/StringProperty.cs
Add a couple of CultureInfo.InvariantCulture (wanted by FxCop). Use lower-case string instead of mixed-case String within the files being touched. 
> More TSA fixes

- src/CI/Axe.Windows.nuspec
This means we will allow NuGet to manage getting dependency packages, instead of including dependency package files in our package.
Also, removed inclusion of system files from our package. These files should already exist on target machines as part of the .Net runtime.
> Add package dependencies to NuSpec file

- src/Automation/Automation.csproj
- src/Automation/Data/OutputFile.cs
- src/Automation/Data/ScanResults.cs
- src/Automation/SnapshotCommand.cs
I came across an environment that provides only a partial implementation of .NET, and that implementation doesn't include the named Tuple struct. To enable the scan, I changed ScanResults.OutputFile from a Tuple to a struct? It's a struct (instead of a class) for compatibility with the named Tuple, which is a value type, not a reference type. We can certainly make it a class, but it's a potentially breaking change from the 0.2.0 interface, where ScanResults.OutputFile could never be null
> Don't use named Tuple for ScanResults.OutputFile

- build/signedbuild.yml
- src/props/version.props
Disable digital signing of axe-windows assemblies (consistent with our long-term plan). Bump the version number to reflect the following changes:
1. Referencing dependencies are no longer included in the package (#86)
2. The OutputFile is now a struct instead of a Tuple (#91)
3. The axe-windows assemblies are no longer digitally signed (included with this PR)
Note: This PR does not update any csproj files. That can happen at a later time without requiring a re-release.
> Disable signing, bump version to 0.3.0 prerelease

- build/prbuild.yml
- build/signedbuild.yml
- src/CI/CI.csproj
NuGet package creation is gated by a environment variable. For historical reasons that no longer apply, this variable is named MAICreateNuget. I've updated this variable to CreateAxeWindowsNugetPackage both to reflect the current repo and to make it clearer what this flag does.
> Rename MAICreateNuget to CreateAxeWindowsNugetPackage

- README.md
Fixes Automation and Telemetry page links with casing issue
> docs: fix broken links in README.md

- Contributing.md
- README.md
- docs/AccessingInternals.md
- docs/AutomationReference.md
- docs/BuildingTheCode.md
- docs/FAQ.md
- docs/GitBranchSetup.md
- docs/Overview.md
- docs/solution.md
- Move the extensive how-to section from automation.md to readme.md
- Rename automation.md to AutomationReference.md
- Extract solution information from overview.md
- add solution overview to solution.md where it can be referenced from multiple places
- Move sections on building the code to their own file where they can be referenced from multiple places
- Add tags to code blocks to get syntax highlighting
> Update docs to move automation info to the foreground and contribution info to the background

- Contributing.md
Extra whitespace made the `Contributing` heading format as a code snippet. Removed leading whitespace to fix this.
> docs: remove leading whitespace in Contributing header

- src/Automation/Data/Config.cs
The expectation for a builder pattern seems to be that a new object should be created each time Build() is called. This change fixes the issue where Config.Builder.Build() would have returned the same object if Build() had been called multiple times.
> Rework Config.Builder.Build to return new each time

- src/ActionsTests/ActionsTests.csproj
This one apparently got missed in the previous cleanup of Sarif references
> Remove remaining Sarif Refefence

- build/signedbuild.yml
Test theory that this will re-enable strongname signing
> Re-add SignAppForRelease in SignedRelease job

- build/settings.targets
- docs/NewProject.md
- src/Actions/Actions.csproj
- src/Actions/packages.config
- src/Automation/Automation.csproj
- src/Automation/packages.config
- src/CI/CI.csproj
- src/Core/Core.csproj
- src/Core/packages.config
- src/Desktop/Desktop.csproj
- src/Desktop/packages.config
- src/RuleSelection/RuleSelection.csproj
- src/RuleSelection/packages.config
- src/Rules/Rules.csproj
- src/Rules/packages.config
- src/RulesTest/app.config
- src/Telemetry/Telemetry.csproj
- src/Telemetry/packages.config
- src/Win32/Win32.csproj
- src/Win32/packages.config
This reverts commit 30f48e87ef2815a47c214e98bdd0468398e69d8c.
Microbuild signing  was needed to delay strong name sign the assemblies. Another PR will be submitted that removes authenticode signing only.
> Revert "Remove project signing (#98)"

- build/settings.targets
Had previously disabled authenticode signing by removing the SignAppForRelease variable from signed build yml file. But that change also inadvertently disabled strong name signing for the assemblies as well. We have since restored SignAppForRelease in the yml file. This change makes it so assemblies should be strong name signed, but not authenticode signed.
> Remove authenticode signing

- build/NetStandardAll.targets
- build/NetStandardRelease.targets
- build/NetStandardTest.targets
- src/Automation/Automation.csproj
- src/Automation/Factory.cs
- src/Automation/OutputFileHelper.cs
- src/AutomationTests/AutomationTests.csproj
- src/AutomationTests/OutputFileHelperUnitTests.cs
- src/AxeWindows.sln
- src/SystemAbstractions/Abstractions/ISystem.cs
- src/SystemAbstractions/Abstractions/ISystemDateTime.cs
- src/SystemAbstractions/Abstractions/ISystemEnvironment.cs
- src/SystemAbstractions/Abstractions/ISystemFactory.cs
- src/SystemAbstractions/Abstractions/ISystemIO.cs
- src/SystemAbstractions/Abstractions/ISystemIODirectory.cs
- src/SystemAbstractions/Concretions/System.cs
- src/SystemAbstractions/Concretions/SystemDateTime.cs
- src/SystemAbstractions/Concretions/SystemEnvironment.cs
- src/SystemAbstractions/Concretions/SystemFactory.cs
- src/SystemAbstractions/Concretions/SystemIO.cs
- src/SystemAbstractions/Concretions/SystemIODirectory.cs
- src/SystemAbstractions/SystemAbstractions.csproj
- src/SystemAbstractionsTests/SystemAbstractionsTests.csproj
- src/SystemAbstractionsTests/SystemUnitTests.cs
- Enable other projects to use the system abstractions formerly limited to Axe.Windows.Automation
- Allow System calls to be mocked so Fakes can be replaced
- Use .Net Standard to ensure broadest future compatibility
> Create SystemAbstractions project

- docs/NewProject.md
- docs/solution.md
Relevant after the creation of the SystemAbstractions .Net Standard project and the SystemAbstractionsTests .Net Core project
> Add .Net Standard-related content to documentation

- build/signedbuild.yml
This fixes the broken signed build.
FxCop analyzers do not work on .NET Standard and .NET Core assemblies. The recommended fix is to use the RoslynAnalyzers build task instead. And that makes sense given that the analyzers we use while compiling are the Roslyn analyzers (even though the NuGet package name is Microsoft.CodeAnalysis.FxCopAnalyzers because the analyzers therein are based on FxCop).
After the PR has been created, certain checks will be kicked off. All of these checks must pass before a merge.
> Change from using FxCop analyzers to RoslynAnalyzers in the pipeline

- src/Core/Bases/A11yElement.cs
Force ProcessName to string.Empty for all elements read from disk. The current behavior is leading to a flaky unit test, depending on the ID's of other processes running on the build agent.
> Force ProcessName to string.Empty for all elements read from disk

- src/OldFileVersionCompatibilityTests/LoadOldFileVersions.cs
These conditions are true, but since they don't really pin all results, and since they're not directly related to the file format verification, Rob and I have agreed to pull them out.
> Remove a couple of conditions that don't belong in this test class

- src/AutomationTests/AutomationTests.csproj
This should have been removed when the Automation project was updated. There are no Fakes in AutomationTests.
> Remove reference to Fakes which is no longer needed

- src/CI/Axe.Windows.nuspec
These dependencies are needed for compilation by apps which consume our NuGet package.
> Add NuGet dependencies from new .NET standard projects

- src/props/version.props
Note: this may not be the version number of the next release. But it ensures that any further builds have a higher number than the current release.
> Update Axe.Windows version to 0.3.3

- src/Core/Properties/AssemblyInfo.cs
Signed build broke because it can't find the default language specification
> Move default language specification outside of ENABLE_SIGNING block

- build/signedbuild.yml
The values of both sets of analyzers are the latest versions provided by https://www.1eswiki.com/wiki/Roslyn_Analyzers_Build_Task.
> Update RoslynAnalyzers build task to use fixed analyzers version

- .github/CODEOWNERS
We've started updating all the accessibility insights repos to use a shared CODEOWNERS team, rather than maintaining separate ones per project. This brings axe-windows up to date with this new policy.
> Generalize CODEOWNERS to use whole-team instead of windows-specific team

- src/Core/Enums/RuleId.cs
- src/Rules/Library/HelpTextExcludesPrivateUnicodeCharacters.cs
- src/Rules/Library/LocalizedControlTypeExcludesPrivateUnicodeCharacters.cs
- src/Rules/Library/NameExcludesPrivateUnicodeCharacters.cs
- src/Rules/PropertyConditions/StringProperties.cs
- src/Rules/PropertyConditions/StringProperty.cs
- src/Rules/Resources/ConditionDescriptions.Designer.cs
- src/Rules/Resources/ConditionDescriptions.resx
- src/Rules/Resources/Descriptions.Designer.cs
- src/Rules/Resources/Descriptions.resx
- src/Rules/Resources/ErrorMessages.Designer.cs
- src/Rules/Resources/ErrorMessages.resx
- src/Rules/Resources/HowToFix.Designer.cs
- src/Rules/Resources/HowToFix.resx
- src/Rules/Rules.csproj
- src/RulesTest/Library/HelpTextExcludesPrivateUnicodeCharactersUnitTests.cs
- src/RulesTest/Library/LocalizedControlTypeExcludesPrivateUnicodeCharactersUnitTests.cs
- src/RulesTest/Library/NameExcludesPrivateUnicodeCharactersUnitTests.cs
- src/RulesTest/PropertyConditions/StringPropertiesTest.cs
- src/RulesTest/RulesTests.csproj
Created three rules for Name, HelpText, and LocalizedControlType because rules are not meant to test the same issue for multiple properties.
Issue #129
> feature: Add a rule to detect characters in the private unicode range

- build/signedbuild.yml
> Update internal Microsoft Roslyn analyzers to version 2.6.3-beta1

- src/Rules/Library/BoundingRectangleNotNull.cs
- src/Rules/PropertyConditions/ElementGroups.cs
- src/RulesTest/Library/BoundingRectangleNotNullTest.cs
- [BUG] BoundingRectangleNotNull rule should exclude non-focusable buttons that are children of sliders · Issue #139
- [BUG] False positive for BoundingRectangleNotNull for group elements in Edge · Issue #142
> Fix two bugs in BoundingRectangleNotNull rule

- src/Core/Enums/Framework.cs
- src/Rules/Library/ControlShouldSupportTextPattern.cs
- src/RulesTest/Library/ControlShouldSupportTextPatternUnitTests.cs
- src/RulesTest/RulesTests.csproj
Please see the bug description for details on the fix.
> Fix [BUG] False positives created by change to ControlShouldSupportTextPattern ruleIssue #140

- build/signedbuild.yml
Create a separate publishing step to publish an artifact with just the NuGet package. This will simplify the effort required to publish the NuGet package (especially if we later automate this part of the process)
> Add a separate publishing artifact dedicated to the NuGet package

- src/ActionsTests/ActionsTests.csproj
- src/ActionsTests/app.config
- src/ActionsTests/packages.config
- src/AutomationTests/AutomationTests.csproj
- src/AutomationTests/app.config
- src/AutomationTests/packages.config
- src/CoreTests/CoreTests.csproj
- src/CoreTests/app.config
- src/CoreTests/packages.config
- src/DesktopTests/DesktopTests.csproj
- src/DesktopTests/packages.config
- src/OldFileVersionCompatibilityTests/OldFileVersionCompatibilityTests.csproj
- src/OldFileVersionCompatibilityTests/packages.config
- src/RuleSelectionTests/RuleSelectionTests.csproj
- src/RuleSelectionTests/packages.config
- src/RulesTest/RulesTests.csproj
- src/RulesTest/packages.config
- src/SystemAbstractionsTests/SystemAbstractionsTests.csproj
- src/TelemetryTests/TelemetryTests.csproj
- src/TelemetryTests/app.config
- src/TelemetryTests/packages.config
- src/Win32Tests/Win32Tests.csproj
- src/Win32Tests/app.config
- src/Win32Tests/packages.config
Update test-only NuGet packages as follows:
- MSTest.TestAdapter (1.4.0 => 2.0.0)
- MSTest.TestFramework (1.4.0 => 2.0.0)
- Moq (4.12.0 => 4.13.0)
- System.Threading.Tasks.Extensions (5.5.2 => 4.5.3)
> Update NuGet packages that are used only for test projects (has no impact on shipping binaries)

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/general-question.md
Use comments for help text in issue templates so they don't show up when the issue creator doesn't delete them. The commented help text will still show up during issue creation.
Also changed from emphasis (**) to headings (##) to match templates in other Accessibility Insights repos.
> chore: update issue templates to use headings and comments

- src/Actions/Actions.csproj
- src/Actions/packages.config
- src/Automation/Automation.csproj
- src/Automation/packages.config
- src/Core/Core.csproj
- src/Core/packages.config
- src/Desktop/Desktop.csproj
- src/Desktop/packages.config
- src/RuleSelection/RuleSelection.csproj
- src/RuleSelection/packages.config
- src/Rules/Rules.csproj
- src/Rules/packages.config
- src/SystemAbstractions/SystemAbstractions.csproj
- src/Telemetry/Telemetry.csproj
- src/Telemetry/packages.config
- src/UnitTestSharedLibrary/UnitTestSharedLibrary.csproj
- src/UnitTestSharedLibrary/packages.config
- src/Win32/Win32.csproj
Use VS to update to Roslyn 2.9.5 analyzers. No code changes were needed.
> Update to Roslyn 2.9.5 final release

- build/signedbuild.yml
Now that we're receiving early warning about the Roslyn analyzers, we should be able to let the system pick the latest version automatically instead of trying to manage it manually. If/when we have a version that causes trouble, we can always re-pin to a "known good" version. By keeping the 2 settings, we also have an obvious record of what changed when.
> Let Roslyn analyzers snap to latest version

- src/ActionsTests/ActionsTests.csproj
- src/ActionsTests/app.config
- src/ActionsTests/packages.config
- src/AutomationTests/AutomationTests.csproj
- src/AutomationTests/app.config
- src/AutomationTests/packages.config
- src/CoreTests/CoreTests.csproj
- src/CoreTests/app.config
- src/CoreTests/packages.config
- src/RulesTest/RulesTests.csproj
- src/RulesTest/app.config
- src/RulesTest/packages.config
- src/TelemetryTests/TelemetryTests.csproj
- src/TelemetryTests/app.config
- src/TelemetryTests/packages.config
- src/Win32Tests/Win32Tests.csproj
- src/Win32Tests/app.config
- src/Win32Tests/packages.config
> Update System.Runtime.CompilerServices.Unsafe to version 4.6.0

- src/Actions/Actions.csproj
- src/Actions/packages.config
System.Compositions.* is referenced in `Actions.csproj`, but is never referenced in the code. Removing it as unnecessary
> Remove System.Compositions from Actions (it's not needed)

- src/Actions/Actions.csproj
- src/Actions/packages.config
Remove System.Reflection.TypeExtensions from Actions (it's not needed)
> Remove System.Reflection.TypeExtensions from Actions (it's not needed)

- src/Actions/Actions/CaptureAction.cs
- src/Actions/Misc/ExtensionMethods.cs
- src/ActionsTests/Actions/CaptureActionUnitTests.cs
- src/ActionsTests/ActionsTests.csproj
- src/Desktop/UIAutomation/TreeWalkers/TreeWalkerForLive.cs
- src/Desktop/UIAutomation/TreeWalkers/TreeWalkerForTest.cs
Our use of Fakes was the only blocker I found to migrating to the newer form of .csproj, so I decided to start removing the few remaining places where axe-windows uses them.
This PR rewrites 1 of the 3 unit test files that currently use Fakes to instead, not. I felt that the original tests were doing too much of testing implementation details, anyway; the ones that used fakes verified that the public `CaptureActions` methods called various internal `CaptureActions` methods, but the caller doesn't care about that, they care about the observable effects. So I rewrote the tests essentially from scratch to pin the caller-visible behavior of the public methods, and avoid testing the interactions between the different internal methods.
To achieve this, I added 3 `internal` test hooks to the …
> Rewrite CaptureActionUnitTests to avoid requiring Fakes

- src/Actions/packages.config
Remove System.Linq and System.Linq.Expressions from Actions project (they aren't used in the code)
> Remove System.Linq and System.Linq.Expressions from Actions project

- src/CI/Axe.Windows.nuspec
- src/Win32/Win32.csproj
Update to System.Drawing.Common 4.6.0, update dependency. Replaces #183 
> Update to System.Drawing.Common 4.6.0, update dependency

- src/Actions/Actions.csproj
- src/Actions/packages.config
- src/Automation/Automation.csproj
- src/Automation/packages.config
- src/Core/Core.csproj
- src/Core/packages.config
- src/Desktop/Desktop.csproj
- src/Desktop/packages.config
- src/RuleSelection/RuleSelection.csproj
- src/RuleSelection/packages.config
- src/Rules/Rules.csproj
- src/Rules/packages.config
- src/SystemAbstractions/SystemAbstractions.csproj
- src/Telemetry/Telemetry.csproj
- src/Telemetry/packages.config
- src/Win32/Win32.csproj
VS-driven change to upgrade Text.Analyzers from 2.6.2 to 2.6.4. Also add Text.Analyzers to production projects where it had been overlooked.
> Update Text.Analyzers to version 2.6.4, add it where it was missing

- src/Actions/Actions.csproj
- src/Actions/packages.config
- src/ActionsTests/ActionsTests.csproj
- src/ActionsTests/packages.config
- src/Automation/packages.config
- src/CI/Axe.Windows.nuspec
- src/Core/Core.csproj
- src/Core/packages.config
- src/CoreTests/CoreTests.csproj
- src/CoreTests/packages.config
- src/Fakes.Prebuild/Fakes.Prebuild.csproj
- src/Fakes.Prebuild/packages.config
- src/UnitTestSharedLibrary/UnitTestSharedLibrary.csproj
- src/UnitTestSharedLibrary/packages.config
Remove multiple assembly references that are not needed:
- System.Collections.Immutable (still needed only because old versions of Axe.Windows say it's used, when it really isn't)
- System.Console
- System.Resources.ResourceManager
- System.Runtime
- System.CodeDom
- Text.Analyzers (removed from UnitTestSharedLibrary so it's only in production projects)
> Remove unused assembly references

- src/CurrentFileVersionCompatibilityTests/App.config
- src/CurrentFileVersionCompatibilityTests/CurrentFileVersionCompatibilityTests.csproj
- src/CurrentFileVersionCompatibilityTests/packages.config
Update System.Collections.Immutable to 1.6.0, add the latest versions of its dependencies. We recently (see #195) removed the references to System.Collections.Immutable, but since the file compatibility tests consume an older version of Axe.Windows, and since that older version still references Systems.Colletions.Immutable, the test gets a reference automatically. After consulting with @RobGallo, we felt that it was cleaner to use the updated versions for the test project. It has no impact on shipping bits.
> Update System.Collections.Immutable to 1.6.0, add the latest versions of its dependencies

- build/signedbuild.yml
This will enable us to add the rules documentation as a GitHub asset when new versions of the package are released.
Verified the artifact was created as part of a signed build.
> Add axe-windows-rules.md as a build artifact

- src/Actions/Actions.csproj
- src/Actions/packages.config
- src/Automation/Automation.csproj
- src/Automation/packages.config
- src/Core/Core.csproj
- src/Core/packages.config
- src/Desktop/Desktop.csproj
- src/Desktop/packages.config
- src/RuleSelection/RuleSelection.csproj
- src/RuleSelection/packages.config
- src/Rules/Rules.csproj
- src/Rules/packages.config
- src/SystemAbstractions/SystemAbstractions.csproj
- src/Telemetry/Telemetry.csproj
- src/Telemetry/packages.config
- src/UnitTestSharedLibrary/UnitTestSharedLibrary.csproj
- src/UnitTestSharedLibrary/packages.config
- src/Win32/Win32.csproj
Done using VS (not by hand).
- Bump Microsoft.CodeAnalysis.Analyzers from 2.9.6 to 2.9.7 in /src
- Bump Microsoft.NetFramework.Analyzers from 2.9.6 to 2.9.7 in /src
- Bump Microsoft.CodeAnalysis.FxCopAnalyzers from 2.9.6 to 2.9.7 in /src
- Bump Microsoft.CodeAnalysis.BinSkim from 1.5.1 to 1.6.0 in /src
- Bump Microsoft.NetCore.Analyzers from 2.9.6 to 2.9.7 in /src
- Bump Microsoft.CodeAnalysis.VersionCheckAnalyzer from 2.9.6 to 2.9.7 in /src
- Bump Microsoft.CodeQuality.Analyzers from 2.9.6 to 2.9.7 in /src
- Bump Roslyn.Diagnostics.Analyzers from 2.9.6 to 2.9.7 in /src
> Bump code analyzers from 2.9.6 to 2.9.7

- src/Desktop/Utility/ExtensionMethods.cs
- src/Win32/NativeMethods.cs
- src/Win32/Win32Enums.cs
- src/Win32/Win32Helper.cs
We identified some Axe.Windows methods that are used only in AIWin. We're adding these methods to AIWin and removing them from Axe.Windows. This is the complement of https://github.com/microsoft/accessibility-insights-windows/pull/630
> Remove Axe.Windows methods that aren't used by Axe.Windows

- src/Actions/Trackers/TreeTracker.cs
This addresses [an issue in ai-win](https://github.com/microsoft/accessibility-insights-windows/issues/619) related to crashes during hotkey tree navigation. A previous axe-windows PR added null checks to certain methods' parameters. One of these methods was consistently passed a null parameter in the circumstance outlined in the aforementioned ai-win issue. Rather than remove the null check, this PR prevents the method from being passed a null parameter in the first place, thus avoiding the exception.
Some minor formatting improvements were made to the file.
> Add null check to TreeTracker to avoid exception

- src/Actions/Actions/ScreenShotAction.cs
- src/Actions/Contexts/ElementContext.cs
- src/ActionsTests/Actions/ScreenShotActionUnitTests.cs
Using static property injection as a light-weight way to avoid using Fakes for getting the Datamanager and creating Bitmaps.
The original tests ensured the ElementDataContext.Screenshot property setter was called. But since that would involve a larger change including creating an interface which could be mocked to replace ElementDataContext, that idea was abandoned in favor of simply checking the resulting data.
I will remove all remaining vestiges of Fakes in another PR. I thought it would be good to keep this PR as minimal as practical.
> Remove Fakes used in ScreenShotAction unit tests

- src/Actions/Actions/ScreenShotAction.cs
- src/ActionsTests/Actions/ScreenShotActionUnitTests.cs
The call to CopyFromScreen fails in the microbuild pool on release builds.
This solution is decidedly unpretty, but it will help us move forward with eliminating Fakes and getting the builds to work for now.
> Update Screenshot unit test to "shim" Graphics

- src/Actions/Actions.csproj
- src/Actions/packages.config
- src/Automation/Automation.csproj
- src/Automation/packages.config
- src/Core/Core.csproj
- src/Core/packages.config
- src/Desktop/Desktop.csproj
- src/Desktop/packages.config
- src/RuleSelection/RuleSelection.csproj
- src/RuleSelection/packages.config
- src/Rules/Rules.csproj
- src/Rules/packages.config
- src/SystemAbstractions/SystemAbstractions.csproj
- src/Telemetry/Telemetry.csproj
- src/Telemetry/packages.config
- src/UnitTestSharedLibrary/UnitTestSharedLibrary.csproj
- src/UnitTestSharedLibrary/packages.config
- src/Win32/Win32.csproj
An updated version of the Roslyn analyzers was just released. Update to version 2.9.8, using Visual Studio tooling. This PR replaces #225, #226, #227, #228, #229, #230, and #231. It also removes the analyzers from the UnitTestSharedLibrary assembly, since we don't run analyzers on our unit tests.
> Bump analyzers from 2.9.7 to 2.9.8 (done via VS)

- src/Rules/Library/ProgressBarRangeValue.cs
- src/RulesTest/Library/ProgressBarRangeValue.cs
- src/RulesTest/RulesTests.csproj
#239 [BUG] [false positive] Update ProgressBarRangeValue allowed minimum and maximum values
The only criteria to test for now is that max is greater than min.
> Fix bug #239

- src/Rules/Library/NameIsReasonableLength.cs
- src/RulesTest/Library/NameIsReasonableLength.cs
- src/RulesTest/MonsterTest.cs
Issue #240 [BUG] [false positive] Rule NameIsReasonableLength should not apply to text elements
> Fix bug #240

- src/Rules/PropertyConditions/PlatformProperties.cs
- src/RulesTest/PropertyConditions/PlatformPropertiesTests.cs
Fix specific case where we had a mismatch between int and uint (and its unit test). This is the root cause of #244. This change is sufficient to handle all _current_ usages, but does nothing to prevent _future_ uses. When compared to #245 and #248, this is definitely the smallest and most targeted option.
> Fix specific case where we had a mismatch between int and uint (and its unit test)

- src/Actions/Trackers/TreeTracker.cs
- src/RulesTest/PropertyConditions/NameTest.cs
- src/RulesTest/PropertyConditions/RelationshipsTest.cs
Correct spelling of "Sibling", which only has 1 'b'. This will require some minor changes in AIWin when we integrate it there, but has no impact on automation consumers.
> Correct spelling of "Sibling", which only has 1 'b'. 

- src/AutomationTests/AutomationIntegrationTests.cs
- src/Core/Enums/RuleId.cs
- src/CurrentFileVersionCompatibilityTests/Program.cs
- src/Desktop/UIAutomation/DesktopElement.cs
- src/Desktop/UIAutomation/DesktopElementExtensionMethods.cs
- src/Rules/Extensions/ExtensionMethods.cs
- src/Rules/Library/ClickablePointOnScreen.cs
- src/Rules/Misc/Helpers.cs
- src/Rules/PropertyConditions/ClickablePoint.cs
- src/Rules/Resources/ConditionDescriptions.Designer.cs
- src/Rules/Resources/ConditionDescriptions.resx
- src/Rules/Resources/Descriptions.Designer.cs
- src/Rules/Resources/Descriptions.resx
- src/Rules/Resources/HowToFix.Designer.cs
- src/Rules/Resources/HowToFix.resx
- src/Rules/Rules.csproj
- src/RulesTest/Library/ClickablePointOnScreen.cs
- src/RulesTest/PropertyConditions/ClickablePointTests.cs
- src/RulesTest/RulesTests.csproj
- Add a new rule, ClicablePointOnScreen, to test that when the clickable point for an element is within the desktop's bounding rectangle, the element's IsOffScreen property is set to false.
- Add a new property condition ClickablePoint.OnScreen -- tests if an element's clickable point both exists and is within the desktop's bounding rectangle.
- Remove DesktopElement.ExcludedPropertyIds because it is not used by axe windows or ai-win.
- Add code to add the ClickablePoint property to element's which are not inside Edge. According to the existing comments, querying for the ClickablePoint property causes a crash in Edge.
- Add an if condition to CurrentFileVersionCompatibilityTests to ignore element's of type thumb when ensuring bounding rectangles are not empty. This is necessary because …
> Fix Issue #162 - [Feature Request] Add rules to ensure that an element's clickable point and IsOffscreen property agree. PR (1/2)

- src/AutomationTests/AutomationIntegrationTests.cs
The Integration tests are failing in the signed build pipeline. We don't yet understand _why_ the tests are failing the signed build, especially since they're working in PR builds (which use the same environment). This test does not fix the tests--it merely allows them to return inconclusive in the signed build. This is a stopgap to mitigate the broken pipeline, but will need a more permanent fix (possibly after the New Year).
> Allow integration tests to return inconclusive in build pipelines

- src/ActionsTests/ActionsTests.csproj
All Axe.Windows builds (like this [recent PR](https://dev.azure.com/accessibility-insights/axe-windows/_build/results?buildId=4989&view=results)) generate the following error:
```
##[warning]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5):
Warning MSB3243: No way to resolve conflict between
"System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and 
"System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Choosing 
"System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" arbitrarily.
```
The current version of System.Net.Http is 4.2.0, but for historical reasons, ActionsTests.csproj is pinned to version 4.0.0. This PR …
> Remove competing versions of System.Net.Http

- src/Core/Enums/RuleId.cs
- src/Rules/Library/ClickablePointOffScreen.cs
- src/Rules/PropertyConditions/ClickablePoint.cs
- src/Rules/Resources/ConditionDescriptions.Designer.cs
- src/Rules/Resources/ConditionDescriptions.resx
- src/Rules/Resources/Descriptions.Designer.cs
- src/Rules/Resources/Descriptions.resx
- src/Rules/Resources/HowToFix.Designer.cs
- src/Rules/Resources/HowToFix.resx
- src/Rules/Rules.csproj
- src/RulesTest/Library/ClickablePointOffScreen.cs
- src/RulesTest/PropertyConditions/ClickablePointTests.cs
- src/RulesTest/RulesTests.csproj
- Add a new rule, ClicablePointOffScreen, to test that when the clickable point for an element is outside the desktop's bounding rectangle, the element's IsOffScreen property is set to true.
- Add a new property condition ClickablePoint.OffScreen -- tests if an element's clickable point both exists and is outside the desktop's bounding rectangle.
The new rule generates a warning instead of an error because
- When Axe.Windows is run from a CLI, The desktop bounding rectangle is probably wrong because DPI awareness is probably not set for the CLI app (this will be addressed in an upcoming change)
- The resulting errors will likely create noise which only platform developers can fix (keeping this rule as a warning will allow it to become an assessment eventually, which will make it easier to …
> Fix Issue #162 - [Feature Request] Add rules to ensure that an element's clickable point and IsOffscreen property agree. PR (2/2)

- src/RulesMD/RulesMD.csproj
- src/RulesMD/packages.config
Manually making a change that dependabot is unable to make on older project types.
> Bump CommandLineParser from 2.6.0 to 2.7.82

- src/Rules/Library/ControlShouldSupportGridPattern.cs
- src/Rules/Library/ControlShouldSupportTablePattern.cs
- src/RulesTest/Library/ControlShouldSupportGridPattern.cs
- src/RulesTest/Library/ControlShouldSupportTablePattern.cs
- src/RulesTest/RulesTests.csproj
Adding PropertyIDs to enable snippet link to be shown in AIWin when a Table is found not to support the required UIA Grid and Table patterns. Update the related TablePattern unit tests, and create new GridPattern unit tests.
> Set PropertyID in rules relating to support for Grid and Table patterns

- src/SystemAbstractionsTests/SystemAbstractionsTests.csproj
This fixes a problem where SystemAbstractionsTests were not run locally with other unit tests.
> Update SystemAbstractionsTests to .Net Core 3.1

- src/CoreTests/CoreTests.csproj
- src/RulesTest/RulesTests.csproj
- src/TelemetryTests/TelemetryTests.csproj
I accidentally bumped a few unit test projects' references to prerelease versions. This change sets the versions of dependencies back to stable releases.
> Revert unit test package versions to stable releases

- src/CoreTests/CoreTests.csproj
- src/RulesTest/RulesTests.csproj
- src/SystemAbstractionsTests/SystemAbstractionsTests.csproj
- src/TelemetryTests/TelemetryTests.csproj
Build is breaking because the signed environment doesn't yet have .NET Core SDK version 3.1. Revert to .NET Core SDK version 3.0 for now (we'll return to 3.1 once the build environment has been updated)
Test build is running at https://dev.azure.com/mseng/1ES/_build/results?buildId=11254597&view=results
> Use .NET Core SDK 3.0 instead of .NET Core SDK 3.1

- src/Rules/Rules.csproj
- src/RulesTest/RulesTests.csproj
Interop types need to be embedded in the rules assembly (this was missed during the port)
> Embed Interop types in Rules and RulesTest assemblies

- src/Core/AssemblyInfo.cs
- src/Rules/AssemblyInfo.cs
- src/SystemAbstractions/AssemblyInfo.cs
- src/Telemetry/AssemblyInfo.cs
- src/Win32/AssemblyInfo.cs
In porting from .NET Framework to .NET Core, we stopped setting the following assembly metadata fields that we used to set:
AssemblyTitle (becomes the "FileDescription" property)
AssemblyProduct (becomes the "ProductName" property)
AssemblyCopyright (becomes the "LegalCopyright" property)
This PR sets the AssemblyTitle and AssemblyProduct values to their pre-port values, and sets the Copyright to 2020 so it's up-to-date. Future changes could potentially use a common value for AssemblyProduct (instead of using the assembly name) and/or centralize these values in a .props file, but the objective here is to achieve parity (modulo the updated copyright).
> Restore Assembly Metadata to projects built with .NET Core SDK

- src/Automation/Interfaces/IOutputFileHelper.cs
- src/Automation/Interfaces/IScanner.cs
- src/Automation/OutputFileHelper.cs
- src/Automation/Scanner.cs
- src/Automation/SnapshotCommand.cs
- src/AutomationTests/OutputFileHelperUnitTests.cs
- src/AutomationTests/SnapshotCommandUnitTests.cs
The automation layer's current scanning code auto-generates a name for the output file. This is fine for code calling the automation layer directly, since the returned data includes the name of the generated file. It's more problematic for the CLI that we're creating, since the CLI can only return an exit code. We could try to create ways to expose the name to the caller, but they all add complexity and increase the work for whoever is writing the script.
To simplify scripting via the CLI, we'll allow the CLI to accept an optional command line parameter that specifies a scan ID, which will then be used as the base file name of the output file. We'll use the current behavior (auto-generating the id/file name) if this command line parameter is omitted. The scanId is managed via the …
> Let IScanner.Scan caller specify scan ID (intended for CLI usage)

- build/prbuild.yml
- build/signedbuild.yml
Our old build loops run tests via vstest.exe, which only understands .NET Framework unit tests. As a result, we were losing tests as we migrated to .NET Core-based tests. This is the root cause of #152. We need to add a task to run the .Net Core CLI task in both the PR and signed build loop definitions. 
Validation in signed build: https://dev.azure.com/mseng/1ES/_build/results?buildId=11295667&view=results
> Enable DotNetCore tests in PR and signed builds

- src/RuleSelection/Resources/DefaultGuidelineUrls.Designer.cs
- src/RuleSelection/Resources/ErrorMessages.Designer.cs
- src/RuleSelection/RuleSelection.csproj
- src/RuleSelectionTests/RuleSelectionTests.csproj
There were 4 unit tests not being run in the RuleSelectionTests project, those in DefaultReferenceLinksTests and ReferenceLinksTests. The reason seems to be that the reflection info for the A11yCriteriaId enum was not retrieveable because the Rules project was not a dependency of the test project.
Also, updated the RuleSelection project so that resource cs files are generated when resx files are changed.
> Fixing RuleSelection unit tests which were not being run

- src/CLI/Options.cs
If a users runs the CLI with no parameters, the CommandLineParser library auto-generates help. The help is displayed in the order in which the properties are defined on the Options class. This changes moves the _required_ parameters (processName or processId) to the top of the help display.
Before the change (note that processId and processName are not first):
```
AxeWindowsCLI 0.3.6-prerelease
Copyright c 2020
ERROR(S):
At least one option from group 'Target' (processid, processname) is required.
--outputdirectory    Output directory
--scanid             Scan ID
--processid          (Group: Target) Process Id
--processname        (Group: Target) Process Name
--verbosity          Verbosity level (Quiet/Default/Verbose)
--help               Display this help screen.
--version …
```
> Reorder Options class to improve auto-generated help

- src/AutomationTests/AutomationIntegrationTests.cs
- src/OldFileVersionCompatibilityTests/Assert.cs
- src/OldFileVersionCompatibilityTests/ErrorCode.cs
- src/OldFileVersionCompatibilityTests/OldFileVersionCompatibilityTests.csproj
- src/OldFileVersionCompatibilityTests/Program.cs
- src/OldFileVersionCompatibilityTests/ProgramException.cs
- src/OldFileVersionCompatibilityTests/TestAssertionException.cs
- src/OldFileVersionCompatibilityTests/TestRunner.cs
Changing the OldFileVersionCompatibilityTests project so that it is a console app rather than a test app.
The problem was that since we changed the project to .Net Core, running all three unit tests which checked for old file version compatibility caused all three tests to appear not to run. The investigation into the problem determined there was a missing dll: Microsoft.IntelliTrace.Core. The trail went cold at that point: there is no documentation on this problem except that it exists and that it should have been fixed in the latest version of Visual Studio and .Net Core, although there are examples of users who still experience the problem with the latest versions just like us.
Since the tests run and pass individually, the solution (implemented herein) is to run each test by calling a …
> Add unit tests to check old a11ytest file version compatibility

- build/prbuild.yml
- build/signedbuild.yml
Pipeline builds started failing in the SignedBuild job because we weren't running **dotnet restore** before building. This is called out as a requirement in the [task documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops), but it seems to have just started to take effect when we moved to updated versions of the MSTest.TestFramework and MSTest.TestAdapter packages. I've added it to all builds, just as a precaution.
Signed build validation: https://dev.azure.com/mseng/1ES/_build/results?buildId=11445099&view=results
> Add nuget restore to pipeline builds

- build/signedbuild.yml
CredScan V1 is on the road to deprecation and we're starting to receive warnings during build. The recommended change is to use CredScan V2. As outlined in https://www.1eswiki.com/wiki/CredScan_Azure_DevOps_Build_Task, this involves setting the toolMajorVerion input to V2. Validation build is at https://dev.azure.com/mseng/1ES/_build/results?buildId=11457625&view=results. Compare the CredScan results (in the ComplianceDebug job) to previous results, and you'll note that we're no longer getting the warning.
> Use CredScan V2

- build/prbuild.yml
- build/signedbuild.yml
- src/CLI/CLI.csproj
- tools/scripts/BuildZippedCLI.ps1
We have an MSI installer for installing the CLI, but there are likely to be automation scenarios where people want to avoid the hassle of an MSI. To support this scenario, we will allow people to access the CLI as a ZIP file. For a given release of Axe.Windows, we'll probably publish both the MSI and ZIP formats, so people can use whichever best fits their needs.
This PR adds a PowerShell script to generate the ZIP file. The script is launched after successfully building the CLI project. Since not all dev machines are configured to allow PowerShell scripts to run automatically, we put the execution of the script behind a new environment variable: `CreateAxeWindowsZippedCLI`. This environment variable is set in the PR and signed builds, so the ZIP file will be available as an artifact for …
> Build zipped form of AxeWindowsCLI

- src/SystemAbstractions/SystemAbstractions.csproj
This change is temporary to retrigger component governance output in the build pipelines
> Add a temporary reference to System.Collections.Immutable

- src/CLI/CLI.csproj
- src/CLI_Installer/CLI_Installer.wixproj
Once CLI signing was enabled, we discovered that the ZIP version of the CLI was being built before
the signing took place, meaning that we would have multiple sets of files to support. To avoid this, we decided to make the CLI_Installer responsible for building the ZIP version of the CLI. Like the Installer itself, it will only build the release version by default.
> Move Zip creation to CLI_Installer project

- src/CLI/OptionsEvaluator.cs
- src/CLITests/OptionsEvaluatorUnitTests.cs
While experimenting with UWP apps, I found apps where the process name is ".App" instead of ".exe", and that's exactly how it shows up in the list of processes. To allow targeting of these apps. update the process name targeting to only remove the extension if it's ".exe". Add unit tests to cover the various code paths.
> Add support for targeting UWP apps

- src/CLI/CLI.csproj
- src/CLI/README.MD
- src/CLI_Installer/Product.wxs
This change adds a README.MD file to the CLI project and installs it via the MSI. I went for a markdown file instead of a text file because of its richer ability to convey formatted information, as well as the fact that we're addressing a developer audience with this tool.
The readme may grow over time. For now, the primary goal is to get people up and running and to unblock potential issues (like the absence of the .NET Core runtime)
> Add README.MD to CLI, install it with tool

- src/CLI_Installer/Product.wxs
The CLI requires .NET Runtime 3.0 or newer to be installed. Add a check to block installation if it's not there.
Our logic checks the version of dotnet.exe in its default install location. If it's 3.0 or above, then we allow the install to continue. If it's missing or the wrong version, then we display a message saying "Axe.Windows Command Line Interface (CLI) requires .NET Core Runtime 3.0 or newer. Please visit https://dotnet.microsoft.com/download/dotnet-core". Here's a screenshot:
After clicking the OK button, the user is taken to the final setup dialog (included in the existing boilerplate), which says "Axe.Windows Command Line Interface (CLI) Setup Wizard ended prematurely because of an error. Your system has not been modified. To install this program at a later time, run Setup …
> Add checks for existence of .NET Core runtime 3.0 or higher

- src/Core/Types/HeadingLevelType.cs
- src/Core/Types/LandmarkType.cs
- src/Core/Types/TypeBase.cs
- src/CoreTests/Types/HeadingLevelTypeTests.cs
- src/Desktop/Styles/StyleId.cs
- src/Desktop/Types/ChangeInfoType.cs
- src/DesktopTests/Styles/StyleIdTests.cs
Our rendering of properties are inconsistent--some have a space before the parentheses, while others don't. This change makes the rendering more consistent.
> Consistently put a space before parentheses in descriptions

- src/CLI_Installer/CLI_Installer.wixproj
- src/CLI_Installer/Product.wxs
The MSI to install the MSI is currently hardcoded to version 1.0.0.0, which is incorrect. The value for `SemVerNumber` is set in src/props/version.props, and we should apply that version to the MSI. WiX requires that this value conform to a System.Version object, so we can't include the value set for `SemVerSuffix`.
Validated by installing the built MSI, then opening Programs in Control Panel and confirming that the displayed version was 0.9.0 (which matches the current value of `SemVerNumber`)
> Apply SemVer property to MSI that installs the CLI

- src/Win32/HighContrast.cs
- src/Win32/HighContrastData.cs
- src/Win32/NativeMethods.cs
Previously,, the unit tests in OldFileVersionCompatibilityTests were not running because something in .Net Core was crashing the test process. No exception was thrown and the error did not produce a helpful error message. To work around the problem, we converted the OldFileVersionCompatibilityTests project to a console app and ran the tests from the AutomationTests project.
By working with the .Net Core team, we now see the cause of the crash was in the HighContrast class in the Wind32 project. For reasons which are still obscure, .Net Core will crash the second time the SystemParametersInfo function is called when the defaultScheme parameter of the passed-in struct is a string. When the defaultScheme parameter is changed to an IntPtr, the problem goes away. There may still be a problem …
> Update Win32.HighContrast to fix unit test crash

- build/signedbuild.yml
To simplify the publishing process (which may eventually be automated), we want to explicitly publish the CLI artifacts (as opposed to having to find them in the drop artifact). This adds 2 new artifacts, called CLI-msi and CLI-zip. Validation build: https://dev.azure.com/mseng/1ES/_build/results?buildId=11544628&view=artifacts&type=publishedArtifacts
> Publish CLI packages as separate artifacts

- src/OldFileVersionCompatibilityTests/OldFileVersionCompatibilityTests.csproj
The Microsoft.NET.Test.Sdk version was accedentally reverted when a later commit reverted the project file to make OldFileVersionCompatibilityTests a unit test project once again.
> Update Microsoft.NET.Test.Sdk reference in OldFileVersionCompatibilityTests

- build/prbuild.yml
- src/ActionsTests/ActionsTests.csproj
- src/AutomationTests/AutomationTests.csproj
- src/CLITests/CLITests.csproj
- src/CoreTests/CoreTests.csproj
- src/DesktopTests/DesktopTests.csproj
- src/OldFileVersionCompatibilityTests/OldFileVersionCompatibilityTests.csproj
- src/RuleSelectionTests/RuleSelectionTests.csproj
- src/RulesTest/RulesTests.csproj
- src/SystemAbstractionsTests/SystemAbstractionsTests.csproj
- src/TelemetryTests/TelemetryTests.csproj
- src/Win32Tests/Win32Tests.csproj
This change __should__ produce a code coverage tab and report in the PR Azure build pipeline for the release configuration.
- Add nuget package coverlet.msbuild
- Add nuget package ReportGenerator
- Update PR build dotnet test task to generate code coverage
- add report generator and publish code coverage tasks to PR build
> Update the PR build to publish code coverage data

- build/prbuild.yml
- Remove ADO publish code coverage task because we can now use codecov and the ADO task can take over a minute
- Remove collecting code coverage data from release builds because we only need one set of code coverage data per pipeline run
- Fix -f parameter value in the task which publishes data to codecov; the previous glob pattern did not work
> Fix publishing code coverage to codecov

- src/Desktop/UIAutomation/EventHandlers/EventListenerFactory.cs
- src/Desktop/UIAutomation/EventHandlers/FocusChangedEventListener.cs
The problem was that the event listener code registered for focus events on the CUIAutomation object, as opposed to the CUIAutomation8 object. We don't know exactly why CUIAutomation.PoleForPotentialSupportedPatterns  does not provide the text pattern as a supported pattern on the Win32 edit field. But CUIAutomation8 does and the text pattern is retrieved successfully.
> Fix Issue #320 - AI-Win not properly reporting text pattern on Win32 up down control

- src/Actions/Actions.csproj
- src/Actions/Resources/ErrorMessages.Designer.cs
- src/Core/Core.csproj
- src/Core/Resources/ErrorMessages.Designer.cs
Resource file generation was broken during the conversion to .Net Standard. This change makes it so that resources used by the C# code will be updated when the .resx files change.
> Fix resource references for Actions and Core

- src/Core/Enums/RuleId.cs
- src/Rules/Library/IsOffScreenChild.cs
- src/Rules/Resources/Descriptions.Designer.cs
- src/Rules/Resources/Descriptions.resx
- src/Rules/Resources/HowToFix.Designer.cs
- src/Rules/Resources/HowToFix.resx
- src/RulesTest/Library/IsOffScreenChild.cs
The evaluation strategy is to  test each element against its parent. This avoids starting with a root element and testing all its descendants. The latter would be very inefficient because the test would be re-run for each descendant of the root.
Also, the chosen strategy has the added benefit of failing while on the element with the mismatched IsOffscreen property value, which means it is easier to point users to the element with the problem. This would have been much more difficult if the non matching element were a deep descendant of the element being tested.
> Fix Issue #161 - [Feature Request] Add rule to ensure the descendants of off screen elements are also off screen.

- build/prbuild.yml
- build/signedbuild.yml
Inspired by an [AI-Win PR](https://github.com/microsoft/accessibility-insights-windows/pull/733), this PR updates the remote build's use of a [deprecated NuGet install task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/prev-versions/nuget-installer-0?view=azure-devops) to the current version of that task. It also allows the use of all 5.x versions of NuGet. A test signed build can [be found here](https://dev.azure.com/mseng/1ES/_build/results?buildId=11746771&view=results).
> Update NuGet installer task

- src/CI/Axe.Windows.nuspec
Fix #335 - [ENG] Warning NU5128 in builds
This change should match the target frameworks of the dependencies specified in the nuspec file to the frameworks of the assemblies contained in the nuget package.
> Add dependency group for .Net Standard 2.0 to nuspec

- build/signedbuild.yml
This PR removes the symbol publishing tasks from our signed build. We plan to [publish symbol packages (.snupkg)](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg) instead.
> Stop publishing symbols from build

- src/CI/Axe.Windows.nuspec
- src/CI/CI.csproj
This PR causes our nuget pack command to create a [symbols package](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg) alongside the already produced nuget package. We can then upload the new symbols package to the NuGet.org symbol server when we release. Note that the nuget package is unchanged; the *.pdb files are only included in the symbols package.
> Creating symbol package (.snupkg) alongside nuget package

- src/Desktop/UIAutomation/Patterns/ItemContainerPattern.cs
The first parameter being passed to the IUIAutomationItemContainerPattern.FindItemByProperty method was the element on which the pattern was implemented and that was throwing an exception. The first parameter should either be an item belonging to the element implementing the pattern or null. The latter indicates the search should start at the first contained element. So the code has been updated to pass null.
See https://docs.microsoft.com/en-us/windows/win32/api/uiautomationcore/nf-uiautomationcore-iitemcontainerprovider-finditembyproperty for further details.
> Fix exception caused by unexpected parameter in FindItemByProperty

- src/CI/Axe.Windows.nuspec
Currently, all .pdb files are included in our snupkg. However, Axe.Windows.CI.exe is not included in our nupkg. This PR brings the packages into alignment by excluding Axe.Windows.CI.pdb from the snupkg.
> Exclude Axe.Windows.CI.pdb from symbols package

- src/ActionsTests/ActionsTests.csproj
- src/AutomationTests/AutomationTests.csproj
- src/CLI/CLI.csproj
- src/CLITests/CLITests.csproj
- src/CLI_Full/CLI_Full.csproj
- src/CLI_Installer/CLI_Installer.wixproj
- src/CLI_Installer/Product.wxs
- src/CoreTests/CoreTests.csproj
- src/DesktopTests/DesktopTests.csproj
- src/OldFileVersionCompatibilityTests/OldFileVersionCompatibilityTests.csproj
- src/RuleSelectionTests/RuleSelectionTests.csproj
- src/RulesTest/RulesTests.csproj
- src/SystemAbstractionsTests/SystemAbstractionsTests.csproj
- src/TelemetryTests/TelemetryTests.csproj
- src/Win32Tests/Win32Tests.csproj
According to https://dotnet.microsoft.com/platform/support/policy/dotnet-core, .NET Core 3.1 is the LTS version, and .NET Core 3.0 (which we use for tests and CLI) isn't officially supported anymore. We originally had to use .NET Core because note all build environments supported .NET Core 3.1. That has now been fixed, so this upgrades us to .NET Core 3.1 for tests and the CLI. The CLI installer had to be modified to use an updated version check and to reflect the fact that the set of created files are slightly different (no more `netcoreapp20`, `netcoreapp21` or `netstandard20` runtime folders, and we ship fewer assemblies because we leverage the versions in the runtime.
Testing included signed builds, installing the CLI MSI, validating the install location, validating that apps can be …
> Upgrade from .NET Core 3.0 to .NET Core 3.1 in tests and CLI

- src/Core/Misc/ExtensionMethods.cs
- src/Desktop/UIAutomation/DesktopElement.cs
- src/RuleSelection/RuleRunner.cs
- src/Rules/Conditions/Condition.cs
- src/RulesTest/MonsterTest.cs
There are 5 places in the code where Axe.Windows is hardcoded to call Debugger.Break. These were added to provide a way to catch unexpected scenarios in Axe.Windows, but they are a real nuisance when trying to debug an app that consumes Axe.Windows (and where the exceptions aren't really that interesting). Of the 5 places where Debugger.Break was called:
- 2 were in unused methods
- 2 were in a block where an exception is reported (which means that the exception will be detectable in telemetry)
- 1 was in a scenario that telemetry suggested never occurred
> Remove hardcoded calls to System.Diagnostics.Debugger.Break

- src/AutomationTests/AutomationIntegrationTests.cs
- src/Rules/Library/ClickablePointOnScreen.cs
- src/RulesTest/Library/ClickablePointOnScreen.cs
Fix #352
The rule is meant to ensure element's with valid clickable points are marked as on screen so that ATs can recognize those elements as clickable. In the case given in the bug, the button has a valid clickable point and is not off screen (according to UIA), which is an error. However, the element is also not focusable, which means it cannot be focused or (theoretically) invoked. In this case, the button does not actually appear on screen.
When the element is not keyboard focusable, the rules cannot determine if the element's IsOffScreen property is correct or not. Therefore, the rule will not be run when the element is not keyboard focusable.
> Fix Issue #352 False-negative result for the rule "An element's IsOffScreen property must be false when its clickable point is on screen."

- src/Actions/Actions/ListenAction.cs
- src/Actions/Enums/Enums.cs
Changing the order in which event handlers are registered addresses [Accessibility Insights for Windows bug #694](https://github.com/microsoft/accessibility-insights-windows/issues/694). However, because the results of changing the registration order may have as yet unknown side-effects, we are making the ordering of event registration configurable via the EventRegistrationOrder enumeration.
> Change the default order in which event handlers are registered

- src/Actions/Actions.csproj
- src/Actions/Actions/SelectAction.cs
- src/Actions/AssemblyInfo.cs
- src/Actions/Trackers/MouseTracker.cs
- src/Actions/Trackers/TreeTracker.cs
- src/Automation/AssemblyInfo.cs
- src/Automation/Automation.csproj
- src/Automation/OutputFileHelper.cs
- src/Automation/SnapshotCommand.cs
- src/AutomationTests/SnapshotCommandUnitTests.cs
- src/CLI/CLI.csproj
- src/CLI/ParameterException.cs
- src/CLI/ProcessHelper.cs
- src/CLI/Program.cs
- src/Core/AssemblyInfo.cs
- src/Core/Core.csproj
- src/Core/Results/ScanResults.cs
- src/Desktop/AssemblyInfo.cs
- src/Desktop/Desktop.csproj
- src/RuleSelection/AssemblyInfo.cs
- src/RuleSelection/RuleSelection.csproj
- src/Rules/AssemblyInfo.cs
- src/Rules/Library/LocalizedControlTypeIsReasonable.cs
- src/Rules/Rules.csproj
- src/SystemAbstractions/SystemAbstractions.csproj
- src/Telemetry/Telemetry.csproj
The FSCopAnaalyzers were meant to be used in all our production projects, but through some error they were not. The change adds them to production projects and fixes the errors found by the analyzers.
Most errors were of the following types:
- Weak reference in lock
- Methods could be static
- Should catch more specific exception
There is one case where an error check which threw an exception was removed in SnapshotCommand.Execute. This is okay because the call to Scan will immediately check the nullity of the returned value which used to be checked.
The warning CA1303 was suppressed throughout the entirety of the CLI project. The warning flags quoted strings. We have chosen to suppress the warning because the work to address it would only be useful if we planned to localize the project, …
> Add FXCopAnalyzers to production projects

- README.md
I've found that the link to CLI readme is not working when clicking it from GitHub. Seems like capitalization matters!
> Fix link to CLI readme

- src/ActionsTests/ActionsTests.csproj
- src/AutomationTests/AutomationTests.csproj
- src/CLITests/CLITests.csproj
- src/CoreTests/CoreTests.csproj
- src/DesktopTests/DesktopTests.csproj
- src/OldFileVersionCompatibilityTests/OldFileVersionCompatibilityTests.csproj
- src/RuleSelectionTests/RuleSelectionTests.csproj
- src/RulesTest/RulesTests.csproj
- src/SystemAbstractionsTests/SystemAbstractionsTests.csproj
- src/TelemetryTests/TelemetryTests.csproj
- src/Win32Tests/Win32Tests.csproj
Making this change manualy since the dependabot PR had conflicts
> Bump MSTest.TestFramework from 2.1.1 to 2.1.2

- build/settings.targets
Currently, we do not digitally sign axe-windows assemblies. This PR enables digital signing for its assemblies using the proper Microsoft 3rd party cert. [Successful signed build here](https://dev.azure.com/mseng/1ES/_build/results?buildId=12530233&view=results).
> Enable authenticode signing with 3rd party cert

- tools/scripts/BuildZippedCLI.ps1
This just updates the usage comment in a script. We changed from .NET core 3.0 to .NET core 3.1 but missed this.
> Update a netcore3.0 comment that was overlooked

- build/signedbuild.yml
A previous PR (#83) disabled signing our nuget package. Because our guidance has change, we now want to sign the package. This PR reenables signing of the package. You can find a signed build output [here](https://dev.azure.com/mseng/1ES/_build/results?buildId=12548401&view=results).
> Reenable nuget signing

- build/NetStandardTest.targets
- src/ActionsTests/ActionsTests.csproj
- src/AutomationTests/AutomationTests.csproj
- src/CLITests/CLITests.csproj
- src/CoreTests/CoreTests.csproj
- src/DesktopTests/DesktopTests.csproj
- src/OldFileVersionCompatibilityTests/OldFileVersionCompatibilityTests.csproj
- src/RuleSelectionTests/RuleSelectionTests.csproj
- src/RulesTest/RulesTests.csproj
- src/SystemAbstractionsTests/SystemAbstractionsTests.csproj
- src/TelemetryTests/TelemetryTests.csproj
- src/Win32Tests/Win32Tests.csproj
Using .Net Framework 4.72 because that is what Accessibility Insights for Windows uses.
Moved target frameworks property to a common .target file where it can easily be reused. The condition in the .target file is needed because CLITests references CLI, which is built for the .Net Core Framework and not .Net Standard (So .Net Framework is not compatible with CLI).
> Fix #285 Add .Net Framework tests in addition to .Net Core tests

- tools/scripts/BuildZippedCLI.ps1
Currently, the auto injected Codesign Validation task scans our entire project for signing violations. Since we only ship specific 
assemblies, this leads to hundreds of false positives. A build variable is available to set the root directory that the task scans. This PR sets that variable to the temp directory we create while making our zipped CLI package. This package contains a superset of all the assemblies that we ship (MSI, zip, and Nuget package), so it seems like a good choice for where to direct the Codesign Validation task--I'm open to other suggestions for where to scan, though. You can find an example of the impact on the build task [here](https://dev.azure.com/mseng/1ES/_build/results?buildId=12617518&view=logs&j=7c3ebc89-e7dd-5791-8c02-2ea1f3a27b50&t=95036218-ae8d-5d14-6fa9-9 …
> Set Codesign Validation scan directory when creating zip

- build/signedbuild.yml
- tools/scripts/BuildZippedCLI.ps1
This PR replaces the work in PR #398 to validate CLI and CLI_Full's assemblies rather than just CLI_Full's. This ensures complete codesign validation coverage. An example run can be found [here](https://dev.azure.com/mseng/1ES/_build/results?buildId=12624793&view=results).
> Update codesign validation

- build/prbuild.yml
- src/SystemAbstractionsTests/SystemAbstractionsTests.csproj
This will make it possible for dependabot to update the version of CodeCov without an engineer having to manually change the version used in prbuild.yml.
> Set an ADO variable for the CodeCov version

- build/NetStandardTest.targets
- src/ActionsTests/ActionsTests.csproj
- src/AutomationTests/AutomationTests.csproj
- src/CoreTests/CoreTests.csproj
- src/DesktopTests/DesktopTests.csproj
- src/OldFileVersionCompatibilityTests/OldFileVersionCompatibilityTests.csproj
- src/RuleSelectionTests/RuleSelectionTests.csproj
- src/RulesTest/RulesTests.csproj
- src/SystemAbstractionsTests/SystemAbstractionsTests.csproj
- src/TelemetryTests/TelemetryTests.csproj
- src/Win32Tests/Win32Tests.csproj
The problem was that the <TargetFrameworks> property was specified in netStandard.Test.targets. And that worked fine, until you cleaned your project directory. At that time, the packages that you had previously downloaded were wiped out and Visual Studio wouldn't reload them because the <TargetFrameworks> property wasn't in the project files themselves.
This did not impact the build because the NuGet packages are retrieved by an Azure pipelines task which is, apparently, savvy enough to get the <TargetFrameworks> property from the imported .targets file.
> Fix a problem where Visual Studio could not load NuGet packages

- src/Rules/Library/BoundingRectangleNotNull.cs
- src/RulesTest/Library/BoundingRectangleNotNullTest.cs
Fix #402
The problem was the code tested for an English Name property string and the tests were run on a non-English application.
The change makes the test more broad, but it should still be limited by the AutomationId of "SystemMenuBar".
> Fix [BUG] BoundingRectangleNotNull fails to properly exclude System menu bars if the text is non-English

- src/Desktop/UIAutomation/A11yAutomation.cs
- src/Desktop/UIAutomation/DesktopElementHelper.cs
This change fixes AI-Win issue [#811](https://github.com/microsoft/accessibility-insights-windows/issues/811).
The problem was that the A11yAutomation class used an older version of the CUIAutomation object.
> Fix: [BUG] AIWin doesn't report a Win32/WinForms ListView's support for UIA Grid and Table patterns

- src/CurrentFileVersionCompatibilityTests/CurrentFileVersionCompatibilityTests.csproj
- src/CurrentFileVersionCompatibilityTests/Program.cs
Our builds (local and in the pipeline) have been producing the following warning for some time now:
Warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Collections.Immutable, Version=1.2.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
The root cause of this warning is that we upgraded (via dependabot) System.Collections.Immutable from version 1.7.0 to version 1.7.1, without updating the CurrentFileVersionCompatibilityTests project. This project intentionally pulls in an old version of Axe.Windows, and that old version of Axe.Windows incorrectly listed System.Collections.Imutable as a dependency, …
> System collection immutable warning

- build/prbuild.yml
- src/SystemAbstractionsTests/SystemAbstractionsTests.csproj
This reverts commit be06b530c6c18cc0264c31d4e568b1724690892d.
This change tried to make it so that when dependabot updated the version of the CodeCov package, the build wouldn't break because of the discrepancy between the version in the project and the version specified in prbuild.yml. The variable should have been correctly set based on the output from the target added to SystemAbstractionsTest.csproj. But either the variable wasn't specified correctly, or it wasn't picked up by the Azure pipeline. Unfortunately, the pipeline didn't fail to let us know the change wasn't working. Either way, the change caused our code coverage data to drop; so we're reverting it.
> Revert "Set an ADO variable for the CodeCov version (#405)"

- docs/AutomationReference.md
- docs/NewProject.md
- docs/SetUpDevEnv.md
- src/CI/App.config
- src/CI/CI.csproj
- src/CurrentFileVersionCompatibilityTests/App.config
- src/CurrentFileVersionCompatibilityTests/CurrentFileVersionCompatibilityTests.csproj
- src/RulesMD/App.config
- src/RulesMD/RulesMD.csproj
I installed a fresh version of VS, and installed only .NET 4.7.2 for AIWin, with no 4.7.1 installed. To my surprise, Axe.Windows refused to load. As it turns out, the three non-production projects that still use the old csproj format (and there are specific reasons that they can't switch formats) are still using .NET 4.7.1, which is scheduled to reach end-of-life in October 2020.
This PR does the following:
- Specifies .NET 2019 as our target build environment
- Specifies .NET Standard 2.0 as our required format
- Targets .NET 4.7.2 in the 3 projects that were targeting 4.7.1
- Updates `NewProject.md` to steer the user towards starting with an existing csproj file then customizing it. This should also be resilient to future changes, since the reference file will get updated as changes …
> Update tool references and instructions

- src/CurrentFileVersionCompatibilityTests/App.config
- src/CurrentFileVersionCompatibilityTests/CurrentFileVersionCompatibilityTests.csproj
- src/CurrentFileVersionCompatibilityTests/Program.cs
- src/CurrentFileVersionCompatibilityTests/packages.config
After merging #411, it occurred to me that there might be a cleaner solution. Rather than add infrastructure to keep dependabot changes from introducing warnings that we couldn't detect, perhaps we can remove the root cause of the warnings. Some history:
- Axe.Windows has _never_ needed System.Collections.Immutable--it was a legacy of a completely unrelated component that happened to not get removed when we created Axe.Windows.
- As dependabot identified new versions of System.Collections.Immutable, we dutifully updated the csproj file to the new version, even though they weren't being used.
- New versions of System.Collections.Immutable pulled in new dependencies, which also got updated, and so on...
So here's a different approach:
1. MANUALLY remove all package references from the …
> Purge unnecessary System.Collections.Immutable goo

- build/prbuild.yml
- src/SystemAbstractionsTests/SystemAbstractionsTests.csproj
This reverts commit 07be6d9feb520f6e29b95a64996de6b478836b41.
It turns out reverting PR #405 didn't help the problem with getting code coverage from CodeCov, so we're re-reverting it.
> Revert "revert "Set an ADO variable for the CodeCov version (#405)" (#412)"

- src/ActionsTests/ActionsTests.csproj
- src/AutomationTests/AutomationTests.csproj
- src/CoreTests/CoreTests.csproj
- src/DesktopTests/DesktopTests.csproj
- src/OldFileVersionCompatibilityTests/OldFileVersionCompatibilityTests.csproj
- src/RuleSelectionTests/RuleSelectionTests.csproj
- src/RulesTest/RulesTests.csproj
- src/SystemAbstractionsTests/SystemAbstractionsTests.csproj
- src/TelemetryTests/TelemetryTests.csproj
- src/Win32Tests/Win32Tests.csproj
The change to <TargetFrameworks> allowed us to build and test multiple frameworks like .Net Framework, but for reasons not yet determined stopped our code coverage from working. We have elected to restore the code coverage for now and work on testing multiple frameworks in a different way.
> Switch proj files back to use <TargetFramework>

- build/signedbuild.yml
Signed builds broke as a result of a change in the signing plugin. Apparently our version is no longer supported, so we need to upgrade. I'll make a similar change in AIWin.
Validation build showing it works: https://dev.azure.com/mseng/1ES/_build/results?buildId=12757078&view=results
> chore: Use newer version of signing plugin

- src/Rules/Library/SiblingUniqueAndFocusable.cs
- src/RulesTest/Library/SiblingUniqueAndFocusableTest.cs
The fix is to make elements which support the GridItem exempt from checking for duplicate siblings under the assumption that such elements can be distinguished by their row and column information.
> Fix: AIWin unexpectedly reports failures with WPF DataGrid's which contain cells with text duplicated between cells · Issue #417

- src/Win32/Win32Enums.cs
The HotKey class was removed from Axe.Windows months ago, but somehow the HotkeyModifier enum was overlooked. We just noticed it was still there in a recent code review. Removing it since it no longer adds value.
> chore: Remove unused HotkeyModifier enum

- src/Rules/Library/BoundingRectangleSizeReasonable.cs
- src/RulesTest/Library/BoundingRectangleSizeReasonableTest.cs
Issue #432 suggested that separators should be exempt from the `BoundingRectangleSizeReasonable` rule. After internal review, we agreed. This change excludes separators and updates the unit tests.
> fix: Revise BoundingRectangleSizeReasonble to ignore Separators

- src/props/version.props
Bump version number to 1.0.3 since we just released 1.0.2
> chore: Bump build version to 1.0.3

- src/Automation/Automation.csproj
Axe.windows fails to build from VS 16.7.4 unless you're running as administrator. The problem is that it can't write C:\Axe.Windows.Automation.xml without admin privileges, so it fails the build. It works fine when running as administrator, and it ends up creating 2 copies of the XML file--one in the root, and one where it's expected in the bin folder. I'm not sure why it's writing 2 copies or how long it's done this--it could be be a bug in the dev tools.
This change modifies how we specify the XML file. Instead of specifying the file, we just tell VS to build it and it auto-generates the file based on the assembly name (which, happily, is the name that we were explicitly specifying). The [MSDN docs](https://docs.microsoft.com/en-us/dotnet/csharp/codedoc) say that the two methods are …
> chore: Change how Axe.Windows.Automation.xml file is specified

- src/RulesTest/Library/BoundingRectangleContainedInParentTest.cs
- src/RulesTest/Library/BoundingRectangleDataFormatCorrectTest.cs
- src/RulesTest/Library/BoundingRectangleNotAllZerosTest.cs
- src/RulesTest/Library/BoundingRectangleNotNullTest.cs
- src/RulesTest/Library/BoundingRectangleNotValidButOffScreenTest.cs
- src/RulesTest/Library/BoundingRectangleSizeReasonableTest.cs
- src/RulesTest/Library/NameIsInformative.cs
- src/RulesTest/Library/NameIsNotEmpty.cs
- src/RulesTest/Library/NameIsNotNull.cs
- src/RulesTest/Library/NameIsNotWhiteSpace.cs
- src/RulesTest/Library/NameIsReasonableLength.cs
While working on #439, I noticed that NameExcludesSpecialCharacters was specifying the parameters to `Assert.AreEqual` in the wrong order. Correct order is expected value first, actual value second. The tests will pass or fail the same with either ordering, but the error message is incorrect if the parameters are specified in the incorrect order. The incorrect error message made it harder to identify my problem :(
I scanned other tests and found 11 other files where the ordering to `Assert.AreEqual` or `Assert.AreNotEqual` was incorrect in one or more unit tests. This PR simply corrects the ordering. Ironically, it leaves the existing (incorrect) order in NameExcludesSpecialCharacters, since that file is going away. This is a preemptive action to avoid a merge conflict once both PR's are …
> chore: Reorder some Assert.Are[Not]Equal parameters

- src/Actions/Actions/SelectAction.cs
- src/Actions/Trackers/MouseTracker.cs
- src/Desktop/UIAutomation/A11yAutomation.cs
This is the axe.windows portion of https://github.com/microsoft/accessibility-insights-windows/issues/974. It modifies the mouse tracking code to normalize the element based on the current TreeViewMode. It also makes a couple of unrelated changes (2 comments, 1 extra newline, and sorting the using blocks) that I happened to notice while I was working on this change.
The change itself is simple. The SelectAction already has the TreeViewMode, so we just need to pass it to the MouseTracker, then use this to normalize the element to the TreeViewMode. The code to check the IsContentElement and IsControlElement properties could be removed if we always calling Normalize, but that complicates the object management, so we make an extra check (which the compiler will optimize easily) and only call …
> fix: Normalize mouse tracking

- docs/RulesDescription.md
PR #445  Split the `ControlShouldSupportSetInfo` rule into 2 rules:
- `ControlShouldSupportSetInfoWPF` applies only to WPF and returns a warning on failure
- `ControlShouldSupportSetInfoXAML` applies only to XAML and returns an error on failure
Update the RulesDescription.md accordingly
> chore: Update RulesDescription.md to reflect recent rule split

- src/CLI/CLI.csproj
- Microsoft.CodeAnalysis.Analyzers
- Roslyn.Diagnostics.Analyzers
> Chore: Add two missing analyzer packages to CLI project

- docs/RulesDescription.md
- src/Core/Enums/RuleId.cs
- src/Rules/Library/ControlShouldSupportTablePattern.cs
- src/Rules/Library/ControlShouldSupportTablePatternInEdge.cs
- src/RulesTest/Library/ControlShouldSupportTablePattern.cs
- src/RulesTest/Library/ControlShouldSupportTablePatternInEdge.cs
The old rule returned two possible `ErrorCode` values (in addition to `ErrorCode.Pass`), whereas each of the new separate rules only returns one. This makes it possible for us to specify the failure error code as part of the `RuleInfo` data, which will allow us to automate documentation for the rules regarding which error codes are returned by which rules.
> Chore: Break ControlShouldSupportTablePattern rule into two rules

- src/Rules/RuleProvider.cs
- src/Rules/RuleRunner.cs
- src/Rules/Rules.cs
- src/RulesTest/RuleRunnerTests.cs
Extracted code from `Rules` into `RuleRunner` in order to test the rule running logic. The extraction was essentially a cut and paste operation.
The idea is to have rule running logic thoroughly unit tested before an upcoming modification which will add another mechanism for evaluating rules and returning `EvaluationCode` values.
> Chore: Add unit tests for the code which runs all rules

- src/Rules/Rule.cs
- src/Rules/RuleInfo.cs
- src/Rules/RuleRunner.cs
- src/RulesTest/RuleImplementations/RuleWithPassesTestNotImplemented.cs
- src/RulesTest/RuleRunnerTests.cs
This change makes it so that if `IRule.Info.ErrorCode` exists for a givenRule`, `IRule.PassesTest` will be called instead of `IRule.Evaluate` to determine if the rule passes its test. In addition, if the rule fails its test, the value of `IRule.Info.ErrorCode` will be returned.
This means that each rule can now specify in its info the `EvaluationCode` to be returned if the rule's test does not pass. And that, in turn, allows us to get the error code for each rule via reflection and display it in our documentation.
> Chore: Add RuleInfo.ErrorCode and IRule.PassesTests

- src/Rules/Rule.cs
- src/RulesTest/RuleImplementations/RuleWithEvaluateNotImplemented.cs
- src/RulesTest/RuleImplementations/RuleWithPassesTestNotImplemented.cs
- src/RulesTest/RuleRunnerTests.cs
The new test ensures that if `Rule.Info.ErrorCode` has no value, `Rule.Evaluate` is expected to be overridden. This is the converse of the existing test where if `Rule.Info.ErrorCode` has a value, `Rule.PassesTest` is expected to be overridden.
Also added tests to confirm the test rule implementations match expectations for the other tests.
Made `Rule.Evaluate` and `Rule.PassesTest` `virtual` so they could be overridden by subclasses.
> Chore: Add unit test for Rule.Evaluate not implemented

- src/Automation/Interfaces/IOutputFileHelper.cs
- src/Automation/OutputFileHelper.cs
- src/Automation/SnapshotCommand.cs
- src/AutomationTests/OutputFileHelperUnitTests.cs
- src/AutomationTests/SnapshotCommandUnitTests.cs
Fixes #460
This fix still allows the exception mentioned in the bug to be propagated to the user. However, the user will not encounter the exception if no output file is requested.
The OutputFileHelper class must still exist as part of the IScanTools interface even though it will not be used if no output files are requested. This helps to keep the change small and to  keep the code concise.
> Fix: Create directory for output files only when files are requested

- build/NetStandardRelease.targets
- src/Actions/Actions.csproj
- src/Automation/Automation.csproj
- src/CLI/CLI.csproj
- src/Core/Core.csproj
- src/Desktop/Desktop.csproj
- src/RuleSelection/RuleSelection.csproj
- src/Rules/Rules.csproj
- src/SystemAbstractions/SystemAbstractions.csproj
- src/Telemetry/Telemetry.csproj
- src/Win32/Win32.csproj
Based on recommendation from https://docs.microsoft.com/en-us/visualstudio/code-quality/migrate-from-fxcop-analyzers-to-net-analyzers?view=vs-2019
> Chore: Switch from using Microsoft.CodeAnalysis.FxCopAnalyzers to Microsoft.CodeAnalysis.NetAnalyzers

- src/Core/Enums/RuleId.cs
- src/Rules/Library/LocalizedControlTypeIsNotCustom.cs
- src/Rules/Library/LocalizedControlTypeIsNotCustomWPFGridCell.cs
- src/Rules/PropertyConditions/ElementGroups.cs
- src/Rules/Resources/HowToFix.Designer.cs
- src/Rules/Resources/HowToFix.resx
- src/RulesTest/Library/LocalizedControlTypeIsNotCustomWPFGridCell.cs
- src/RulesTest/PropertyConditions/ElementGroupsTests.cs
Add extra how-to-fix information about accessibility switches in the case where the `ControlType` property is `Custom`, the `Framework` is "WPF", and the `ClassName` is "DataGridCell". The how-to-fix information in question applies to .Net versions older than 4.7.1.
To do this, I created a new rule: `LocalizedControlTypeIsNotCustomWPFGridCell`. The new rule should apply in the same cases as `LocalizedControlTypeIsNotCustom`, but only if the platform is `WPF` and the `ClassName` is `DataGridCell`. The existing rule, `LocalizedControlTypeIsNotCustom`, should not be run in the case of a WPF DataGridCell.
I used string formatting for the htf info to avoid duplicating text in documentation which could become mismatched.
I reworked the unit tests in LocalizedControlTypeIsNotCustom.cs a bit to …
> Fix: Issue #441

- src/Rules/Library/NameExcludesLocalizedControlType.cs
- src/Rules/PropertyConditions/ElementGroups.cs
- src/RulesTest/Library/NameExcludesLocalizedControlType.cs
- src/RulesTest/PropertyConditions/ElementGroupsTests.cs
The change is to allow edit controls in older versions of Edge (before Anaheim) to have the same name and localized control type when the LCT is either "password" or "email". Note: "email" is not specifically called out in the bug, but it is a similar issue we've received through support channels.
Also, Updated the existing unit tests for `NameExcludesLocalizedControlType` just a touch to be a little more robust.
> Fix: Issue #471

- src/Actions/Actions.csproj
- src/Automation/Automation.csproj
- src/Core/Core.csproj
- src/Desktop/Desktop.csproj
- src/RuleSelection/RuleSelection.csproj
- src/Rules/Rules.csproj
- src/SystemAbstractions/SystemAbstractions.csproj
- src/Telemetry/Telemetry.csproj
- src/Win32/Win32.csproj
We have been unnecessarily including a PackageReference to the BinSkim tools. BinSkim 1.7.1 has a breaking change that prevents us from including the PackageReference, so we're removing the reference. I'll kick off a signed build after this merges to ensure that the BinSkim build task is working correctly without the PackageReference.
> chore: Remove BinSkim package reference

- src/Rules/Library/ControlShouldNotSupportTablePattern.cs
- src/RulesTest/Library/ControlShouldNotSupportTablePattern.cs
No longer check that the table pattern doesn't exist for list elements with the class name "SysListView32" because developers can't remove the pattern and the framework is unlikely to change.
> Fix: Address bug #483

- src/Rules/Resources/Descriptions.Designer.cs
- src/Rules/Resources/Descriptions.resx
In https://github.com/Microsoft/accessibility-insights-windows/commit/c2cc94dd2cf596dfd4324891572514a80508394f, the `NameIsInformative` description was incorrectly modified as follows:
Original Value | Modified Value
--- | ---
The name property of an element should not contain class names like 'Microsoft.*.*' or 'Windows.*.*' as these are not usually informative. | The Name property must not include its class name.
This PR restores the description to its original value.
> fix: Correct the description for the NameIsInformative rule

- src/Rules/Library/BoundingRectangleNotNull.cs
- src/Rules/Library/BoundingRectangleOnWPFTextParent.cs
- src/Rules/Library/ControlShouldNotSupportInvokePattern.cs
- src/Rules/Library/ControlShouldSupportSetInfoWPF.cs
- src/Rules/Library/ControlShouldSupportSetInfoXAML.cs
- src/Rules/Library/ControlShouldSupportTablePattern.cs
- src/Rules/Library/ControlShouldSupportTablePatternInEdge.cs
- src/Rules/Library/ControlShouldSupportTextPattern.cs
- src/Rules/Library/IsKeyboardFocusableTopLevelTextPattern.cs
- src/Rules/Library/LandmarkNoDuplicateBanner.cs
- src/Rules/Library/LandmarkNoDuplicateContentInfo.cs
- src/Rules/Library/LandmarkOneMain.cs
- src/Rules/Library/SelectionPatternSelectionRequired.cs
- src/Rules/Library/SiblingUniqueAndFocusable.cs
- src/Rules/Library/SiblingUniqueAndNotFocusable.cs
- src/Rules/PropertyConditions/ElementGroups.cs
- src/Rules/PropertyConditions/Framework.cs
- src/Rules/PropertyConditions/UWP.cs
This replaces a `Condition` statement in a rule like
`StringProperties.Framework.Is(FrameworkId.Edge)`
with
`Edge`
This makes the code easier to comprehend.
> Chore: Replace lengthy framework conditions with shorter ones

- src/Rules/Library/NameIsInformative.cs
- src/RulesTest/Library/NameIsInformative.cs
Fixes issue #485.
This rule is intended to catch an accessibility error in older versions of .Net frameworks where controls such as lists would have there item names automatically generated and they would be given the name of their .Net class, such as "Microsoft.Controls.ListItem", instead of an informative accessible name.
It is possible to have legitimate names for controls which violate this rule. Because this is rare, we consider occasionally having a possible false positive for this rule acceptable. However, the accessibility problem described above never happened in the Win32 framework. Therefore, we're disabling this rule for Win32.
The astute observer will notice that while I added unit tests for most of the properties used to match the rule, I did not add unit tests for …
> Fix: #485 NameIsInformative false positive in Win32 apps

- src/CLI_Installer/Product.wxs
Since the last release, we've updated several assemblies that used to use the assemblies from the OS-installed .NET runtime. The revised assembly versions are pulled into the app's manifest, so we need to reference them in the WXS file. I also updated the names of two file ID's to be a little more descriptive (it seemed to make sense now that we have more files).
Tested by building the MSI locally, installing it, and ensuring that it works as expected.
> fix: Update WXS file to use updated components

- src/RuleSelection/Resources/DefaultGuidelineUrls.Designer.cs
- src/RuleSelection/Resources/DefaultGuidelineUrls.resx
- src/Rules/A11yCriteriaId.cs
We noticed in AI-Windows that sometime late last year, the www.access-board.gov site we link to changed. Now, our links are redirected to the correct page, but the fragment bringing you to the right place on the page is lost. You can see the full repro steps in this AI-Win issue: https://github.com/microsoft/accessibility-insights-windows/issues/1017.
This PR fixes the issue by updating the URL. These were the only places in either repo referencing access-board.gov.
> fix: Update www.access-board.gov links with current URL

- src/CI/Axe.Windows.nuspec
We failed to update the nuspec file to reflect the following changes:
- Microsoft.Win32.Registry was bumped to version 5.0.0 in #465 
- System.Drawing.Common was bumped to version 5.0.0 in #466 
- System.IO.Packaging was bumped to version 5.0.0 in #467 
When we consume Axe.Windows 1.0.5, the transitive dependencies get lost, which generates build warnings (and potential for more significant bugs).
This PR updates the nuspec file. I've already consumed it into AIWin and confirmed that this fixes the build warnings. My recommendation would be to release this as 1.0.6, even though we have no code changes between the builds.
> chore(deps): Update nuspec file to reflect updated dependencies

- src/Rules/Library/BoundingRectangleCompletelyObscuresContainer.cs
- src/Rules/Library/BoundingRectangleContainedInParent.cs
- src/Rules/Library/BoundingRectangleDataFormatCorrect.cs
- src/Rules/Library/BoundingRectangleNotAllZeros.cs
- src/Rules/Library/BoundingRectangleNotNull.cs
- src/Rules/Library/BoundingRectangleNotValidButOffScreen.cs
- src/Rules/Library/BoundingRectangleOnUWPMenuBar.cs
- src/Rules/Library/BoundingRectangleOnUWPMenuItem.cs
- src/Rules/Library/BoundingRectangleOnWPFTextParent.cs
- src/Rules/Library/BoundingRectangleSizeReasonable.cs
- src/RulesTest/Library/BoundingRectangleCompletelyObscuresContainerTest.cs
- src/RulesTest/Library/BoundingRectangleContainedInParentTest.cs
- src/RulesTest/Library/BoundingRectangleDataFormatCorrectTest.cs
- src/RulesTest/Library/BoundingRectangleNotAllZerosTest.cs
- src/RulesTest/Library/BoundingRectangleNotNullTest.cs
- src/RulesTest/Library/BoundingRectangleNotValidButOffScreenTest.cs
- src/RulesTest/Library/BoundingRectangleOnUWPMenuBarTest.cs
- src/RulesTest/Library/BoundingRectangleOnUWPMenuItemTest.cs
- src/RulesTest/Library/BoundingRectangleOnWPFTextParentTest.cs
- src/RulesTest/Library/BoundingRectangleSizeReasonableTest.cs
Adding the evaluation code to the rule's info will allow us to automatically generate documentation which provides the rule's expected error code.
> Chore: Update some rules to use the new PassesTest method instead of Evaluate

- src/Rules/Library/ChildrenNotAllowedInContentView.cs
- src/Rules/Library/ClickablePointOffScreen.cs
- src/Rules/Library/ClickablePointOnScreen.cs
- src/Rules/Library/ComboBoxShouldNotSupportScrollPattern.cs
- src/RulesTest/Library/ClickablePointOffScreen.cs
- src/RulesTest/Library/ClickablePointOnScreen.cs
- src/RulesTest/Library/ComboBoxShouldNotSupportScrollPatternTests.cs
Adding the evaluation code to the rule's info will allow us to automatically generate documentation which provides the rule's expected error code.
>     Chore: Update rules to use the new PassesTest method instead of Evaluate

- src/Rules/Library/ButtonInvokeAndExpandeCollapsePatterns.cs
- src/Rules/Library/ButtonInvokeAndTogglePatterns.cs
- src/Rules/Library/ButtonShouldHavePatterns.cs
- src/Rules/Library/ButtonToggleAndExpandeCollapsePatterns.cs
- src/RulesTest/Library/ButtonInvokeAndExpandCollapsePatterns.cs
- src/RulesTest/Library/ButtonInvokeAndTogglePatterns.cs
- src/RulesTest/Library/ButtonPatterns.cs
- src/RulesTest/Library/ButtonToggleAndExpandCollapsePatterns.cs
Adding the evaluation code to the rule's info will allow us to automatically generate documentation which provides the rule's expected error code.
> Chore: Update more rules to use the new PassesTest method instead of Evaluate

- src/CLI/README.MD
This PR adds information about how to install the MSI installer silently. We're adding docs like this for several of our Windows installers (AI-Windows, AI-Unified, etc) so users who wish to avoid the graphical interface can do so.
> docs: add instructions for silent installation

- src/Rules/Library/ControlShouldNotSupportInvokePattern.cs
- src/Rules/Library/ControlShouldNotSupportScrollPattern.cs
- src/Rules/Library/ControlShouldNotSupportTablePattern.cs
- src/Rules/Library/ControlShouldNotSupportTogglePattern.cs
- src/Rules/Library/ControlShouldNotSupportValuePattern.cs
- src/Rules/Library/ControlShouldNotSupportWindowPattern.cs
- src/RulesTest/Library/ControlShouldNotSupportScrollPatternTests.cs
- src/RulesTest/Library/ControlShouldNotSupportTablePattern.cs
Adding the evaluation code to the rule's info will allow us to automatically generate documentation which provides the rule's expected error code.
> Chore: Update rules to use the new PassesTest method instead of Evaluate

- src/RulesMD/EvaluationCodeDescriptions.md
- src/RulesMD/MarkdownCreator.tt
- src/RulesMD/RulesMD.csproj
Adding a column for error code to the autogenerated table of details for the axe-windows rules.
Provides the error code/severity for each ule in axe-windows. This allows users to get a comprehensive overview of which rules throw which type of error code:  error/warning/open/note.
> Chore: Add error code to auto generated documentation

- src/Rules/PropertyConditions/StringProperty.cs
- src/RulesTest/PropertyConditions/StringPropertiesTest.cs
Previously, in `StringProperty.MatchesRegEx` we did not check the return value of `GetStringPropertyValue`, which could occasionally be null. In such cases, this caused a null access exception.
We have seen cases in our telemetry which show us that sometimes string properties being tested can be null. This isn't especially valuable to us as telemetry. But it is possibly worse for users who may see these execution errors represented as accessibility errors in the UI.
The decision to return false outright rather than log an exception is based on the simple logic that if a string property is null, it cannot possibly match a regular expression. And any other logical part of a test should be uneffected.
> Chore: Eliminate useless exception

- src/Rules/Conditions/StringDecoratorCondition.cs
- src/Rules/Library/HelpTextExcludesPrivateUnicodeCharacters.cs
- src/Rules/Library/ListItemSiblingsUnique.cs
- src/Rules/Library/LocalizedControlTypeExcludesPrivateUnicodeCharacters.cs
- src/Rules/Library/LocalizedControlTypeIsNotCustomWPFGridCell.cs
- src/Rules/Library/LocalizedControlTypeIsReasonable.cs
- src/Rules/Library/NameExcludesControlType.cs
- src/Rules/Library/NameExcludesPrivateUnicodeCharacters.cs
- src/Rules/PropertyConditions/Relationships.cs
StyleCop used to insist that we use lower-case `string` instead of Pascal-case `String`. As a result, the vast majority of the code uses the lower-case version. There are a dozen outliers--one caught my attention so I decided to change them purely for consistency. This has no impact on the functionality of the code.
> chore: Standardize on lower case "string" instead of Pascal case "String"

- src/Rules/Library/NameExcludesControlType.cs
- src/Rules/Resources/ErrorMessages.Designer.cs
- src/Rules/Resources/ErrorMessages.resx
We have an Exception message that tells us that a control has an invalid ControlTypeId, but since the message doesn't tell us what the ID is, the message is not overly useful.
Make the message more useful
> chore: Include missing control type in Exception message

- build/prbuild.yml
Disable CG in unsigned builds. 
Unsigned CG builds have recently failed, and when working, they don't block merging with bad components. CG works correctly in the signed pipeline, so there's no risk of accidentally releasing a bad component should it get introduced in a PR.
> chore: Disable CG in unsigned builds

- build/NetStandardRelease.targets
VisualStudio 16.9.0 recently released, and builds with the new version are suddenly broken due to 10 new warnings that were not occurring before. We've reached out to the Visual Studio team to understand why VS suddenly decided to raise these warnings, but the quickest mitigation to get everyone unstuck is to suppress these warnings globally. 
Allow the team to develop with VS 16.9.0
This is a temporary mitigation to get unstuck. It comes with the understanding that we'll actually evaluate and maybe fix these issues going forward.
> chore: Suppress warnings that VS 16.9.0 is suddenly generating

- build/NetStandardRelease.targets
- src/Actions/Attributes/InteractionLevelAttribute.cs
- src/Core/Attributes/PatternEventAttribute.cs
- src/Core/Attributes/PatternMethodAttribute.cs
- src/Rules/RuleInfo.cs
PR #529 disabled many warnings. This PR reenables the [CA1813 warning, which catches unsealed custom attributes](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1813). I sealed our custom attributes, which isn't a problem because they're not inherited from anywhere.
Reenabling suppressed warnings.
I considered suppressing these errors individually, but the changes made sense to me. 
> chore: Enable + fix CA1813 warnings by sealing custom attributes

- build/NetStandardRelease.targets
- src/CLI/OutputGenerator.cs
- src/CLI/Program.cs
PR #529 disabled many warnings. This PR reenables the [IL3000 warning](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/il3000), which calls out a possible error if shipping as a single file executable. We don't ship this way, so we don't _need_ to change any code. However, the suggested change made sense in one place, since we were doing extra work to get a directory that is available in a less expensive way.
Reenabling suppressed warnings.
Tested by running locally and ensuring that the third party notices file displays as expected.
> chore: Enable and address IL3000 warnings

- src/Desktop/UIAutomation/DesktopElementHelper.cs
While addressing some analyzer issues in Axe.Windows, I realized that the following methods (and their backing code) in https://github.com/microsoft/axe-windows/blob/main/src/Desktop/UIAutomation/DesktopElementHelper.cs are not used anywhere in Axe.Windows, and should be migrated into AIWin:
`SetCorePropertiesList`
`GetCorePropertiesList`
`GetDefaultCoreProperties`
After talking with @jalkire, we've chosen the following plan of action:
1. Give AIWin its own implementation of this functionality (https://github.com/microsoft/accessibility-insights-windows/pull/1081)
2. Remove the code from Axe.Windows (this PR). 
I opportunistically changed the input parameters to the remaining functions from List`<int>` to `IEnumerable<int>`. Existing code will just work and we'll have a slightly cleaner …
> chore: Tidy things up in DesktopElementHelper

- src/Core/Enums/RuleId.cs
- src/Core/Misc/ExtensionMethods.cs
- src/Rules/Library/FrameworkDoesNotSupportUIAutomation.cs
- src/Rules/Resources/Descriptions.Designer.cs
- src/Rules/Resources/Descriptions.resx
- src/Rules/Resources/HowToFix.Designer.cs
- src/Rules/Resources/HowToFix.resx
- src/RulesTest/Library/FrameworkDoesNotSupportUIAutomationTests.cs
- src/RulesTest/Library/FrameworkDoesNotSupportUIAutomationUnitTests.cs
Issue #554 requests a way to warn users if they're using a framework that doesn't support UIA. We don't yet have a good way to do this in live mode, but a first step is to add an automated check that triggers an error based on the Windows class name. So far, the cases we've encountered are Win32 frameworks that return class names of `SunAwtFrame` or `SunAwtDialog`. Other classes could exist, so we've opted to raise the error for any Win32 object with a reported ClassName of `SunAwt*`. We use a case-sensitive regular expression here.
Issue #554 
The HowToFix text may be a little too blunt. It says "Switch your application to a framework that supports UI Automation.". I'm open to gentler ways to express this sentiment of "Sorry, you chose the wrong framework".
> fix: Add unsupported framework rule

- src/CLI/IOptions.cs
- src/CLI/IScanDelay.cs
- src/CLI/Options.cs
- src/CLI/OptionsEvaluator.cs
- src/CLI/OutputGenerator.cs
- src/CLI/Program.cs
- src/CLI/README.MD
- src/CLI/ScanDelay.cs
- src/CLITests/OptionsEvaluatorUnitTests.cs
- src/CLITests/OptionsUnitTests.cs
- src/CLITests/OutputGeneratorUnitTests.cs
- src/CLITests/ScanDelayUnitTests.cs
The current CLI doesn't provide a way to scan transient controls. This PR adds the ability to delay up to 60 seconds to allow the user to get the app UI into the correct configuration for scanning.
I needed this ability for testing #561, then realized that it might be useful in general.
To facilitate unit testing, I implemented the 1 second delay via an `Action` that gets passed in from the Program. 
I changed `OutputGeneratorUnitTests` to use a test fixture. I was going to have to modify the constructor anyway, so I just went ahead and moved to a test fixture while I was at it.
> chore: Add delayed triggering to CLI scanner

- src/ActionsTests/ActionsTests.csproj
- src/ActionsTests/Misc/ExtensionMethodsTests.cs
- src/AutomationTests/AutomationTests.csproj
- src/CLITests/CLITests.csproj
- src/CLITests/OptionsEvaluatorUnitTests.cs
- src/CLITests/OptionsUnitTests.cs
- src/CLITests/OutputGeneratorUnitTests.cs
- src/CLITests/ProcessHelperUnitTests.cs
- src/CLITests/ScanDelayUnitTests.cs
- src/CLITests/TextWriterVerifier.cs
- src/CoreTests/CoreTests.csproj
- src/CoreTests/Results/ScanMetaInfoTests.cs
- src/CoreTests/Types/ControlTypesTests.cs
- src/CoreTests/Types/HeadingLevelTypeTests.cs
- src/CoreTests/Types/PatternTypesTests.cs
- src/CoreTests/Types/PropertyTypesTests.cs
- src/CoreTests/Types/TypeBaseTests.cs
- src/DesktopTests/ColorContrastAnalyzer/ImageTests.cs
- src/DesktopTests/DesktopTests.csproj
- src/DesktopTests/Styles/StyleIdTests.cs
- src/DesktopTests/Types/TextAttributeTemplateTests.cs
- src/DesktopTests/Utility/SupportedEventsTests.cs
- src/OldFileVersionCompatibilityTests/OldFileVersionCompatibilityTests.csproj
- src/RuleSelectionTests/ReferenceLinksTests.cs
- src/RuleSelectionTests/RuleSelectionTests.csproj
- src/SystemAbstractionsTests/MicrosoftUnitTests.cs
- src/SystemAbstractionsTests/SystemAbstractionsTests.csproj
- src/SystemAbstractionsTests/SystemUnitTests.cs
- src/TelemetryTests/TelemetryTests.csproj
- src/Win32Tests/Win32Tests.csproj
If you use the IDE to add a new test to one of our test projects, the test class ends up in a different namespace that other test classes in that folder. In addition, our current test namespaces are very inconsistent. This PR normalizes the namespaces and ensures that IDE-added classes follow the same pattern.
Make it easier to work with tests (both creating and viewing the results) in the IDE.
To test this, I added a new test class to each test assembly and confirmed that the new tests get added in the correct namespace. I never committed these files. I also broke up the commits per project, in case there's any desire to review these individually.
> chore: Normalize test namespaces

- src/Rules/Library/BoundingRectangleCompletelyObscuresContainer.cs
- src/RulesTest/Library/BoundingRectangleCompletelyObscuresContainerTest.cs
Address [BUG] ComboBox "An element's BoundingRectangle must not obscure its container element" · Issue #540
The light dismiss button is not intended to ever have focus and has little to no value for magnification users. It is also designed specifically to eclipse its parent window. Therefore, we will not check for BoundingRectangleCompletelyObscuresContainer on the light dismiss button.
> Fix: Issue 540

- src/props/version.props
- thirdpartynotices.html
This tweaks the wording of the placeholder to better reflect both the name of the file (thirdpartynotices.html instead of NOTICES.html) and the name of the pipeline (Axe.Windows instead of Accessibility Insights).
Accuracy is nice, even in a placeholder
> chore: Tweak placeholder

- src/AutomationTests/AutomationIntegrationTests.cs
- src/AutomationTests/OutputFileHelperUnitTests.cs
- src/CLITests/OptionsUnitTests.cs
- src/CLITests/OutputGeneratorUnitTests.cs
- src/Core/Bases/A11yPattern.cs
- src/Core/Bases/A11yPatternProperty.cs
- src/Core/Bases/A11yProperty.cs
- src/Core/Types/PatternType.cs
- src/Core/Types/PlatformPropertyType.cs
- src/CurrentFileVersionCompatibilityTests/Assert.cs
- src/Desktop/Styles/AnimationStyle.cs
- src/Desktop/Styles/BulletStyle.cs
- src/Desktop/Styles/CapStyle.cs
- src/Desktop/UIAutomation/DesktopElement.cs
Specify CultureInfo.InvariantCulture when rendering strings.
This is part of the GlobalReadiness work for the compliance feature. Only 1 change (called out in the code) is likely to have any real impact to the shipping code.
> chore: Specify culture invariant

- src/Actions/Trackers/BaseTracker.cs
- src/Actions/Trackers/FocusTracker.cs
- src/Actions/Trackers/MouseTracker.cs
MouseTracker.cs and FocusTracker.cs have some commonality in how they remember the selected element, but different code to implement it. This does the following:
* It brings the common code into a single location
* It allows the fields that track the selected state to become private instead of internal
* It converts some code from `condition == false` to `!condition`, which is handy for long lines
* It removes some unneeded code from MouseTracker (one check was performed twice, and we needlessly set `element` to null at the end)
Improved clarity and encapsulation. I had to debug the MouseTracker code today and it took longer than it should have to discern the intent of the code.
I considered renaming the now-private fields in BaseTracker to the underscore syntax, but thought it would be …
> chore: minor refactor of how trackers remember selection

- src/Desktop/UIAutomation/CustomObjects/Config.cs
- src/Desktop/UIAutomation/CustomObjects/CustomProperty.cs
- src/DesktopTests/UIAutomation/CustomObjects/ConfigTests.cs
This PR adds classes and unit tests for reading and validating custom UIA properties defined in JSON according to the specification defined in #587.
Part of feature 1845247 (internal access required to view).
Later PRs to handle the "enum" type, custom property registration, and data rendering.
This PR assumes that a non-empty "properties" collection will *always* be defined. This might not be the case if custom annotations/patterns are later added, so this constraint may need to be relaxed later (and `EmptyConfigTest` possibly updated to reflect this).
> feat(custom-uia): Load and validate custom properties from disk

- src/Desktop/Desktop.csproj
- src/Desktop/UIAutomation/CustomObjects/Registrar.cs
- src/DesktopTests/UIAutomation/CustomObjects/RegistrarTests.cs
Consume an interop assembly from a NuGet package. Includes a class that calls into the interop, just as a POC. We embed the interop so we don't change our set of files, and unit tests exercise the interop and ensure that it works as expected, including proper disposal of the `CUIAutomationRegistrar` object.
Provide a sustainable way to consume the needed interop from a NuGet package. This Interop is MIT licensed and comes from https://github.com/FlaUI/UIAutomation-Interop. It's been published 4 times since 2019, so it's reasonably well supported (and we could incorporate it into our repo should we ever have a need).
> chore: Add Interop.UIAutomationCore from NuGet package

- src/Desktop/UIAutomation/CustomObjects/Converters/BoolTypeConverter.cs
- src/Desktop/UIAutomation/CustomObjects/Converters/DoubleTypeConverter.cs
- src/Desktop/UIAutomation/CustomObjects/Converters/ElementTypeConverter.cs
- src/Desktop/UIAutomation/CustomObjects/Converters/ITypeConverter.cs
- src/Desktop/UIAutomation/CustomObjects/Converters/IntTypeConverter.cs
- src/Desktop/UIAutomation/CustomObjects/Converters/PointTypeConverter.cs
- src/Desktop/UIAutomation/CustomObjects/Converters/StringTypeConverter.cs
- src/Desktop/UIAutomation/CustomObjects/CustomProperty.cs
- src/DesktopTests/UIAutomation/CustomObjects/Converters/BoolConverterTests.cs
- src/DesktopTests/UIAutomation/CustomObjects/Converters/DoubleConverterTests.cs
- src/DesktopTests/UIAutomation/CustomObjects/Converters/ElementConverterTests.cs
- src/DesktopTests/UIAutomation/CustomObjects/Converters/IntConverterTests.cs
- src/DesktopTests/UIAutomation/CustomObjects/Converters/PointConverterTests.cs
- src/DesktopTests/UIAutomation/CustomObjects/Converters/StringConverterTests.cs
Repeatedly checking the JSON type string (`CustomProperty.DataType`) at registration and runtime is expensive, and the `enum` type requires special handling. This PR therefore adds a new `iTypeConverter` interface and `TypeConverter` classes which encapsulate type information for custom properties and streamline rendering.
Part of feature 1845247 (internal access required to view).
* The `enum` type is out-of-scope for this PR.
* Commit 1bf2a0c922192f65d4a45611042beec7e6f9a468 (removal of `UnderlyingUIAType` property used to aid registration) to be reverted after merge of #592 (in a subsequent PR).
> feat(custom-uia): add "type converters" for rendering and registration

- src/Desktop/Desktop.csproj
#592 broke the signed build because the assembly from the [Interop.UIAutomationCore](https://www.nuget.org/packages/Interop.UIAutomationCore/) package is not StrongName signed. This PR simply changes to the [Interop.UIAutomationCore.Signed](https://www.nuget.org/packages/Interop.UIAutomationCore.Signed/) package, which is a StrongName signed version of the same assembly. The assembly itself is still named Interop.UIAutomationCore, so the only required change is to update the package reference. I queued a [validation build](https://mseng.visualstudio.com/1ES/_build/results?buildId=15448326&view=results), which completed successfully.
Broken builds are very bad
> fix: use StrongName-signed interop

- src/Core/CustomObjects/Config.cs
- src/Core/CustomObjects/CustomProperty.cs
- src/Core/Enums/CustomUIAPropertyType.cs
- src/CoreTests/CustomObjects/ConfigTests.cs
- src/CoreTests/CustomObjects/CustomPropertyTests.cs
This PR removes the `Config.Validate()` and `CustomProprty.Validate()` methods, instead validating at the attribute level. It also relaxes the requirement for the JSON file to have custom properties, or any contents at all, defined as this may be useful for follow-up work on annotations/patterns. `DataType` has been renamed `ConfigType` (as it is the type from the user configuration) to distinguish it with a newly-added `Type` attribute containing an enum value kept in sync with the `ConfigType` property via setters. The new `Type` attribute should be used in calling code for faster performance, but `ConfigType` must be public for the benefit of Newtonsoft. Since Newtonsoft catches all exceptions thrown by calling code and re-throws its own, tests expecting our `InvalidDataException` were …
> feat(custom-uia): remove Validate() methods and perform field validation on property setters

- src/Core/Bases/A11yProperty.cs
- src/Core/CustomObjects/Converters/BoolTypeConverter.cs
- src/Core/CustomObjects/Converters/DoubleTypeConverter.cs
- src/Core/CustomObjects/Converters/ElementTypeConverter.cs
- src/Core/CustomObjects/Converters/IntTypeConverter.cs
- src/Core/CustomObjects/Converters/PointTypeConverter.cs
- src/Core/CustomObjects/Converters/StringTypeConverter.cs
- src/CoreTests/Bases/A11yPropertyTests.cs
- src/Desktop/UIAutomation/CustomObjects/Registrar.cs
- src/DesktopTests/UIAutomation/CustomObjects/RegistrarTests.cs
This PR integrates the `Desktop.UIAutomation.CustomObjects.Registrar` with `CustomProperty` and adds logic to `A11yProperty` to facilitate rendering.
Part of custom UIA extensions feature (internal access required to view).
`A11yProperty.ToString` uses a `switch` statement with hardcoded UIA property cases. Later refactoring might consider moving these to the newly added `TypeConverterMap` to make lookup more efficient/cleaner.
> feat(custom-uia): Finish the registrar and initial rendering support

- src/Actions/Actions/CaptureAction.cs
- src/Actions/Actions/CustomUIAAction.cs
- src/Automation/AxeWindowsActions.cs
- src/Automation/Data/Config.cs
- src/Automation/Interfaces/IAxeWindowsActions.cs
- src/Automation/SnapshotCommand.cs
- src/AutomationTests/SnapshotCommandUnitTests.cs
- src/Desktop/UIAutomation/CustomObjects/Registrar.cs
- src/Desktop/UIAutomation/DesktopElementHelper.cs
- src/DesktopTests/UIAutomation/CustomObjects/RegistrarTests.cs
This PR adds methods to the actions and automation layers to facilitate registration of custom UIA properties, and initial support for the output of custom properties in element snapshots.
Future PR to include the programmatic names in the output.
> feat(custom-uia): Expose registered custom properties in the actions and automation layers

- src/CLI/ScanRunner.cs
- src/Desktop/UIAutomation/CustomObjects/Registrar.cs
This PR fixes handling of the string and bool UIA types in `Registrar.GetUnderlyingUIAType` by providing the correct underlying types.
N/A
> feat(custom-uia): Fix type handling for String and Point

- src/CLI/IOptions.cs
- src/CLI/Options.cs
- src/CLI/OptionsEvaluator.cs
- src/CLI/Resources/OptionsHelpText.Designer.cs
- src/CLI/Resources/OptionsHelpText.resx
- src/CLI/ScanRunner.cs
- src/CLITests/OptionsUnitTests.cs
This PR adds an option to the CLI allowing users to scan a process with custom UIA configuration.
Connection with Accessibility Insights to follow in a subsequent PR.
> feat(custom-uia): Add a command-line option to enable scanning with custom UIA extensions

- src/CLI/CLI.csproj
- src/CLI_Full/CLI_Full.csproj
The signed binary check is unhappy about Interop.UIAutomationCore.dll. We _could_ sign it with our 3rd party cert and ship it with our binaries, but since we embed the assembly in the [Desktop assembly](https://github.com/microsoft/axe-windows/blob/main/src/Desktop/Desktop.csproj#L48), there's no need to ship it.
Don't ship unsigned files
> fix: Delete Interop.UIAutomationCore.dll from CLI projects

- src/CLI/CLI.csproj
- src/CLI_Full/CLI_Full.csproj
#603 didn't work, but we didn't learn that until after it had gone through the signed pipeline. We're reverting the change and taking a different approach that will keep the interop from breaking the MSI install.
This will not be needed with the new approach.
> chore: Revert #603

- src/AxeWindows.sln
- src/Desktop/Desktop.csproj
- src/DesktopTests/DesktopTests.csproj
- src/Interop/ForceInclusion.cs
- src/Interop/Interop.csproj
This PR adds an interop dummy project containing the `Interop.UIAutomationcore.signed` package to facilitate embedding Interop.UIAutomationCore.dll (which we get through a NuGet package) into Axe.Windows.Desktop.dlll, instead of shipping it as a standalone assembly.
> feat(custom-uia): Add interop project to facilitate embedding in release

- src/AxeWindows.sln
- src/CLI_Full/BuildNotes.md
- src/CLI_Full/CLI_Full.csproj
Fix resource binding issue in `CLI_Full` project. This fixes a bug introduced in #577, when hardcoded strings in CLI were replaced by resource strings, and CLI_Full got enough of the strings to compile but not enough to embed the resources into the compiled binary. Since there is no intended difference between the `AxeWindowsCLI.dll` files that get generated by `CLI` and `CLI_Full`, this change ensures that `CLI` builds before `CLI_Full`, then adds a post-build step to copy `AxeWindowsCLI.dll` from `CLI` to `CLI_Full`. Not necessarily the prettiest fix, but surprisingly effective. I also updated `BuildNotes.md` with this information and strengthened its warning about making changes in the `CLI_Full` project.
The `CLI_Full` package should work
I considered trying to modify …
> fix: Solve resource problem with CLI_Full project

- src/Actions/Actions/CustomUIAAction.cs
- src/Automation/AxeWindowsActions.cs
- src/Automation/SnapshotCommand.cs
This PR moves `CustomUIAAction` from `Axe.Windows.Actions.Actions` to `Axe.Windows.Actions`.
Consistency.
> feat(custom-uia): make namespacing for CustomUIAAction more consistent with other actions

- src/AutomationTests/AutomationIntegrationTests.cs
- src/Rules/Library/ControlShouldSupportTextPattern.cs
- src/RulesTest/Library/ControlShouldSupportTextPatternUnitTests.cs
As reported in #636, WinForms Edit controls don't support TextPattern. It's a known framework issue that we don't really expect app developers to try to fix. It's possible that a future .NET WinForms version might support this pattern, but there's no guarantee of _if_ or _when_ this might occur. To minimize noise, we've decided to exclude WinForms edit controls from this rule until a less noisy solution becomes available. 
Remove noise, address #636
> fix: Exclude WinForms edit control from ControlShouldSupportTextPattern rule

- src/Rules/PropertyConditions/ElementGroups.cs
- src/RulesTest/PropertyConditions/ElementGroupsTests.cs
As called out in #648, we should skip name checking of items inside a WPF CheckBox, since AT's will simply read the Name property of the CheckBox, which will be set either by the framework or overridden by the app developer.
Handle case identified in #648.
This is similar to #572, but handled differently. #572 changed the condition on a single rule, but this effectively causes us to ignore _all_ name-related rules within the scope of the fix. Happy to discuss pros & cons of the options, if desired.
> fix: Ignore names on WPF Text inside a CheckBox

- src/Desktop/ColorContrastAnalyzer/BitmapCollection.cs
Finish the change that was started with #469, then forgotten. This will merge only after https://github.com/microsoft/accessibility-insights-windows/pull/1245, which adds the corresponding change in AIWin, merges. There are no other supported callers of the `BitmapCollection` class.
We want to allow AIWin to experiment with different parameters to the color auto-detection algorithm, without requiring a re-release of Axe.Windows.
> chore: Remove legacy constructor for BitmapCollection

- src/CLI/Program.cs
- src/CLI/README.MD
When running the CLI, we use localized text for the fields that we control, but the fields for `--help` and `--version` are hardcoded:
```
AxeWindowsCLI 1.0.10
Copyright c 2020
--processid                Process Id
--processname              Process Name
--outputdirectory          Output directory
--scanid                   Scan ID
--verbosity                Verbosity level (Quiet/Default/Verbose)
--showthirdpartynotices    Display Third Party Notices (opens file in browser
without executing scan). If specified, all other
options will be ignored.
--delayinseconds           How many seconds to delay before triggering the
scan. Valid range is 0 to 60 seconds, with a
default of 0.
--customuia                The path to a configuration file specifying custom
UI Automation attributes
--help …
```
> feat(compliance-fall-21): Exclude non-localizable fields from CLI help output

- src/CI/CI.csproj
- src/CI/packages.config
- src/CLI_Installer/CLI_Installer.wixproj
- src/CLI_Installer/packages.config
Dependabot PR #645 bumped the MicroBuild version in all of the new-format projects, but we failed to upgrade the project that generates an MSI file (the WiX project is incompatible with the new format, or else we would have changed this before). This PR changes the MicroBuild version in the MSI-related projects. Validation signed build (where MicroBuild really matters) is at https://dev.azure.com/mseng/1ES/_build/results?buildId=16433972&view=results
Use updated build package
> chore: Use latest MicroBuild package when building MSI-related projects

- docs/RulesDescription.md
- src/Rules/Resources/Descriptions.Designer.cs
- src/Rules/Resources/Descriptions.resx
Updates the error message as discussed in #653 
Addresses #653
N/A
> fix: Update misleading split button pattern error message

- src/Rules/Library/ControlShouldSupportExpandCollapsePattern.cs
- src/RulesTest/Library/ControlShouldSupportExpandCollapsePattern.cs
In win32 app, the SplitButton is implented using nested SplitButtons. Only the parent one implements the expand collapse pattern which is fine, however the child does not. This PR updates the rule to exclude direct SplitButton childrens of SplitButtons from the ExpandCollapsePatternRule.
Addresses #659 
N/A
> fix: Fix win32 SplitButton nesting leading to faulty expand collapse pattern rule errors

- src/CI/CI.csproj
Our NuGet signing recently broke without our realizing it. We think it occurred when moving to the new build pool. After some consultation with the experts, the suggestion was made to put our `SignNuGetPackage` definition after the import of the MicroBuild targets. Validation build is at https://dev.azure.com/mseng/1ES/_build/results?buildId=16654220&view=results
We need to be able to sign in order to release.
> chore: Fix NuGet package signing

- src/DesktopTests/ColorContrastAnalyzer/ImageTests.cs
- src/DesktopTests/DesktopTests.csproj
#668 had a couple of errors:
1. The resource paths for cleanup omitted the `TestImages\` prefix
2. One test ddn't include the colors for validation
This PR fixes both oversights.
Complete and accurate tests
> chore: Corrections to #668

- src/Automation/DisplayStrings.resx
- src/Automation/Interfaces/ITargetElementLocator.cs
- src/Automation/Resources/ErrorMessages.Designer.cs
- src/Automation/Resources/ErrorMessages.resx
- src/Automation/SnapshotCommand.cs
- src/Automation/TargetElementLocator.cs
- src/AutomationTests/SnapshotCommandUnitTests.cs
- src/Desktop/UIAutomation/A11yAutomation.cs
This change refactors TargetElementLocator so that it returns all root-level window elements for a given process id. The scanner itself still only scans the first window returned, which is the same as the existing behavior. 
This commit partially addresses  #665.
This change was kept as small as possible. But it should pave the way for a change where the user can specify that all root-level windows are scanned.
> [feat(scan-multiple-windows)] Add code to scan multiple root-level windows

- src/CLI/OutputGenerator.cs
- src/CLI/Resources/DisplayStrings.Designer.cs
- src/CLI/Resources/DisplayStrings.resx
- src/CLITests/OutputGeneratorUnitTests.cs
- src/Core/Results/RuleResult.cs
- src/Core/Results/ScanResult.cs
- src/RuleSelection/RuleRunner.cs
- src/Rules/RuleInfo.cs
- src/RulesTest/RuleRunnerTests.cs
We're adding `RuleInfo.FrameworkIssueLink` to identify rules with known framework problems. If a rule sets this field, that serves as an indication that _every_ element that meets the condition of the rule is potentially caused by that known framework issue. The link will go to a documentation page that outlines how to determine if the app is using a framework that has this problem. Where possible, that page will also include links to issues in public GitHub repos, so teams already have an external bug to reference and possibly upvote.
Needed for framework issue logic feature
This PR is purely infrastructure and changes no rules. The unit test simulate rules with known issues. I also tested it locally by adding some links to rules and confirming that they appear in the a11ytest file and …
> feat(framework-issues-logic): Infrastructure for framework issue links

- src/AutomationTests/AutomationIntegrationTests.cs
- src/Rules/Library/ControlShouldSupportSetInfoWPF.cs
- src/Rules/Library/EdgeBrowserHasBeenDeprecated.cs
- src/Rules/Library/FrameworkDoesNotSupportUIAutomation.cs
- src/RulesTest/Library/ControlShouldSupportSetInfoWPFTest.cs
- src/RulesTest/Library/EdgeBrowserHasBeenDeprecated.cs
- src/RulesTest/Library/FrameworkDoesNotSupportUIAutomationTests.cs
Add aka.ms links for our existing rules where we want to document framework-related issues (does do not yet exist, so the aka.ms links resolve to our docs.microsoft.com landing page).
Part of framework issues feature
The links will be redirected (outside of code) once the documentation pages exist
> feat(framework-issues-logic): Add framework issue links

- docs/RulesDescription.md
I forgot to include this in #697, which changed `ControlShouldSupportSetInfoWPF` from Warning to Error
Keep docs current
> feat(framework-issues-logic): Update RulesDescription.md

- src/Actions/Misc/ExtensionMethods.cs
- src/Core/Enums/RuleId.cs
This PR removes unused RuleId values, including some that were artifacts of the legacy scan engine that was removed in 2019. It also corrects some comments that refer to the old scan engine. Finally, since all of the RuleId values now deal with `Axe.Windows.Rules`, there is no need to have comments that were originally intended to help to categorize the rules.
Code hygiene
> chore: Remove unused RuleId values

- docs/RulesDescription.md
- src/Core/Enums/RuleId.cs
- src/Rules/Library/BoundingRectangleNotNull.cs
- src/Rules/Library/BoundingRectangleNotNullListViewXAML.cs
- src/Rules/Library/BoundingRectangleNotNullTextBlockXAML.cs
- src/Rules/PropertyConditions/ElementGroups.cs
- src/RulesTest/Library/BoundingRectangleNotNullListViewXAMLTest.cs
- src/RulesTest/Library/BoundingRectangleNotNullTest.cs
- src/RulesTest/Library/BoundingRectangleNotNullTextBlockXAMLTest.cs
- src/RulesTest/PropertyConditions/ElementGroupsTests.cs
This PR splits the `BoundingRectangleNotNull` into 3 rules:
1. `BoundingRectangleNotNullListViewXAML` scans on-screen XAML List elements. The docs will eventually reference https://github.com/microsoft/microsoft-ui-xaml/issues/1979 and https://github.com/microsoft/microsoft-ui-xaml/issues/2036
2. `BoundingRectangleNotNullTextBlockXAML` scans on-screen XAML Hyperlink elements hosted in a Text element. The docs will eventually reference https://github.com/microsoft/microsoft-ui-xaml/issues/5666
3. The `BoundingRectangleNotNull` continues as before, although it excludes controls covered by the new rules
The new rule names are geared toward the XAML control names (`ListView` instead of `List` and `TextBlock` instead of `Text`). Failures of `BoundingRectangleNotNullTextBlockXAML` will be …
> feat(framework-issues-logic): BoundingRectangleNotNull*

- docs/RulesDescription.md
- src/AutomationTests/AutomationIntegrationTests.cs
- src/Core/Enums/RuleId.cs
- src/Rules/Library/ControlShouldSupportTextPattern.cs
- src/Rules/Library/ControlShouldSupportTextPatternEditWinform.cs
- src/Rules/PropertyConditions/ElementGroups.cs
- src/RulesTest/Library/ControlShouldSupportTextPatternEditWinform.cs
- src/RulesTest/PropertyConditions/ElementGroupsTests.cs
This rule `ControlShouldSupportTextPatternEditWinform` splits off from [ControlShouldSupportTextPattern](https://github.com/microsoft/axe-windows/blob/main/src/Rules/Library/ControlShouldSupportTextPattern.cs#L40) when Framework is `WinForm` and `ControlType` is `Edit`. 
We found that the `ControlShouldSupportTextPattern` already excludes the conditions (WinForm & Edit) and did not feel the original rule nor its tests required updates to prevent overlap:
https://github.com/microsoft/axe-windows/blob/d269eb404592121dc797f42dc1f694dc932ecd7e/src/Rules/Library/ControlShouldSupportTextPattern.cs#L32-L43
> feat(framework-issues-logic): Add rule `ControlShouldSupportTextPatternEditWinform`

- docs/RulesDescription.md
- src/Core/Enums/RuleId.cs
- src/Rules/Library/ClickablePointOnScreenWPF.cs
- src/RulesTest/Library/ClickablePointOnScreen.cs
- src/RulesTest/Library/ClickablePointOnScreenWPFTests.cs
Add framework-specific rule to point people to https://github.com/dotnet/wpf/issues/4631. We originally scoped this feature to ListViewItems, but upon further digging, it applies more broadly. The [fix](https://github.com/dotnet/wpf/pull/5126/files) actually changes the base [AutomationPeer](https://github.com/dotnet/wpf/blob/main/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Automation/Peers/AutomationPeer.cs), so it will impact _all_ WPF control types. Based on that, the new rule is called `ClickablePointOnScreenWPF`. The framework issue link still says ListView but we can change that separately since it will also impact the docs.
Framework issues feature.
> feat(framework-issues-logic): Add WPF-specific IsClickablePointOnScreen rule

- src/RulesTest/MonsterTest.cs
`MonsterTest.cs` is an old test that hasn't really been maintained. It predates the rule-specific unit tests and may no longer be needed. It seems like it's time to either get update it or get rid of it. This is an attempt to update it and streamline future maintenance. It keeps exactly the same input files, but it refactors the tests as follows:
1. To reduce churn and noise, rules are assumed to be `EvaluationCode.NotApplicable` unless explicitly specified. This makes the tests significantly smaller.
2. If new rules are applicable to one of the tests, the test will fail until the expected results have been updated. This prevents new rules from being added without updating the test.
3. Tests will fail if an expected rule is specified more than once in a test.
4. The checks for failures …
> chore: Refactor MonsterTest for better coverage & less churn

- src/CLI/Program.cs
- src/CLI/ReturnValueChooser.cs
- tools/scripts/verification.scripts/ValidateCLI.ps1
The CLI has recently regressed in 2 ways:
1. It is throwing an Exception when no scan is run (for example, just display the help). This occurs as the process exits, so scans complete as expected but the return code indicates failure. This regressed in #682 when a null check was dropped.
2. When displaying the help, it displays twice. This may have come from a recent change in CommandLineParser, but I haven't tried to pin it down.
These are both recent regressions that we didn't catch in the last validation pass.
CLI usability
It would be awesome if the CLI tests could have detected the Exception, but I'm unsure of the best way to add that ability.
> fix: CLI is throwing an exception, displaying help twice

- build/signedbuild.yml
The `SystemAbstractions` assembly was added in #108, but the BinSkim config wasn't updated to scan the new assembly. This PR corrects that oversight.
Conform to shipping requirements
> fix: Run BinSkim on the SystemAbstractions assembly

- build/NetStandardRelease.targets
- docs/AutomationReference.md
- src/Actions/Actions.csproj
- src/Automation/Automation.csproj
- src/CI/CI.csproj
- src/Core/Core.csproj
- src/Desktop/Desktop.csproj
- src/InteropDummy/InteropDummy.csproj
- src/RuleSelection/RuleSelection.csproj
- src/Rules/Rules.csproj
- src/SystemAbstractions/SystemAbstractions.csproj
- src/Telemetry/Telemetry.csproj
- src/Win32/Win32.csproj
In #719, we enabled SourceLink support in the assemblies, but users still had to enable NuGet symbol servers to make things work as expected. This PR embeds the PDB files directly into the assemblies, instead of putting them into a `.snupkg` file. The net result is:
1. Size of all DLLs increases from about 1.9MB to 2.1MB
2. When debugging, the symbols can be instantly loaded into memory (no delay from fetching from the NuGet packages)
3. The CLI's also now include PDB data (we excluded it before since they has no corresponding `.snupkg` file
I validated by building the signed pipeline, downloading the `.nupkg` file from the [artifacts](https://dev.azure.com/mseng/1ES/_build/results?buildId=17676375&view=artifacts&pathAsName=false&type=publishedArtifacts), and consuming them locally in …
> chore: Embed symbols in assemblies

- src/Core/Enums/RuleId.cs
- src/Core/Misc/BoundedCounter.cs
- src/Core/Misc/ExtensionMethods.cs
- src/Core/Types/PropertyType.cs
- src/Core/Types/TypeBase.cs
This PR fixes various spelling and typographical errors found in strings and comments in the `Core` namespace.
> chore: Fix various spelling and typographical errors in source code comments and strings (Core namespace)

- src/Automation/Data/OutputFile.cs
- src/Automation/ReadMe.md
- src/AutomationTests/OutputFileHelperTests.cs
- src/Win32/Win32Helper.cs
This PR fixes various spelling and typographical errors found in strings and comments in the `Automation` and `Win32` namespaces.
> chore: Fix various spelling and typographical errors in source code comments and strings (Automation and Win32 namespaces)

- src/CoreTests/Resources/A11yElementTest.hier
- src/CoreTests/Resources/A11yPatternTest.hier
- src/CoreTests/Resources/A11yPropertyTest.hier
This PR fixes various spelling and typographical errors found in strings and comments in the `CoreTests` namespace. I'm a little nervous about these (I changed several occurrences of rectagle -> rectangle using find/replace, for instance) but am hoping that this doesn't break unit or system tests/these misspellings aren't intentional!
> chore: Fix various spelling and typographical errors in source code comments and strings (CoreTests namespace)

- src/UnitTestSharedLibrary/Snapshots/MonsterDataGrid.snapshot
- src/UnitTestSharedLibrary/Snapshots/MonsterEdit.snapshot
- src/UnitTestSharedLibrary/Snapshots/MonsterListView.snapshot
- src/UnitTestSharedLibrary/Snapshots/Taskbar.snapshot
- src/UnitTestSharedLibrary/Utility.cs
This PR fixes various spelling and typographical errors found in strings and comments in the `UnitTestSharedLibrary` namespace. Once again, a little worried that I've inadvertantly broken system tests that depend on the misspellings.
> chore: Fix various spelling and typographical errors in source code comments and strings (UnitTestSharedLibrary namespace)

- src/Desktop/UIAutomation/A11yAutomation.cs
As outlined in #730 , scanning UWP apps was broken when we switched how we scan children nodes in #676. This PR based on https://github.com/DaveTryon/axe-windows/pull/45 fixes this by manually walking the UIA tree. In my personal testing, this change did not seem to create a big performance difference (if one at all) when running the interaction tests.
Addresses issue #730 
Ideally, we would want a test with a UWP being scanned, however due to the complexity of installing the app on the remote machine and then running it, I'm fairly sure this would not be that easy. This issue of testing a UWP app was also discussed in another issue (can't remember which :/) with the same outcome.
> fix: Fix process UIA scanning to also work on UWP apps by walking UIA tree manually

- docs/RulesDescription.md
- src/Rules/PropertyConditions/ElementGroups.cs
- src/Rules/PropertyConditions/Relationships.cs
- src/Rules/Resources/Descriptions.Designer.cs
- src/Rules/Resources/Descriptions.resx
- src/Rules/Resources/HowToFix.Designer.cs
- src/Rules/Resources/HowToFix.resx
- src/RulesTest/PropertyConditions/RelationshipsTests.cs
This PR fixes various spelling and typographical errors found in strings and comments in the `Rules` namespace.
> chore: Fix various spelling and typographical errors in source code comments and strings (Rules namespace).

- src/CLI/Resources/DisplayStrings.Designer.cs
- src/CLI/Resources/DisplayStrings.resx
Quotes are escaped differently in resource files than they are in code files, so when string resources were copied from code to a resource file, we ended up with an extra backslash character in the output.
Output before the change--note the extra backslash just before each quote:
```
C:\demo>axewindowscli --showthirdpartynotices
Axe.Windows Accessibility Scanner CLI (version 1.1.7)
Opening Third Party Notices in default browser. If this fails, manually open \"c:\program files (x86)\AxeWindowsCLI\1.1.7\thirdpartynotices.html\"
C:\demo>axewindowscli --processname notepad++
Axe.Windows Accessibility Scanner CLI (version 1.1.7)
Scan Target: Process Name = notepad++, Process ID = 15228
3 errors were found
Results were written to \"C:\demo\AxeWindowsOutputFiles\AxeWindows_22-08-17_10-47-23.71370 …
```
> fix: Remove incorrect escaping in CLI messaging

- src/CLI/README.MD
I noticed that the CLI's readme.md file was not as complete as it ought to be (it was last updated with version 1.0.8). Changes included:
- Include the help output from the current version (line breaks are different because of the presence of the `areMultipleScanRootsEnabled` parameter
- Bump the version so that it's in sync with the build version (see note under context)
- Remove superfluous `|` characters at start and stop of lines in the table that documents command line parameters
- Add documentation for the `areMultipleScanRootsEnabled` option
- Expand the explanation of the `customUia` note
The readme that ships in the product should be in sync with what the user encounters when running the product.
Q: Why update the build version to be in sync with `version.props`?
A: Ideally, the …
> chore: Refresh README that installs with CLI

- build/signedbuild.yml
The version of the ADO signing task that we've been using has been deprecated, causing our signed build to break. This simply bumps the task to the latest version. None of the parameters needed to be updated. Validation build is at https://dev.azure.com/mseng/1ES/_build/results?buildId=18305230&view=results. A warning was generated but it seems to have been a transient issue that went away on retry.
We need to be able to sign to ship.
> chore: Use newer signing plugin

- src/Actions/Actions/DataManager.cs
- src/Actions/Actions/SetDataAction.cs
- src/ActionsTests/Actions/DataManagerTests.cs
This improves the `DataManager` class as follows as we prepare for an async API:
1. `DataManager.GetDefaultInstance` used a non-concurrent `Dictionary` to allow for side-by-side instances of `DataManager`, even though the code _never_ created anything but the default instance. This removes the `Dictionary`. Future changes will create separate `DataManager` objects that will be explicitly passed into API calls.
2. `DataManager.Dispose` was never implemented beyond the boilerplate, so it was essentially a NOP. The `Dispose` method will be a important part of our data cleanup in the async world, so we need a proper implementation. We'll be cleaning up UIA objects, so the finalizer is needed (the boilerplate added it commented)
3. `DataManager.RemoveDataContext` had a documented parameter …
> feat(async-api): Improve DataManager

- src/Actions/Actions/CaptureAction.cs
- src/ActionsTests/Actions/CaptureActionTests.cs
- src/Desktop/UIAutomation/TreeWalkers/TreeWalkerDataContext.cs
- src/Desktop/UIAutomation/TreeWalkers/TreeWalkerForTest.cs
- src/DesktopTests/UIAutomation/TreeWalkerForTestTests.cs
- src/DesktopTests/UIAutomation/TreeWalkers/TreeWalkerForTestTests.cs
- src/RuleSelection/RuleRunner.cs
- src/Rules/RuleRunner.cs
- src/Rules/Rules.cs
- src/RulesTest/MonsterTest.cs
- src/RulesTest/RuleRunnerTests.cs
Adding cancellation logic to two of the most time intensive operations performed during scanning, the tree walker and rule runner. 
Based on docs/ discussion online, it appears that the norm is to use `ThrowIfCancellationRequested` to check the cancellation token throughout the async call. This throws a `OperationCanceledException`, which will be wrapped in an `AggregateException` once these methods are wrapped in a task.
Also added bare minimum test coverage for cancellation in TreeWalkerForTest, which previously did not have any unit tests. 
Part of [1986365](https://mseng.visualstudio.com/1ES/_workitems/edit/1986365) to enable cancellation
This is the first in what will be multiple PRs to add cancellation tokens. In the future we will need to add the logic to pass the cancellation …
> feat(async-api): Add cancellation token for TreeWalker and RuleRunner

- src/Automation/Scanner.cs
- src/Automation/SnapshotCommand.cs
- src/AutomationTests/AutomationIntegrationTests.cs
Add test coverage for new `ScanAsync` method added in https://github.com/microsoft/axe-windows/commit/bb5e9efe4cd0a6e21e37af02592d3920143b1f0c.
Add test coverage for new API
> feat(async-api): Add async integration test coverage

- src/Automation/Data/Config.cs
- src/Automation/SnapshotCommand.cs
- src/AutomationTests/AutomationIntegrationTests.cs
- src/AutomationTests/ConfigTests.cs
- src/AutomationTests/SnapshotCommandTests.cs
- src/CLI/IOptions.cs
- src/CLI/Options.cs
- src/CLI/OptionsEvaluator.cs
- src/CLI/README.MD
- src/CLI/Resources/OptionsHelpText.Designer.cs
- src/CLI/Resources/OptionsHelpText.resx
- src/CLI/ScanRunner.cs
- src/CLITests/OptionsEvaluatorTests.cs
This is a BREAKING change to the CLI. Scripts that called the CLI with the --aremultiplescanrootsenabled  parameter will reject the arguments. To be fair, though, we know of nobody who uses this parameter. The only known case of scanning multiple top-level windows goes directly to the Automation API and does not use the CLI.
When we added multiple scan roots, we jumped through some hoops to ensure it would be non-breaking. The 2.0 Automation API is a breaking change, so we've decided to simplify multiple scan roots. They're always enabled and currently have no means of disabling them. If requested, it's easy to add at a later time.
One other change in behavior to call out: For anyone who used the Automation API and specified multiple root window support, scans would generate an …
> feat(async-api): Multiple scan roots are always enabled

- build/signedbuild.yml
CodeQL analysis should be available via injection in default build pipelines. This PR sets the flag that is supposed to enable it. An intermediate commit included explicit tasks, which are supposedly not necessary in the default branch. We'll find out after merging this and triggering a build.
New security requirement
This does not yet enable TSA uploads. That may occur at a later time
> chore: Enable CodeQL analysis

- src/Actions/Actions/CaptureAction.cs
- src/Actions/Actions/GetDataAction.cs
- src/Actions/Actions/SelectAction.cs
- src/Actions/Contexts/DefaultActionContext.cs
- src/Actions/Contexts/IActionContext.cs
- src/Actions/Contexts/ScopedActionContext.cs
- src/Actions/Trackers/BaseTracker.cs
- src/Actions/Trackers/FocusTracker.cs
- src/Actions/Trackers/MouseTracker.cs
- src/Actions/Trackers/TreeTracker.cs
- src/ActionsTests/Actions/CaptureActionTests.cs
- src/ActionsTests/Contexts/DefaultActionContextTests.cs
- src/ActionsTests/Contexts/ScopedActionContextTests.cs
- src/Automation/TargetElementLocator.cs
- src/Core/Bases/A11yProperty.cs
- src/Desktop/Resources/ErrorMessages.Designer.cs
- src/Desktop/Resources/ErrorMessages.resx
- src/Desktop/UIAutomation/A11yAutomation.cs
- src/Desktop/UIAutomation/DesktopDataContext.cs
- src/Desktop/UIAutomation/DesktopElementExtensionMethods.cs
- src/Desktop/UIAutomation/DesktopElementHelper.cs
- src/Desktop/UIAutomation/TreeWalkers/DesktopElementAncestry.cs
- src/Desktop/UIAutomation/TreeWalkers/TreeWalkerDataContext.cs
- src/Desktop/UIAutomation/TreeWalkers/TreeWalkerForLive.cs
- src/Desktop/UIAutomation/TreeWalkers/TreeWalkerForTest.cs
- src/DesktopTests/UIAutomation/DesktopDataContextTests.cs
- src/DesktopTests/UIAutomation/TreeWalkers/TreeWalkerForTestTests.cs
#757 set up separate data contexts, but it didn't go far enough. When testing, we realized that the `A11yAutomation` static class was still being shared across all of those data contexts, so the `IUIAutomation` object held within that class was also being shared between contextx. These changes break down as follows:
1. Update `A11yAutomation` to support multiple instances, with each instance having its own `IUIAutomation`.
2. Add an `A11yAutomation` object to `TreeWalkerDataContext`
3. Rename `TreeWalkerDataContext` to `DesktopDataContext`, move it one level up the directory structure
4. Add an `IActionContext` member in the `BaseTracker` class, so each tracker is bound to a context. In practice, these will always be the default contexts (they're not used while scanning), but it puts that …
> feat(async-api): Provide instanced IUIAUtomation objects

- src/Core/Bases/A11yProperty.cs
#770 calls out a potential isolation problem with the mix of CustomUIA and async scans. Upon further analysis, each scan registers its own set of CustomUIA properties and incorporates that in the properties requested from UIA, so our only risk for conflict is in rendering. The `A11yProperty` class maintains a mapping from system-assigned property ID's to an appropriate `TypeConverter`, and this mapping is not thread-safe. The simplest change we can make here is to replace the `Dictionary` with a `ConcurrentDictonary`, which gives us the thread safety that we need. As it turns out, the API's that we're currently calling on the `Dictionary` require no change for `ConcurrentDictionary`, so the change is trivial--just change the type.
One thing to note is that custom property ID's are issues …
> feat(async-api): Use ConcurrentDictionary for custom TypeConverter mapping

- docs/RulesDescription.md
- src/Rules/PropertyConditions/StringProperties.cs
- src/Rules/Resources/ConditionDescriptions.Designer.cs
- src/Rules/Resources/ConditionDescriptions.resx
We noticed that the description for the `LocalizedLandmarkTypeExcludesPrivateUnicodeCharacters` was malformed. It read:
The [StringProperty not set] property must not contain any characters in the private Unicode range.
It should read:
The LocalizedControlType property must not contain any characters in the private Unicode range.
Easy fix, just add the description to the property and rebuild RulesDescription.md
Docs should be correct
> chore: Fix malformed rule description

- src/Desktop/UIAutomation/A11yAutomation.cs
- src/Desktop/UIAutomation/TreeWalkers/DesktopElementAncestry.cs
- src/Desktop/UIAutomation/TreeWalkers/TreeWalkerForLive.cs
- src/Desktop/UIAutomation/TreeWalkers/TreeWalkerForTest.cs
Changes in #767 removed a parameter and from the public constructor of `DesktopElementAncestry` and its associated plumbing, since the field was never used in Axe.Windows. Unfortunately, AIWIn relies on this functionality [here](https://github.com/microsoft/accessibility-insights-windows/blob/main/src/AccessibilityInsights.SharedUx/Controls/TestTabs/TabStopControl.xaml.cs#L419). This PR restores the property with a tiny refactor to (hopefully) make the code clearer.
I've confirmed that AIWin builds correctly with this change
Part of async feature work
> feat(async-api): Restore old signature

- build/NetStandardRelease.targets
- build/signedbuild.yml
- src/Core/Core.csproj
- src/RuleSelection/RuleSelection.csproj
- src/Rules/Rules.csproj
This PR onboards to the microbuild loc plugin such that the projects that will need to be localized begin generating `localize/*/*.lce` files in the signed build output. These files will be picked up by the loc team for translation, and eventually the loc team will check .lcl files into this repo.
Test run with these changes: https://dev.azure.com/mseng/1ES/_build/results?buildId=18577457&view=results
See relevant files at `drop/src/{ projects that need to be localized }/bin/release/netstandard2.0/localize/*`.
This PR does not address 2 items: 
- Including the resulting loc files in signing. I added a TODO in the code to address this as well as created a user story: https://dev.azure.com/mseng/1ES/_workitems/edit/2002189
- Including the resulting loc files in the …
> feat(localization): Onboard to microbuild loc plugin

- src/Rules/Resources/ConditionDescriptions.resx
- src/Rules/Resources/Descriptions.Designer.cs
- src/Rules/Resources/Descriptions.resx
- src/Rules/Resources/ErrorMessages.resx
- src/Rules/Resources/HowToFix.Designer.cs
- src/Rules/Resources/HowToFix.resx
- src/Rules/Resources/LocalizedControlTypeNames.resx
This PR adds translator comments for each string in the resource files under the `Rules` directory. While at it, I also cleaned up and standardized a couple of messages.
Part of localization feature (internal access required to view).
Other namespaces to follow in subsequent PRs.
> feat(localization): Add translator comments for Rules namespace

- src/RuleSelection/Resources/DefaultGuidelineShortDescriptions.resx
- src/RuleSelection/Resources/DefaultGuidelineUrls.resx
- src/RuleSelection/Resources/ErrorMessages.resx
This PR adds translator comments for each string in the resource files under the `RuleSelection` directory.
Part of localization feature (internal access required to view).
Other namespaces to follow in subsequent PRs.
> feat(localization): Add translator comments for RuleSelection namespace

- src/Core/Resources/DisplayStrings.resx
- src/Core/Resources/ErrorMessages.resx
This PR adds translator comments for each string in the resource files under the `Core` directory.
Part of localization feature (internal access required to view).
Other namespaces to follow in subsequent PRs.
> feat(localization): Add translator comments for Core namespace

- build/NetStandardRelease.targets
- build/settings.targets
- build/signedbuild.yml
.resource.dll files were added to signed build output in https://github.com/microsoft/axe-windows/pull/779, but are not actually included in signing yet. This PR adds those files to `FilesToSign`. 
Test run with these changes: https://dev.azure.com/mseng/1ES/_build/results?buildId=18601521&view=results
Localization feature work
> feat(localization): Include .resource.dll files for signing

- src/Rules/Library/BoundingRectangleSizeReasonable.cs
- src/Rules/PropertyConditions/BoundingRectangle.cs
- src/RulesTest/Library/BoundingRectangleSizeReasonableTests.cs
Updating the BoundingRectangleReasonableSized rule to exclude the Telerik Sparkline elements.
Addresses #780
N/A
> fix: Make Telerik Sparkline elements not fail the Bounding Rectangle rule anymore

- build/prbuild.yml
- src/Rules/Resources/ConditionDescriptions.resx
- src/Rules/Resources/Descriptions.resx
- src/Rules/Resources/ErrorMessages.resx
- tools/scripts/verification.scripts/ResourceStringCommentVerification.ps1
As the resource strings in the core, rules, and ruleselection projects will be localized soon, it is important that we include any necessary translator comments along with those resources. We have gone through and added comments in previous PRs, but this PR adds a script to our PR builds to verify that we continue to have translator notes for all resource strings in those projects.
The script does not include the resource files for projects that are not localized right now, since there are quite a lot of strings in those projects that do not have comments yet. If we ever decide to localize those projects, it will be simple to remove them from the exclude list in this script.
> feat(localization): Add script to check resource strings for comments

- src/CI/CI.csproj
- tools/scripts/CopyLocalizedFiles.ps1
In https://github.com/microsoft/axe-windows/pull/786#discussion_r1005849979, the suggestion was made to have `CopyLocalizedFiles.ps1` detect which projects had localized folders to copy, as oppose to requiring that `src\CI\CI.csproj` call them out explicitly. This PR makes that change. The logic is as follows:
1. Start with the solution folder
2. Walk through all child directories of the solution folder (these are the project folders)
3. Check for the existence of a `bin\Release\netstandard2.0\localize` directory within each project. This is the folder created by MicroBuild if localization is enabled
4. If the folder exists, call into the code that was already in place in the script.
Within the script, some internal function names have been massaged to better reflect what they do. …
> feat(localization): Refactor script to auto-detect localized projects

- src/AutomationTests/OutputFileHelperTests.cs
The pipeline often times out in the `OutputFileHelperCtor_NullSystem_ThrowsException` test, which should take no time at all. This PR increases the timeout to 15 seconds, with a comment why it's there.
Reduce pipeline flakiness
> chore: Increase timeout of test that causes pipeline issues

- src/Actions/Actions/DataManager.cs
- src/Actions/Actions/ListenAction.cs
- src/Actions/Actions/LoadActionParts.cs
- src/Actions/Actions/SelectAction.cs
- src/Actions/Attributes/InteractionLevelAttribute.cs
- src/Actions/Contexts/ElementContext.cs
- src/Actions/Contexts/ElementDataContext.cs
- src/Actions/Trackers/BaseTracker.cs
- src/Actions/Trackers/FocusTracker.cs
- src/Actions/Trackers/MouseTracker.cs
- src/Actions/Trackers/TreeTracker.cs
Apply analyzer-led removal of unneeded `this.` prefixes in the `Actions` project. After locally making the changes in #796, the IDE highlighted the `this.` prefixes that were not needed.
The code was originally written by folks who used `this.` _everywhere_ because that was the pattern in the team that they came from. Over time, that pattern has fallen by the wayside and now the code is very inconsistent. This PR is part of a series of PRs intended to increase the code consistency by removing unnecessary `this`. usage wherever possible.
> chore: Analyzer-led removal of unneeded "this." prefixes in the Actions project

- src/Core/Bases/A11yElement.cs
- src/Core/Bases/A11yPattern.cs
- src/Core/Bases/A11yPatternProperty.cs
- src/Core/Bases/A11yProperty.cs
- src/Core/Results/RuleResult.cs
- src/Core/Results/ScanMetaInfo.cs
- src/Core/Results/ScanResult.cs
- src/Core/Results/ScanResults.cs
- src/Core/Types/TypeBase.cs
Apply analyzer-led removal of unneeded `this.` prefixes in the `Core` project. After locally making the changes in #796, the IDE highlighted the `this.` prefixes that were not needed.
The code was originally written by folks who used `this.` _everywhere_ because that was the pattern in the team that they came from. Over time, that pattern has fallen by the wayside and now the code is very inconsistent. This PR is part of a series of PRs intended to increase the code consistency by removing unnecessary `this`. usage wherever possible.
> chore: Analyzer-led removal of unneeded "this." prefixes in the Core project

- src/RulesTest/Library/ButtonInvokeAndExpandCollapsePatternsTests.cs
- src/RulesTest/Library/ButtonInvokeAndTogglePatternsTests.cs
- src/RulesTest/Library/ButtonShouldHavePatternsTests.cs
- src/RulesTest/Library/ButtonToggleAndExpandCollapsePatternsTests.cs
- src/RulesTest/Library/ControlShouldSupportExpandCollapsePatternTests.cs
- src/RulesTest/Library/ControlShouldSupportGridPatternTests.cs
- src/RulesTest/Library/ControlShouldSupportTablePatternTests.cs
- src/RulesTest/Library/LandmarkIsTopLevelTests.cs
- src/RulesTest/Library/LocalizedControlTypeIsNotCustomTests.cs
- src/RulesTest/Library/LocalizedControlTypeIsNotCustomWPFGridCellTests.cs
- src/RulesTest/Library/LocalizedControlTypeIsNotWhiteSpaceTests.cs
- src/RulesTest/Library/LocalizedControlTypeIsReasonableTests.cs
- src/RulesTest/Library/NameIsNotWhiteSpaceTests.cs
- src/RulesTest/Library/SplitButtonInvokeAndTogglePatternsTests.cs
- src/RulesTest/MockA11yElement.cs
- src/RulesTest/PropertyConditions/ElementGroupsTests.cs
Apply analyzer-led removal of unneeded `this.` prefixes in the `RulesTest` project. After locally making the changes in #796, the IDE highlighted the `this.` prefixes that were not needed.
The code was originally written by folks who used `this.` _everywhere_ because that was the pattern in the team that they came from. Over time, that pattern has fallen by the wayside and now the code is very inconsistent. This PR is part of a series of PRs intended to increase the code consistency by removing unnecessary `this`. usage wherever possible.
> chore: Analyzer-led removal of unneeded "this." prefixes in the RulesTest project

- src/.editorconfig
Enable analyzer rules to call out places where `this.` is used unnecessarily
The code was originally written by folks who used `this.` _everywhere_ because that was the pattern in the team that they came from. Over time, that pattern has fallen by the wayside and now the code is very inconsistent. This PR is part of a series of PRs intended to increase the code consistency by removing unnecessary `this`. usage wherever possible.
> chore: Enable analyzer flags to catch unneeded "this." prefixes

- src/Rules/Library/BoundingRectangleNotNullListViewXAML.cs
- src/Rules/Library/BoundingRectangleNotNullTextBlockXAML.cs
- src/Rules/Library/ClickablePointOnScreenWPF.cs
- src/Rules/Library/ControlShouldSupportSetInfoWPF.cs
- src/Rules/Library/ControlShouldSupportTextPatternEditWinform.cs
- src/Rules/Library/EdgeBrowserHasBeenDeprecated.cs
- src/Rules/Library/FrameworkDoesNotSupportUIAutomation.cs
- src/Rules/Library/IsControlElementTrueRequiredButtonWPF.cs
- src/Rules/Library/IsControlElementTrueRequiredTextInEditXAML.cs
When we added the framework issue links, we added them as aka.ms links, which are primarily intended for marketing-related links. In-product links should use fwlinks, which just assign a numeric value to each page. This PR updates the rules to point directly to the fwlink versions, while the redirect system has been already updated to point the existing aka.ms links to their new fwlink counterparts, so that we only need to worry about maintaining the fwlinks going forward. Here is the table that details the mapping between the old links, the new links, and the target pages:
aka.ms link | fwlink | target page
--- | --- | ---
https://aka.ms/FrameworkIssue-BoundingRectangleNotNullListViewXAML  | https://go.microsoft.com/fwlink/?linkid=2214242 | …
> fix: Use correct type of redirects

- src/CoreTests/Bases/A11yElementTests.cs
- src/CoreTests/Bases/A11yPatternPropertyTests.cs
- src/CoreTests/Bases/A11yPatternTests.cs
- src/CoreTests/Bases/A11yPropertyTests.cs
- src/CoreTests/Misc/MiscTests.cs
- src/UnitTestSharedLibrary/Utility.cs
There are several places where the test code has things like `A11yElement ke`, which seems like a very odd naming choice. The `A11yElement` class was renamed in 2019, and `ke` was derived from the old class name. This PR renames all instances of `ke` to `element`.
Clean up remnants of old code
> chore: rename "ke" variables

- src/DesktopTests/Types/TextAttributeTemplateTests.cs
Code standards are very inconsistent throughout the code base. This PR contains the changes needed to make the `DektopTests` project consistent after locally applying #810. The renames were all done through the IDE, and in most cases the IDE-suggested name was used. In cases where the IDE-supplied name seemed odd, I chose a name that seemed appropriate.
> chore: Update private field names in DesktopTests project

- src/Core/Bases/A11yElement.cs
- src/Core/Bases/A11yPattern.cs
- src/Core/Bases/A11yPatternProperty.cs
- src/Core/Bases/A11yProperty.cs
Code standards are very inconsistent throughout the code base. This PR contains the changes needed to make the `Core` project consistent after locally applying #810. The renames were all done through the IDE, and in most cases the IDE-suggested name was used. In cases where the IDE-supplied name seemed odd, I chose a name that seemed appropriate.
> chore: Update private field names in Core project

- src/AutomationTests/AutomationIntegrationTests.cs
- src/AutomationTests/ScanResultsAssemblerTests.cs
Code standards are very inconsistent throughout the code base. This PR contains the changes needed to make the `AutomationTests` project consistent after locally applying #810. The renames were all done through the IDE, and in most cases the IDE-suggested name was used. In cases where the IDE-supplied name seemed odd, I chose a name that seemed appropriate.
> chore: Update private field names in AutomationTests project

- src/ActionsTests/Actions/CaptureActionTests.cs
Code standards are very inconsistent throughout the code base. This PR contains the changes needed to make the `ActionsTest` project consistent after locally applying #810. The renames were all done through the IDE, and in most cases the IDE-suggested name was used. In cases where the IDE-supplied name seemed odd, I chose a name that seemed appropriate.
> chore: Update private field names in ActionsTests project

- src/.editorconfig
Code standards for private members are very inconsistent through the code base. This PR adds the following checks to the `.editorconfig` file:
- Non-static private member names start with underscore and use camelCase
- Static private member names start don't have underscore and use PascalCase
This PR will be merged after all associated project-specific PR's are merged
> chore: Update private fields rules in editorconfig file

- src/Actions/Attributes/InteractionLevelAttribute.cs
- src/Actions/Trackers/BaseTracker.cs
- src/Desktop/ColorContrastAnalyzer/ColorContrastRunner.cs
- src/Desktop/ColorContrastAnalyzer/ColorPair.cs
This PR tidies up some properties that I've noticed in the code:
1. `InteractionLevelAttribute.InteractionLevel` can be an auto-property
2. `BaseTracker.ProcessId` can be a protected property instead of an internal field
3. `ColorPair` can be a little simpler it the foreground color and background color are implemented as properties
Code clarity and control
> chore: Update some properties

- src/Actions/Actions/SaveAction.cs
- src/Core/Bases/A11yPatternProperty.cs
- src/Core/Bases/A11yProperty.cs
- src/Core/Types/LegacyIAccessibleRoleType.cs
- src/CoreTests/Types/LegacyIAccessibleRuleTypeTests.cs
- src/Desktop/UIAutomation/Patterns/LegacyIAccessiblePattern.cs
AIWin [#1454](https://github.com/microsoft/accessibility-insights-windows/issues/1454) requests that we add the enum name for MSAA role types. This change provides the mapping, and it will light up in AIWin after this change gets published and picked up.
We add the `LegacyIAccessibleRoleType` class to map from numeric values to MSAA role types. We then add this to `A11yProperty` to capture this on the element. Finally, we need to expose this via the `A11yPatternProperty`, which leverages the `LegacyIAccessibleRoleType` class to get the name. In order to avoid confusing quotation marks around the mapped role, we add `A11yPatternProperty.OmitQuotesFromString`, which gets set only for `LegacyIAccessiblePattern.Role`. When writing out the JSON file, we set the flag to omit null values, so …
> fix: Add MSAA role name to LegacyIAccessiblePattern.Role

- src/Desktop/UIAutomation/CustomObjects/Registrar.cs
- src/Rules/Extensions/ExtensionMethods.cs
This PR cleans up 2 things:
1. Renaming `Registrar.sDefaultInstance` to `Registrar.DefaultInstance` to match naming guidelines
2. Removing an unused parameter from an extension method. The entire method itself seems to be unused but I left it for now.
I'd love to remove all unused methods, but I'm not sure how to identify them in an efficient way
> chore: Tiny code cleanups that got missed before

- src/.editorconfig
- src/AutomationTests/OutputFileHelperTests.cs
- src/Core/Bases/A11yElement.cs
- src/Core/Bases/A11yProperty.cs
- src/Core/CustomObjects/Converters/EnumTypeConverter.cs
- src/Core/CustomObjects/Converters/PointTypeConverter.cs
- src/Core/Misc/ExtensionMethods.cs
- src/Core/Misc/PackageInfo.cs
- src/CoreTests/CustomObjects/ConfigTests.cs
- src/CoreTests/CustomObjects/Converters/StringConverterTests.cs
- src/Desktop/ColorContrastAnalyzer/Color.cs
- src/Desktop/ColorContrastAnalyzer/ColorPair.cs
- src/Desktop/ColorContrastAnalyzer/ContrastTransition.cs
- src/Rules/RuleProvider.cs
- src/Win32/HighContrast.cs
- src/Win32/HighContrastData.cs
IDE0049 nudges us toward language-specific type names instead of framework type names, so things like:
- `int` instead of `System.Int32`
- `uint` instead of `System.UInt32`
- `double` instead of `System.Double`
- `string` instead of `System.String`
- `object` instead of `System.Object`
- `bool` instead of `System.Boolean`
Most of the code is already following this rule, but there are some outliers. This PR updates `.editorconfig` to call out these issues, then also applies the changes across all projects
> chore: Consistently follow IDE0049

- build/NetStandardTest.targets
- build/signedbuild.yml
- src/ActionsTests/ActionsTests.csproj
- src/AutomationTests/AutomationTests.csproj
- src/CLI/CLI.csproj
- src/CLITests/CLITests.csproj
- src/CLI_Full/CLI_Full.csproj
- src/CLI_Installer/CLI_Installer.wixproj
- src/CLI_Installer/Product.wxs
- src/CoreTests/CoreTests.csproj
- src/Desktop/Desktop.csproj
- src/DesktopTests/DesktopTests.csproj
- src/InteropDummy/InteropDummy.csproj
- src/OldFileVersionCompatibilityTests/OldFileVersionCompatibilityTests.csproj
- src/RuleSelectionTests/RuleSelectionTests.csproj
- src/RulesTest/RulesTests.csproj
- src/SystemAbstractionsTests/SystemAbstractionsTests.csproj
- src/TelemetryTests/TelemetryTests.csproj
- src/Win32Tests/Win32Tests.csproj
As called out in this [blog post](https://devblogs.microsoft.com/dotnet/net-core-3-1-will-reach-end-of-support-on-december-13-2022/), .NET Core 3.1 ends LTS on 13 December 2022, which is coming up quickly. Some of our .NET dependencies are dropping support for .NET Core 3.1, so in order to stay on current binaries, we are shifting our EXE's to .NET 6.0. This includes the CLI and all test projects. The libraries in the NuGet package will continue to build using .NET Standard 2.0, so they'll continue to work in either .NET or .NET Framework applications. They will also continue to be Windows-specific, which makes sense since UIA is a Windows-specific technology.
Validation included:
1. Run changes through the signed build pipeline. Artifacts are …
> chore: Migrate EXE's from .NET Core 3.1 to .NET 6.0

- src/MsiFileTests/MsiFileTests.csproj
After merging #834, I stopped to wonder why we needed WPF for this test...and couldn't find a reason. This PR just removes the `UseWPF` flag and updates the target accordingly
> chore: We don't need to use WPF in this test

- src/MsiFileTests/WxsValidationTests.cs
The signed release build is including a localization file that is not included in the other builds. Since the CLI is not yet localized, we are not including the localized files and should add this file to the list of files that we intentionally exclude from the MSI package.
Unblock signed builds
> fix: Signed build is failing WXS validation

- tools/scripts/verification.scripts/ValidateCLI.ps1
When #833 changed the CLI to target .NET 6.0, it changed the path of the locally-built CLI, which (in turn) broke the validation script. This just fixes the validation script and makes the displayed instructions a little bit clearer.
Validation scripts should work
> chore: Fix CLI validation script

- tools/LocTestingSampleApp/LocTestingSampleApp.csproj
- tools/LocTestingSampleApp/LocTestingSampleApp.sln
- tools/LocTestingSampleApp/Program.cs
- tools/LocTestingSampleApp/README.md
Adds a test app that can be used to test axe-windows localization to the tools directory. See the README for details on usage.
Keep all tools related to axe-windows in one place
> chore: Add localization testing tool to tools directory

- src/CLI_Installer/Product.wxs
- src/MsiFileTests/WxsValidationTests.cs
This is the analog to [AIWin 1483](https://github.com/microsoft/accessibility-insights-windows/pull/1483). 
This fixes some issues with the MSI checker:
1. Due to a logic error, files were returned _only_ if a set of excluded files was provided. This empty set was not caught as a problem. These have both been fixed.
2. We weren't passing the correct component names in 1, so we were returning empty sets of files. This empty set was also not caught as a problem. This has been fixed.
3. As written, the checker assumed that everything in a component comes from the same build folder, which is OK in this project. For consistency with AIWIn, though, we ignore the source path of the file and validate the _set_ of files in the folder.
There was also 1 place in the WXS file where we were using a …
> chore: Fix gaps in WxsValidationTests

- .gitignore
Current versions of VS store user-specific settings in `launchSettings.json`. This file shouldn't be in the repo, so adding it to the `.gitignore` file seems appropriate.
Enable local debugging without risk of contaminating the repo with these files.
> chore: Ignore launchSettings.json

- tools/WildlifeManager/src/WildlifeManager/MainWindow.xaml
Prior to this change none of the controls in the wildlife test app had automation IDs. This doesn't really matter since it's just a test app, but it means the automation ID column in the VS accessibility checker is not populated when testing this app. This is a simple improvement to make the wildlife test app better to demo with. 
Improve demo app
> chore: add automation ids to failing controls in wildlife test app

- src/Rules/Resources/HowToFix.Designer.cs
- src/Rules/Resources/HowToFix.resx
This PR adds additional guidance for when the `NameIsInformative` rule can be ignored safely.
Related to #874.
> Fix: Clarify "how to fix" guidance for NameIsInformative rule violations

- src/Rules/Resources/HowToFix.resx
In #881, the term "Accessibility Insights for Web" was erroneously translated. Add better guidance in the translator comment around this term.
> Fix: Update translator comment for chromium rule

- src/RulesMD/RulesMD.csproj
Our build pipeline recently broke in the Roslyn analyzers phase. Upon investigation, the problem was that the `RulesMD` project uses `$(VisualStudioVersion)`, which gets redefined from 16.0 to 17.0 when the Roslyn analyzer task is run. Future versions of the Roslyn analyzer task will support 17.0, but the objective here is to unblock the pipeline. Once we move to the updated Roslyn analyzer, this PR should be backed out.
Validation run of this change can be found [here](https://mseng.visualstudio.com/1ES/_build/results?buildId=19493022&view=logs&j=efe68385-d402-5492-a2cf-bc47ec32e784&t=e38751e8-0dc8-5e3c-8d46-e18c39d37211&l=3911). I canceled the build after the Roslyn step completed, since Roslyn was the only thing we were fixing.
We need to be able to ship
This change applies locally, …
> fix: Temporary workaround to unblock build

- src/Rules/Library/NameIsInformative.cs
- src/RulesTest/Library/NameIsInformativeTests.cs
- src/RulesTest/MonsterTest.cs
This PR excludes the `Group` and `Text` UIA control types from the `NameIsInformative` rule in an attempt to reduce false positives.
Re #874.
> fix: Exclude Group and Text controls from NameIsInformative due to high false-positive rate

- src/.editorconfig
- src/Actions/Actions/DataManager.cs
- src/Actions/Trackers/TreeTracker.cs
- src/ActionsTests/Actions/ScreenShotActionTests.cs
- src/ActionsTests/Contexts/ScopedActionContextTests.cs
- src/AutomationTests/AutomationIntegrationTests.cs
- src/AutomationTests/SnapshotCommandTests.cs
- src/CLITests/OptionsEvaluatorTests.cs
- src/CLITests/OptionsTests.cs
- src/CLITests/OutputGeneratorTests.cs
- src/Core/Misc/ExtensionMethods.cs
- src/Desktop/UIAutomation/EventHandlers/ActiveTextPositionChangedEventListener.cs
- src/Desktop/UIAutomation/EventHandlers/EventListener.cs
- src/Desktop/UIAutomation/EventHandlers/EventListenerFactory.cs
- src/Desktop/UIAutomation/EventHandlers/NotificationEventListener.cs
- src/Desktop/UIAutomation/EventHandlers/PropertyChangedEventListener.cs
- src/Desktop/UIAutomation/EventHandlers/StructureChangedEventListener.cs
- src/Desktop/UIAutomation/EventHandlers/TextEditTextChangedEventListener.cs
- src/DesktopTests/UIAutomation/CustomObjects/RegistrarTests.cs
- src/Rules/RuleFactory.cs
- src/RulesTest/Library/NameIsInformativeTests.cs
The latest version of Visual Studio analyzers are flagging some things that they didn't flag before. This PR represents a single pass through the project to update the appropriate fields. The commits are non-overlapping and it's possibly simplest to review on a per-commit basis.
Make analyzer suggestions more obvious in the IDE and less dangerous (i.e., don't use suggestions that require C# versions that we aren't guaranteed to have).
According to the C# language versioning [docs](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version), both .NET Standard 2.0 and .NET Framework default to C# 7.3, which is why we max out the suggestions there. The fields added to `.editorconfig` are based on the actual analyzer messages that occurred. I made no …
> chore: Apply/suppress new analyzer suggestions

- .github/dependabot.yml
The `CurrentFileVersionCompatibilityTests` project is intentionally pinned to old versions of `Axe.Windows` and `Newtonsoft.Json`. This is for testing only and not something that we ship. Dependabot knows to leave `Axe.Windows` alone, but we want updates to `Newtonsoft.Json` everywhere but in this project.
This PR creates a separate set of rules for the `CurrentFileVersionCompatibilityTests` project. This should work, based on the dependabot.yml [docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file), but we'll ultimately find out empirically.
Reduce overhead from unwanted dependabot changes
> chore: Prevent dependabot updates of pinned package versions

- .github/dependabot.yml
#889 was an dependabot.yml experiment that failed. Its intent was to reduce dependabot noise in the `src/CurrentFileVersionCompatibilityTests` folder. It actually made things worse, as shown by dependabot change #891, which was a direct result of the change. I did a little more research and found https://github.com/dependabot/dependabot-core/issues/4364, which is an ongoing request to allow the same ecosystem to support different dependabot rules in different folders. It has lots of upvotes but it doesn't seem to be getting any traction.
This PR simply reverts the change from #889
Minimize build noise
> chore: Revert failed dependabot.yml experiment

- build/signedbuild.yml
- tools/scripts/pipeline/build/create-tsa-config.ps1
Our compliance tools are are being deprecated. Our signed build warnings include the following output:
Job | Task | Warning
--- | --- | ---
ComplianceDebug | Run AutoApplicability |  This tool is no longer supported. Please remove this build task from your build definition.
ComplianceDebug | Run CredScan | Please upgrade the version of this build task in your build to major version: 3.
ComplianceDebug | Run PoliCheck | Please upgrade the version of this build task in your build to major version: 2.
ComplianceDebug | Run Roslyn analyzers | Please upgrade the version of this build task in your build to major version: 3.
ComplianceDebug | Create Security Analysis Report (CredScan, RoslynAnalyzers, and PoliCheck) | Please upgrade the version of this build task in your build to major version: …
> chore: Update compliance tools to the next generation

- src/AutomationTests/AutomationIntegrationTests.cs
- src/AutomationTests/TimedExecutionWrapper.cs
Automation integration tests frequently have timeouts in our pipelines, which is bad. This PR replaces the VSTest-controlled timeout with a timeout that we control, so that we can return Inconclusive if a test times out in the pipeline. It also slightly increases the timeouts on a couple of tests and makes the timeout directly proportional to the number of processes being spun up.
This will probably be easier to review if you enable the "Hide whitespace" setting
Flaky tests make life hard.
> chore: Make integration test timeouts more tolerant

- build/signedbuild.yml
This is the Axe.Windows analog of https://github.com/microsoft/accessibility-insights-windows/pull/1569. We currently run the unit tests _after_ running the Roslyn analyzers. The problem is that Running the Roslyn analyzers rebuilds the solution, which could potentially create subtle differences between the tests that run locally and the tests that run in the ComplianceDebug pipeline job. This PR simply runs the unit tests immediately after building the solution so that we increase the consistency of the tests that we run.
Make pipeline tests more like local tests
> chore: Run unit tests before running the Roslyn analyzer

- build/signedbuild.yml
Note: This is the analog of https://github.com/microsoft/accessibility-insights-windows/pull/1578
The old version of TSA automatically added the branch name to the database, which was kind of wasteful since new databases were created from each non-main branch used for a signed test build. The new version of TSA uses the same database name for all branches, which means that builds from any branch could create noise in the production version. To solve both problems, this PR restricts the TSA upload to just the main branch. All TSA artifacts are created as usual, but the upload task gets skipped. This is based on the method shown [here](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml%2Cstages).
The Validation build skips both TSA …
> chore: Limit TSA uploads to main branch

- src/Rules/Resources/ConditionDescriptions.resx
- src/Rules/Resources/Descriptions.resx
- src/Rules/Resources/HowToFix.resx
This PR adds (machine-readable) annotations to relevant translator comments to prevent the localization of technical terms and product names.
[Bug 802071](https://dev.azure.com/ceapex/CEINTL/_workitems/edit/802071) (internal access required to view).
> Chore(Lock-keyword): Replace narrative translator guidance with machine-readable annotations

- src/AutomationTests/AutomationIntegrationTests.cs
As called out in #912, our PR builds are breaking due to a test problem. This PR simply bypasses the test scenario that is failing
We need to be able to publish PR's
This doesn't fix the issue--that will be a separate PR after we understand what is happening
> chore: Temporarily skip Scan_Integration_WebViewSample(true) in pipelines

- src/Rules/Library/LocalizedControlTypeIsReasonable.cs
- src/Rules/PropertyConditions/SystemProperties.cs
- src/RulesTest/Library/LocalizedControlTypeIsReasonableTests.cs
- src/RulesTest/MonsterTest.cs
- src/RulesTest/PropertyConditions/SystemProperitesTests.cs
- src/RulesTest/PropertyConditions/SystemPropertiesTests.cs
https://github.com/microsoft/accessibility-insights-windows/issues/1572 called out the fact that the `LocalizedControlTypeReasonable` rule uses English language strings to validate localized names. The chosen solution was to change the `Condition` so that this rule only applies on English language systems. This PR adds a new `Condition` called `IsEnglish` that takes advantage of .NET's built-in support of 3 letter language codes as defined in the ISO 639-2 spec. For our purposes, we disable the rule for anything other than "eng". The check is case-insensitive, which probably isn't strictly necessary, but seemed like the safest bet.
Tested by setting my Windows language to French and verifying that `SystemPropertiesTests.OverriddenCultureName_ResetsToDefault` reports as inconclusive. It …
> fix: Skip English-specific rules on non-English systems

- src/Rules/Resources/Descriptions.Designer.cs
- src/Rules/Resources/Descriptions.resx
- src/Rules/Resources/HowToFix.Designer.cs
- src/Rules/Resources/HowToFix.resx
This PR:
* Removes some strings from `Locked` comments where they aren't used in the original message.
* Sets more appropriate scoping on some `Locked` usage.
* Adds some `Locked` keywords that were missed previously.
* General cleanup of strings (opportunistic typo fixing, etc.)
> Chore: improve usage of {Locked} keyword and minor string cleanup

- src/RulesMD/RulesMD.csproj
Revert #882. This was a temporary workaround while the build pipeline tools updated from VS16 to VS17. The signed validation build with this change is at https://dev.azure.com/mseng/1ES/_build/results?buildId=20035917&view=results.
Code hygiene
> chore: Remove variable that was added for Roslyn migration

- src/Rules/Resources/Descriptions.Designer.cs
- src/Rules/Resources/Descriptions.resx
- src/Rules/Resources/HowToFix.Designer.cs
- src/Rules/Resources/HowToFix.resx
This PR:
* Adds the C# keywords `true`, `false`, and `null` to `Locked` comments where used.
* Adds guidance to translators to alphabetize the list of standard landmark types, as done in English.
Follow-up of #919 and esn updates in #926.
> chore: Further changes to translator comments

- src/AutomationTests/AutomationIntegrationTests.cs
- src/Rules/Library/ChromiumComponentsShouldUseWebScanner.cs
- src/Rules/PropertyConditions/Relationships.cs
- src/RulesTest/Library/ChromiumComponentsShouldUseWebScannerTests.cs
https://github.com/microsoft/accessibility-insights-windows/issues/1625 points out that the `ChromiumComponentsShouldUseWebScanner` rule is flagging items that are outside the context of a web page, which goes against the rule's primary purpose. This change limits the `ChromiumComponentsShouldUseWebScanner` rule to elements within a HTML document (including the document itself).
While working on this, we discovered a bug in WebView2, which is tracked at https://github.com/MicrosoftEdge/WebView2Feedback/issues/3530.
Address https://github.com/microsoft/accessibility-insights-windows/issues/1625
As expected, only the `ChromiumComponentsShouldUseWebScanner` rule is impacted
Rule | Count Before | Count After
--- | --- | ---
An element of the given ControlType must not support the invoke …
> fix: Reduce noise in ChromiumComponentsShouldUseWebScanner rule

- src/Actions/Trackers/FocusTracker.cs
- src/Desktop/UIAutomation/DesktopElementExtensionMethods.cs
- src/Win32/Win32Helper.cs
- src/props/version.props
This PR excludes windows created on <kbd>Alt</kbd>+<kbd>Tab</kbd> from focus tracking that interfere with it, making apps that use focus tracking unusable for keyboard users on Windows 11.
microsoft/accessibility-insights-windows#1610
> fix: Exclude the Alt+Tab "task switching" UI from focus tracking on Sun Valley

- docs/AutomationReference.md
- src/Automation/Data/Config.cs
- src/Automation/SnapshotCommand.cs
- src/CLI/IOptions.cs
- src/CLI/Options.cs
- src/CLI/OptionsEvaluator.cs
- src/CLI/README.MD
- src/CLI/Resources/OptionsHelpText.Designer.cs
- src/CLI/Resources/OptionsHelpText.resx
- src/CLI/ScanRunner.cs
- src/CLITests/OptionsEvaluatorTests.cs
- src/CLITests/OptionsTests.cs
#935 requests that we provide a way for CLI users to create an `.a11ytest` file even when no errors are reported. This adds a `--alwayssavetestfile` option to the CLI, then plumbs it through to take effect. People using the automation interface can access this directly via the `Config.Builder.WithAlwaysSaveTestFile` method.
Address #935
> feat: Add ability to always save test file

- build/signedbuild.yml
- docs/BuildingTheCode.md
- src/CLI_Installer/CLI_Installer.wixproj
- src/CLI_Installer/Product.wxs
- src/CLI_Installer/packages.config
- src/MsiFileTests/WxsValidationTests.cs
Upgrade WixToolset to v4.0.1
Address issue #946
In WiX v4, it's easier than ever to build MSIs for each platform (x86, x64, arm64) using the exact same sources (with no conditional code).
The default build output directory for the MSI changes from `bin\$(Configuration)\...` to `bin\$(Platform)\$(Configuration)\...` where Platform = `x86`
This MSI contains suboptimal authoring, especially concerning the Windows Installer Best Practices relating to Component/File relationships. Generally speaking, each Component should have only one File. You can create ComponentGroups to group components as needed, but ComponentGroups don't survive in the MSI (they are an authoring-only concept).
> Upgrade WixToolset to v4.0.1

- tools/scripts/pipeline/build/clearly-defined/ValidateScript.bat
- tools/scripts/pipeline/build/clearly-defined/check-clearly-defined.ps1
Note: This change is a port of https://github.com/microsoft/accessibility-insights-windows/pull/1672
#954 had 2 bugs about namespaces:
1. Dependabot adds a `/src` component to the branch name of NuGet component. The script didn't take this into account and we ended up with an incorrect url
2. Dependabot omits the `@` from branch names of npm components that include a namespace. The script didn't take this into accoiunt and we ended up with an incorrect url
The fix in both cases is the same--we add a function to adjust the raw namespace that comes from parsing the branch name. 
It also includes a batch script to aid in script validation. If we encounter future branch names that go awry, we can just add additional test cases and have protection against breakage.
Tune the desired friction of …
> fix: Correct dependabot validation

- .github/dependabot.yml
- src/ActionsTests/ActionsTests.csproj
- src/AutomationTests/AutomationTests.csproj
- src/CLITests/CLITests.csproj
- src/CoreTests/CoreTests.csproj
- src/DesktopTests/DesktopTests.csproj
- src/MsiFileTests/MsiFileTests.csproj
- src/OldFileVersionCompatibilityTests/OldFileVersionCompatibilityTests.csproj
- src/RulesTest/RulesTests.csproj
- src/SystemAbstractionsTests/SystemAbstractionsTests.csproj
- src/TelemetryTests/TelemetryTests.csproj
- src/Win32Tests/Win32Tests.csproj
Since 4.20.x, Moq has introduced a privacy vulnerability that improperly handles user data. https://github.com/moq/moq/issues/1372 
This pins to 4.18.4 until we can confirm that those privacy concerns are resolved.
Privacy/Security
> chore: Pin Moq to 4.18.4

- src/ActionsTests/Misc/ExtensionMethodsTests.cs
- src/AutomationTests/ScanResultsAssemblerTests.cs
- src/CoreTests/Bases/A11yElementTests.cs
- src/CoreTests/Bases/A11yPatternPropertyTests.cs
- src/CoreTests/Bases/A11yPatternTests.cs
- src/CoreTests/Bases/A11yPropertyTests.cs
- src/CoreTests/CustomObjects/ConfigTests.cs
- src/CoreTests/CustomObjects/Converters/BoolConverterTests.cs
- src/CoreTests/CustomObjects/Converters/DoubleConverterTests.cs
- src/CoreTests/CustomObjects/Converters/ElementConverterTests.cs
- src/CoreTests/CustomObjects/Converters/EnumConverterTests.cs
- src/CoreTests/CustomObjects/Converters/IntConverterTests.cs
- src/CoreTests/CustomObjects/Converters/PointConverterTests.cs
- src/CoreTests/CustomObjects/Converters/StringConverterTests.cs
- src/CoreTests/CustomObjects/CustomPropertyTests.cs
- src/CoreTests/Misc/MiscTests.cs
- src/CoreTests/Results/ScanMetaInfoTests.cs
- src/CoreTests/Types/ControlTypesTests.cs
- src/CoreTests/Types/HeadingLevelTypeTests.cs
- src/CoreTests/Types/LegacyIAccessibleRuleTypeTests.cs
- src/CoreTests/Types/PatternTypesTests.cs
- src/CoreTests/Types/PropertyTypesTests.cs
- src/DesktopTests/ColorContrastAnalyzer/BitmapCollectionTests.cs
- src/DesktopTests/ColorContrastAnalyzer/ColorPairTests.cs
- src/DesktopTests/ColorContrastAnalyzer/ColorTests.cs
- src/DesktopTests/ColorContrastAnalyzer/ImageTests.cs
- src/DesktopTests/ColorContrastAnalyzer/ImageTestsV2.cs
- src/DesktopTests/Styles/StyleIdTests.cs
- src/DesktopTests/Utility/SupportedEventsTests.cs
- src/RulesTest/MonsterTest.cs
Similar to https://github.com/microsoft/accessibility-insights-windows/pull/1687, there are some irregularities in our test decorators. This PR is made up of the following global search & replace operations:
- `[TestClass()]` becomes `[TestClass]`
- `[TestMethod()]` becomes `[TestMethod]`
The extra parentheses on the decorators don't break anything, but they are non-standard and don't add any value. I've confirmed that all unit tests run as expected.
> chore: Fix test irregularities

- .github/dependabot.yml
Dependabot for our repos is scheduled to run at fairly different times that are inconvenient for some geographies. This PR moves this repo's dependabot time to 09:00 UTC (14:30 IST, 02:00 PDT, 01:00 PST).
Part of [Feature 2083093](https://mseng.visualstudio.com/1ES/_queries/edit/2083093) (internal access required to view).
> feat(oncall-vendor-transition): Move Dependabot to 09:00 UTC

- .github/dependabot.yml
Explicitly set the Dependabot PR limit to 10.
Consistency is good.
> Chore: Set dependabot PR limit to 10

- src/CLI_Installer/Product.wxs
#833 updated the CLI from .NET Core 3.1 to .NET 6.0 because .NET Core 3.1 had reached its end of life. Unfortunately, the error message that tells the user the minimum version was not updated. This PR simply corrects that omission and tells the user to install .NET 6.0 or newer.
Usability
The CLI no longer supports Windows 7. This is tracked at #980 and not addressed here.
> chore: Update installer message for .NET version

- src/CLI_Installer/Product.wxs
MSI installer should warn user about unsupported Operating System.
Associated Issue: https://github.com/microsoft/axe-windows/issues/980
Fix implemented for:
- To warn user about unsupported Operating System by displaying a message as: Axe.Windows Command Line Interface (CLI)
requires .NET 6, which is supported on Windows 10 or newer.
- Screenshot of the implemented fix: 
- Locally tested all the changes and they are working as expected.
> fix: MSI installer should warn user about unsupported OS. 

- build/signedbuild.yml
This PR is for migrating Microsoft.axe-windows(signed) pipeline to 1ES MicroBuild Template.
Old run link: https://dev.azure.com/mseng/1ES/_build/results?buildId=25829758&view=results
New run link: https://dev.azure.com/mseng/1ES/_build/results?buildId=25904428&view=results
Below are details:
1. Test cases are less in the new pipeline as we are filtering UI test cases in debug and release compliance job. These test cases are already filtered in Signed Release job as the agent pool used for micro build do not support it. After migration debug and release compliance jobs will also run on the same agent pool instead of default ADO agent pool. These test cases are running successfully in PR and CI Pipelines. Filter used is --filter TestCategory!=Integration.
2. We have to keep running …
> feat(Pipeline Migration to 1ES Template): migrated signed build to 1ES micro build template

- build/prbuild.yml
1ES PT adds tags to pipeline runs using the access token provided by ADO. In the case of pipeline runs against forked repos of a GitHub repo, the access token does not have Edit build quality permissions and hence cannot add tags. To unblock those pipelines, skipped tagging by using the option SkipBuildTagsForGitHubPullRequests.
Verified that the only change in the pipeline run is that it do not add "1ES.PT.Unofficial" tag on the Run. In place of that it adds below warning message.
##[warning]1ES PT Warning: Skipping build tags as this build is a pull request form github which does not have permissions to add tags.
> fix: disable custom tag task for the forked repo PRs.

- .github/dependabot.yml
- .github/policies/resourceManagement.yml
- build/NetStandardAll.targets
- build/NetStandardRelease.targets
- build/NetStandardTest.targets
- build/check-dependencies.yml
- build/common.targets
- build/delaysign.targets
- build/prbuild.yml
- build/settings.targets
- build/signedbuild.yml
- tools/scripts/verification.scripts/LicenseHeaderVerification.ps1
While updating to 1ES pipeline templates, we realized that several of our files were missing copyright headers. This adds them and updates the tooling to ensure that we don't miss them in these files types in the future. Copyright headers were all added by running the script.
The policy service file can't have comments without breaking the bot, so an exception is made for any files under `.github\policies`.
Address #991
> fix: Add license headers to .yml and .targets files

- src/CLI_Installer/CLI_Installer.wixproj
Update WixToolset.*.* to address CVE-2024-29188. The existing code does not appear to actually be vulnerable, but this is cheap insurance. 
The change was made via Visual Studio, which removed the extra newlines. I'm not a fan of having the tool pull these out but it's not worth the hassle of trying to keep them in if Visual Studio insists on removing them.
CVE
> chore: Update Wix packages to version 4.0.5

- docs/AutomationReference.md
- src/Automation/Data/ScanOptions.cs
- src/Automation/Interfaces/IScanTools.cs
- src/Automation/Interfaces/ITargetElementLocator.cs
- src/Automation/ScanTools.cs
- src/Automation/Scanner.cs
- src/Automation/SnapshotCommand.cs
- src/Automation/TargetElementLocator.cs
- src/AutomationTests/A11yAutomationUtilities.cs
- src/AutomationTests/AutomationIntegrationTests.cs
- src/AutomationTests/AutomationTests.csproj
- src/AutomationTests/SnapshotCommandTests.cs
- src/CLI/IOptions.cs
- src/CLI/Options.cs
- src/CLI/OptionsEvaluator.cs
- src/CLI/OutputGenerator.cs
- src/CLI/README.MD
- src/CLI/Resources/DisplayStrings.Designer.cs
- src/CLI/Resources/DisplayStrings.resx
- src/CLI/Resources/OptionsHelpText.Designer.cs
- src/CLI/Resources/OptionsHelpText.resx
- src/CLI/ScanRunner.cs
- src/CLITests/OptionsEvaluatorTests.cs
- src/CLITests/OptionsTests.cs
- src/CLITests/OutputGeneratorTests.cs
- src/CLITests/TextWriterVerifier.cs
- src/Core/Bases/A11yElement.cs
- src/Desktop/UIAutomation/A11yAutomation.cs
- src/RulesTest/MockA11yElement.cs
Adds:
- ScanOptions property settable to IntPtr for HWND of root of subtree to be scanned
- Teach PID descendants search to operate on HWND's subtree instead of GetRootElement
- Add Integration test for test app leaf node scan
Proposal to address issue #1021 
I exposed internals of A11yAutomation to the Integration Tests project so I could find a relevant IUIAutomationElement for testing the ScanOptions' HWND constraint
You could implement this as a "ForWindowHandle()" constraint on the Config, but my external tools use the same scanner repeatedly - it's the individual Scans whose scope needs to be constrained.
> Add ScanOptions.NativeWindowHandle to scope Scans to rooted UIA sub-tree

- src/Core/Bases/A11yElement.cs
- src/Core/Bases/A11yProperty.cs
- src/Core/Bases/IA11yElement.cs
- src/Core/Misc/ExtensionMethods.cs
- src/Core/Types/PropertyType.cs
- src/CoreTests/Bases/A11yPropertyTests.cs
- src/CoreTests/Resources/A11yPropertyTest.hier
- src/Desktop/UIAutomation/DesktopElementExtensionMethods.cs
- src/Win32/NativeMethods.cs
- src/Win32/Win32Enums.cs
- src/Win32/Win32Helper.cs
This PR adds a "pseudo-property", `LogicalSize`, a normalized size based on an element's `BoundingRectangle` to aid in touch size calculations. 
Part of [Feature 2152841](https://mseng.visualstudio.com/1ES/_workitems/edit/2152841) (internal access required to view).
> feat(logical-size): Implement the LogicalSize property in Axe.Windows

- src/Core/Misc/ExtensionMethods.cs
- src/props/version.props
Axe.Windows follows [semantic versioning](https://semver.org), which states:
> Given a version number MAJOR.MINOR.PATCH, increment the... MINOR version when you add functionality in a backward compatible manner
I think 6d72b85 and d2a5c65 qualify as "new functionality" for these purposes, justifying a minor version bump.
Also includes a small fix-up of #1020 to prevent execution of `a11yProperty.ToSize` on properties other than `LogicalSize`.
Pre-release preparation.
> Chore: Bump minor version in preparation for release, fix-up #1020

- src/Rules/Library/SiblingUniqueAndFocusable.cs
The Win32 IP address control consists of a pane of edit fields, one per octet of an IPV4 address. As such, the `SiblingUniqueAndFocusable` rule is not appropriate for this control.
> fix: Exclude the win32 IP address control from the SiblingUniqueAndFocusable rule

- docs/RulesDescription.md
- src/Core/Enums/RuleId.cs
- src/Rules/Library/SiblingUniqueAndFocusableWin32.cs
- src/props/version.props
Due to a large number of false positives (and given the fact that Win32 applications don't support UIA natively), downgrade `SiblingUniqueAndFocusable` to `NeedsReview` in Win32 applications.
Addresses #1046. Supersedes #1038. Addresses microsoft/accessibility-insights-windows#1838.
> fix: Downgrade SiblingUniqueAndFocusable to NeedsReview for Win32 apps

- build/signedbuild.yml
This is new pre release version used in 1ES pipeline templates. But our TSA upload task still uses the older version (1.9.5) so this conflict is resulting into pipeline failure.
For now updating pipeline to optout for new version. 
There will be separate work item to update binskim to 4.3.1 version as new rules in 4.3.1 might discover issues which also need to be resolved so that pipeline does not break.
> chore: update binskim to optout 4.3.1 version

- src/ActionsTests/ActionsTests.csproj
- src/AutomationTests/AutomationTests.csproj
- src/CLITests/CLITests.csproj
- src/CoreTests/CoreTests.csproj
- src/DesktopTests/DesktopTests.csproj
- src/MsiFileTests/MsiFileTests.csproj
- src/OldFileVersionCompatibilityTests/OldFileVersionCompatibilityTests.csproj
- src/RuleSelectionTests/RuleSelectionTests.csproj
- src/RulesTest/RulesTests.csproj
- src/SystemAbstractionsTests/SystemAbstractionsTests.csproj
- src/TelemetryTests/TelemetryTests.csproj
- src/Win32Tests/Win32Tests.csproj
This PR replaces various testing-related package references with the `MSTest` metapackage, obviating the need for multiple package references for testing.
addresses #1076
> chore: Use of MSTest metapackage instead of multiple package references related to testing.
